apiVersion: v1
kind: LimitRange
metadata:
  name: engine-limits
  namespace: openbeam-engine
  labels:
    app.kubernetes.io/name: openbeam-engine
spec:
  limits:
    - type: Container
      default:
        cpu: "1"
        memory: 2Gi
      defaultRequest:
        cpu: 100m
        memory: 256Mi
      max:
        cpu: "16"
        memory: 64Gi
      min:
        cpu: 50m
        memory: 64Mi
    - type: PersistentVolumeClaim
      max:
        storage: 100Gi
      min:
        storage: 1Gi
