apiVersion: v1
kind: Namespace
metadata:
  name: openbeam-engine
  labels:
    app.kubernetes.io/name: openbeam-engine
    app.kubernetes.io/part-of: openbeam
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
