apiVersion: v1
kind: ServiceAccount
metadata:
  name: engine-cpu
  namespace: openplane-engine
  labels:
    app.kubernetes.io/name: engine-cpu
    app.kubernetes.io/component: cpu-service
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: engine-gpu
  namespace: openplane-engine
  labels:
    app.kubernetes.io/name: engine-gpu
    app.kubernetes.io/component: gpu-service
automountServiceAccountToken: false
