replicaCount: 1

persistence:
  enabled: true
  size: 1Ti
  storageClass: managed-csi

resources:
  requests:
    cpu: "1"
    memory: 4Gi
  limits:
    cpu: "4"
    memory: 12Gi

podSecurityContext:
  fsGroup: 1000

securityContext:
  runAsUser: 1000

tolerations:
  - key: "kubernetes.azure.com/scalesetpriority"
    operator: "Equal"
    value: "spot"
    effect: "NoSchedule"

podLabels:
  app: vespa
  app.kubernetes.io/name: vespa
  app.kubernetes.io/instance: vespa

service:
  type: ClusterIP
  ports:
    - name: vespa-http
      port: 8080
      targetPort: 8080
    - name: vespa-config
      port: 19071
      targetPort: 19071

livenessProbe:
  httpGet:
    path: /state/v1/health
    port: 8080
  initialDelaySeconds: 120
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /state/v1/health
    port: 8080
  initialDelaySeconds: 90
  periodSeconds: 5
