export const WORKFLOW_CONSTANTS = {
  HISTORY_SIZE_THRESHOLD: 10_000,
  CONTINUE_AS_NEW_THRESHOLD: 10_000,
} as const;

export const ACTIVITY_CONSTANTS = {
  DEFAULT_BATCH_SIZE: 100,
  LARGE_BATCH_SIZE: 1000,
  DEFAULT_MAX_CONCURRENCY: 1,
} as const;

export const REDIS_CONSTANTS = {
  IDEMPOTENCY_TTL_MS: 24 * 60 * 60 * 1000,
} as const;

export const WORKER_CONSTANTS = {
  DEFAULT_MAX_CONCURRENT_ACTIVITIES: 100,
  DEFAULT_MAX_CONCURRENT_WORKFLOWS: 100,
  DEFAULT_MAX_CACHED_WORKFLOWS: 1000,
  DEFAULT_STICKY_TIMEOUT_MS: 10_000,
} as const;

export const PARALLEL_CONSTANTS = {
  MIN_CONCURRENCY: 1,
  DEFAULT_BATCH_SIZE: 100,
} as const;

export const SAFETY_CEILINGS = {
  HARD_MAX_LOOP_ITERATIONS: 10_000,
  HARD_MAX_LOOP_DURATION_MS: 3_600_000,
  MAX_PARALLEL_BRANCHES: 100,
  MAX_SIGNAL_QUEUE_SIZE: 1000,
  MAX_EXECUTION_DURATION_MS: 14_400_000,
  MAX_TOTAL_NODE_EXECUTIONS: 50_000,
  MAX_LOOP_NESTING_DEPTH: 10,
} as const;
