apiVersion: v1
kind: ConfigMap
metadata:
  name: temporal-config
  namespace: openbeam
  labels:
    app.kubernetes.io/name: temporal-worker
    app.kubernetes.io/component: temporal-worker
    app.kubernetes.io/part-of: openbeam
data:
  namespace: "openbeam-prod"
  gcs-bucket: "openbeam-files"
  vespa-url: "http://vespa.vespa.svc.cluster.local:8080"
  engine-cpu-url: "http://engine-cpu.openbeam-engine.svc.cluster.local:8000"
  engine-gpu-url: "http://engine-gpu.openbeam-engine.svc.cluster.local:8001"
