apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openbeam

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: openbeam

resources:
  - serviceaccount.yaml
  - configmap.yaml
  - worker-deployment.yaml
  - service.yaml
  - pdb.yaml
  - networkpolicy.yaml
  - keda-scaledobject.yaml

images:
  - name: openbeam/worker
    newTag: latest
