apiVersion: v1
kind: ServiceAccount
metadata:
  name: temporal-worker
  namespace: openplane
  labels:
    app.kubernetes.io/name: temporal-worker
    app.kubernetes.io/component: temporal-worker
    app.kubernetes.io/part-of: openplane
automountServiceAccountToken: false
