-- AlterEnum
ALTER TYPE "AppType" ADD VALUE 'SAMSARA';
ALTER TYPE "AppType" ADD VALUE 'VERKADA';
ALTER TYPE "AppType" ADD VALUE 'AWS_IOT';
ALTER TYPE "AppType" ADD VALUE 'AZURE_IOT';
ALTER TYPE "AppType" ADD VALUE 'SMARTTHINGS';
