export const AGENT_UI_CONSTANTS = {
  CURSOR_BLINK_MS: 530,
  MAX_OUTPUT_LINES: 3,
  PREVIEW_LENGTH: 60,
  SCROLL_THRESHOLD: 500,
  MAX_VISIBLE_TOOLS: 5,
  THINKING_COLLAPSE_DELAY: 1000,
  MIN_GROUP_SIZE: 3,
  STATUS_FADE_DELAY: 300,
  DURATION_UPDATE_INTERVAL: 100,
} as const;

export type AgentUIConstants = typeof AGENT_UI_CONSTANTS;
