export {
  captureImmediate,
  flushServerClient,
  getBrowserClient,
  getServerClient,
  identifyImmediate,
  initBrowserClient,
  initServerClient,
  resetBrowserClient,
  shutdownBrowserClient,
  shutdownServerClient,
} from "./clients";
export {
  type AnalyticsConfig,
  getAnalyticsConfig,
  initializeAnalytics,
  isAnalyticsInitialized,
  resetAnalyticsConfig,
} from "./config";
export type {
  AIActionExecutedEvent,
  AICitationClickedEvent,
  AIConversationStartedEvent,
  AIFeedbackEvent,
  AIMessageSentEvent,
  AIResponseReceivedEvent,
  ConnectorConfiguredEvent,
  ConnectorDisconnectedEvent,
  ConnectorErrorEvent,
  ConnectorHealthCheckEvent,
  ConnectorOAuthCompletedEvent,
  ConnectorSetupStartedEvent,
  ConnectorSyncCompletedEvent,
  DocumentActionEvent,
  DocumentFeedbackEvent,
  DocumentInteractionEvent,
  DocumentViewedEvent,
  Feature,
  FeatureFirstUseEvent,
  FeatureUsageEvent,
  KeyboardShortcutUsedEvent,
  OnboardingCompletedEvent,
  OnboardingDropoffEvent,
  OnboardingStep,
  OnboardingStepEvent,
  PageViewEvent,
  SearchExecutedEvent,
  SearchRefinementEvent,
  SearchResultClickedEvent,
  SearchResultDwellEvent,
  SearchSatisfactionEvent,
  SearchZeroResultsEvent,
  SessionEndEvent,
} from "./events";

export {
  aiAssistantEvents,
  aiAssistantEventsServer,
  connectorEvents,
  connectorEventsServer,
  documentEvents,
  documentEventsServer,
  engagementEvents,
  onboardingEvents,
  searchEvents,
  searchEventsServer,
} from "./events";
export type {
  ExperimentConversionEvent,
  ExperimentExposureEvent,
} from "./feature-flags";
export {
  createExperiment,
  createFeatureFlagContext,
  experiments,
  featureFlags,
} from "./feature-flags";

export type {
  OrganizationActivityMetrics,
  OrganizationProperties,
  TeamActivityMetrics,
  TeamProperties,
} from "./groups";
export {
  organizationAnalytics,
  teamAnalytics,
} from "./groups";

export type {
  CostBreakdown,
  LLMFeedbackEvent,
  LLMGenerationEvent,
  LLMProvider,
  LLMSpanEvent,
} from "./llm";
export {
  calculateCost,
  createGenerationTraceContext,
  createGenerationTracker,
  estimateCostFromPrompt,
  getCostBreakdown,
  getModelCosts,
  llmAnalytics,
  registerModelCost,
  trackEmbedding,
  trackRetrieval,
  trackToolCall,
  withPostHogObservability,
} from "./llm";

export type {
  AIAnswerQualityMetrics,
  AIUsageMetrics,
  EngagementMetrics,
  GleanSearchQualityMetrics,
  QueryResult,
  RAGQualityMetrics,
  SearchQualityMetrics,
  SearchSessionMetrics,
  TeamSearchMetrics,
} from "./metrics";
export {
  calculateAllEngagementMetrics,
  calculateAllMetrics,
  calculateAverageDwellTime,
  calculateAverageSatisfactionScore,
  calculateAverageTimeToClick,
  calculateClickThroughRate,
  calculateDAUWAURatio,
  calculateFilterUsageRate,
  calculateFirstAttemptSuccessRate,
  calculateMRR,
  calculateMRRAtK,
  calculateQuerySuccessRate,
  calculateRefinementRate,
  calculateRetention,
  calculateSearchQualityScore,
  calculateStickiness,
  calculateWAUMAURatio,
  calculateZeroResultsRate,
  ENGAGEMENT_BENCHMARKS,
  GLEAN_BENCHMARKS,
  generateSearchQualityReport,
  gleanMetrics,
} from "./metrics";
export type {
  AIRequestMetrics,
  RAGQueryMetrics,
  SearchQueryMetrics,
  ToolCallMetrics,
} from "./observability";
export {
  addLogTransport,
  aiMetrics,
  circuitBreakerMetrics,
  configureLogger,
  createAILogger,
  createRAGLogger,
  getMetricsOutput,
  logAIGeneration,
  logger,
  logRAGQuery,
  logSearchQuery,
  logToolCall,
  ragMetrics,
  recordAIRequest,
  recordRAGQuery,
  recordSearchClick,
  recordSearchQuery,
  recordSearchSatisfaction,
  recordToolCall,
  searchMetrics,
  setMetricsAdapter,
  toolMetrics,
} from "./observability";
export type {
  ConsentPreferences,
  GDPRCompliantConfig,
  SensitiveFieldType,
  SessionRecordingConfig,
} from "./privacy";

export {
  defaultSessionRecordingConfig,
  detectRegion,
  excludeElement,
  getConsentPreferences,
  getDefaultConsentPreferences,
  getPrivacyAttributeForMaskedData,
  getPrivacyAttributeForSensitiveData,
  getSensitiveInputSelector,
  handleConsentGiven,
  hasGivenConsent,
  includeElement,
  initWithGDPRCompliance,
  isEUUser,
  isSessionRecordingActive,
  markSessionAsImportant,
  maskElement,
  PRIVACY_CLASSES,
  requestDataDeletion,
  requestDataExport,
  revokeConsent,
  sensitiveFieldTypes,
  startSessionRecording,
  stopSessionRecording,
  tagSessionRecording,
  unmaskElement,
  updateConsentPreferences,
} from "./privacy";
export type {
  AnalyticsContext,
  Environment,
  EventProperties,
  FeatureFlagPayload,
  FeatureFlagValue,
  GroupProperties,
  PersonProfiles,
} from "./types";
