FROM oven/bun:1.3.2

WORKDIR /app

COPY package.json bun.lock turbo.json ./
COPY apps/web/package.json ./apps/web/
COPY packages/*/package.json ./packages/

ARG HUGEICONS_PRO_AUTH_TOKEN
RUN if [ -n "$HUGEICONS_PRO_AUTH_TOKEN" ]; then \
      printf "@hugeicons-pro:registry=https://npm.hugeicons.com/\n//npm.hugeicons.com/:_authToken=%s\n" "$HUGEICONS_PRO_AUTH_TOKEN" > .npmrc; \
    fi

RUN bun install && rm -f .npmrc

COPY . .

RUN cd packages/db && bun run db:generate

WORKDIR /app/apps/web

EXPOSE 3001

CMD ["bun", "run", "dev"]
