import {
  AppType,
  AuthType,
  ConnectorType,
  SyncMode,
  type UnifiedApp,
} from "../types";

export const dynamics365App: UnifiedApp = {
  id: AppType.DYNAMICS_365,
  name: "Dynamics 365",
  category: "CRM",
  active: true,
  logo: AppType.DYNAMICS_365,
  short_description:
    "Search across accounts, contacts, leads, opportunities, and cases.",
  description:
    "Connect Microsoft Dynamics 365 to search across CRM entities via the Dataverse Web API. Supports OAuth for organizational accounts.",
  images: [],
  installed: false,
  type: "official",
  connectorType: ConnectorType.SOURCE,
  developerName: "Microsoft Corporation",
  website: "https://dynamics.microsoft.com",

  searchDisplay: {
    defaultIconKey: "Building",
    documentTypes: {
      account: { label: "account", iconKey: "Building", category: "account" },
      contact: { label: "contact", iconKey: "User", category: "contact" },
      lead: { label: "lead", iconKey: "UserPlus", category: "contact" },
      opportunity: {
        label: "opportunity",
        iconKey: "Target",
        category: "deal",
      },
      case: { label: "case", iconKey: "Ticket", category: "ticket" },
      event: { label: "activity", iconKey: "Calendar", category: "event" },
    },
  },

  features: [
    "Full and incremental sync of CRM entities",
    "Accounts, contacts, leads, opportunities, cases, and activities",
    "OData-based filtering for efficient delta sync",
    "Create and update records via Dataverse API",
  ],

  auth: {
    type: AuthType.OAUTH2,
    config: {
      authUrl: "https://login.microsoftonline.com/common/oauth2/v2.0/authorize",
      tokenUrl: "https://login.microsoftonline.com/common/oauth2/v2.0/token",
      redirectPath: "/connectors/setup/dynamics365/oauth/callback",
      scopes: ["User.Read", "offline_access"],
    },
  },

  streams: [
    {
      name: "accounts",
      label: "Accounts",
      description: "Companies and organizations in CRM",
      entityType: "resource",
      dataPoints: ["Name", "Industry", "Revenue", "Address", "Phone"],
      isPii: false,
      syncMode: SyncMode.PERIODIC,
      defaultInterval: 30,
      supportsBackfill: true,
    },
    {
      name: "contacts",
      label: "Contacts",
      description: "People associated with accounts",
      entityType: "identity",
      dataPoints: ["Name", "Email", "Phone", "Job Title", "Company"],
      isPii: true,
      syncMode: SyncMode.PERIODIC,
      defaultInterval: 30,
      supportsBackfill: true,
    },
    {
      name: "leads",
      label: "Leads",
      description: "Prospective customers and sales leads",
      entityType: "identity",
      dataPoints: ["Name", "Email", "Company", "Topic", "Rating"],
      isPii: true,
      syncMode: SyncMode.PERIODIC,
      defaultInterval: 30,
      supportsBackfill: true,
    },
    {
      name: "opportunities",
      label: "Opportunities",
      description: "Sales opportunities and deals",
      entityType: "activity",
      dataPoints: ["Name", "Value", "Stage", "Close Date", "Probability"],
      isPii: false,
      syncMode: SyncMode.PERIODIC,
      defaultInterval: 30,
      supportsBackfill: true,
    },
    {
      name: "cases",
      label: "Cases",
      description: "Customer service cases and incidents",
      entityType: "resource",
      dataPoints: ["Title", "Priority", "Status", "Description", "Customer"],
      isPii: false,
      syncMode: SyncMode.PERIODIC,
      defaultInterval: 30,
      supportsBackfill: true,
    },
    {
      name: "activities",
      label: "Activities",
      description: "Tasks, appointments, emails, and phone calls",
      entityType: "activity",
      dataPoints: ["Subject", "Type", "Status", "Due Date", "Description"],
      isPii: false,
      syncMode: SyncMode.PERIODIC,
      defaultInterval: 60,
      supportsBackfill: true,
    },
  ],

  settings: [
    {
      id: "oauth_input_method",
      label: "Credentials",
      description: "Enter Azure AD app credentials.",
      type: "select",
      required: true,
      value: "manual",
      options: [{ label: "Enter manually", value: "manual" }],
    },
    {
      id: "client_id",
      label: "Application (client) ID",
      description: "From Azure AD app registration",
      type: "text",
      required: true,
      value: "",
      placeholder: "00000000-0000-0000-0000-000000000000",
    },
    {
      id: "client_secret",
      label: "Client Secret",
      description: "From Azure AD app registration",
      type: "password",
      required: true,
      value: "",
    },
    {
      id: "org_url",
      label: "Dynamics 365 Organization URL",
      description:
        "Your Dynamics 365 environment URL (e.g. https://yourorg.crm.dynamics.com)",
      type: "text",
      required: true,
      value: "",
      placeholder: "https://yourorg.crm.dynamics.com",
    },
    {
      id: "tenant_id",
      label: "Tenant ID",
      description: "Azure AD tenant. Leave 'common' for multi-tenant.",
      type: "text",
      required: false,
      value: "common",
      placeholder: "common",
    },
    {
      id: "sync_leads",
      label: "Sync Leads",
      description: "Include leads in sync.",
      type: "switch",
      required: false,
      value: true,
    },
    {
      id: "sync_cases",
      label: "Sync Cases",
      description: "Include customer service cases in sync.",
      type: "switch",
      required: false,
      value: true,
    },
    {
      id: "sync_activities",
      label: "Sync Activities",
      description: "Include activities (tasks, appointments, etc.) in sync.",
      type: "switch",
      required: false,
      value: true,
    },
    {
      id: "lookback_days",
      label: "History (days)",
      description: "How far back to sync. Leave empty for unlimited.",
      type: "text",
      required: false,
      value: "",
      placeholder: "Unlimited",
    },
  ],
};

export default dynamics365App;
