{{- if .Values.appSecret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openplane.appSecretName" . }}
  labels:
    {{- include "openplane.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.appSecret.jwtSecret | quote }}
  LIVEKIT_API_KEY: {{ .Values.appSecret.livekitApiKey | quote }}
  LIVEKIT_API_SECRET: {{ .Values.appSecret.livekitApiSecret | quote }}
{{- end }}
