{{- if and .Values.services.web.enabled .Values.services.web.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "openplane.webName" . }}
  labels:
    {{- include "openplane.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: {{ .Values.services.web.service.type }}
  selector:
    {{- include "openplane.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: {{ .Values.services.web.service.port }}
      targetPort: {{ .Values.services.web.service.targetPort }}
      protocol: TCP
      {{- if and (or (eq .Values.services.web.service.type "NodePort") (eq .Values.services.web.service.type "LoadBalancer")) .Values.services.web.service.nodePort }}
      nodePort: {{ .Values.services.web.service.nodePort }}
      {{- end }}
{{- end }}
