import { OpenAPIHono } from "@hono/zod-openapi";
import type { AuthEnv } from "@/middleware/auth";
import aha from "./aha/aha.index";
import airtable from "./airtable/airtable.index";
import amplitude from "./amplitude/amplitude.index";
import asana from "./asana/asana.index";
import awsIot from "./aws-iot/aws-iot.index";
import azureDevOps from "./azure-devops/azure-devops.index";
import azureIot from "./azure-iot/azure-iot.index";
import bamboohr from "./bamboohr/bamboohr.index";
import benchling from "./benchling/benchling.index";
import bitbucket from "./bitbucket/bitbucket.index";
import box from "./box/box.index";
import bynder from "./bynder/bynder.index";
import canva from "./canva/canva.index";
import clickup from "./clickup/clickup.index";
import coda from "./coda/coda.index";
import confluence from "./confluence/confluence.index";
import coupa from "./coupa/coupa.index";
import datadog from "./datadog/datadog.index";
import docebo from "./docebo/docebo.index";
import docusign from "./docusign/docusign.index";
import dropbox from "./dropbox/dropbox.index";
import dynamics365 from "./dynamics365/dynamics365.index";
import egnyte from "./egnyte/egnyte.index";
import evernote from "./evernote/evernote.index";
import fellow from "./fellow/fellow.index";
import fifteenFive from "./fifteen-five/fifteen-five.index";
import figma from "./figma/figma.index";
import freshservice from "./freshservice/freshservice.index";
import github from "./github/github.index";
import gitlab from "./gitlab/gitlab.index";
import gmail from "./gmail/gmail.index";
import gong from "./gong/gong.index";
import googleCalendar from "./google-calendar/google-calendar.index";
import googleChat from "./google-chat/google-chat.index";
import googleDrive from "./google-drive/google-drive.index";
import googleSites from "./google-sites/google-sites.index";
import greenhouse from "./greenhouse/greenhouse.index";
import guru from "./guru/guru.index";
import harvest from "./harvest/harvest.index";
import haystack from "./haystack/haystack.index";
import highspot from "./highspot/highspot.index";
import hubspot from "./hubspot/hubspot.index";
import insided from "./insided/insided.index";
import interact from "./interact/interact.index";
import intercom from "./intercom/intercom.index";
import jira from "./jira/jira.index";
import linear from "./linear/linear.index";
import marketo from "./marketo/marketo.index";
import microsoftCalendar from "./microsoft-calendar/microsoft-calendar.index";
import miro from "./miro/miro.index";
import monday from "./monday/monday.index";
import notion from "./notion/notion.index";
import onenote from "./onenote/onenote.index";
import opsgenie from "./opsgenie/opsgenie.index";
import outlook from "./outlook/outlook.index";
import pagerduty from "./pagerduty/pagerduty.index";
import pipedrive from "./pipedrive/pipedrive.index";
import s3 from "./s3/s3.index";
import salesforce from "./salesforce/salesforce.index";
import samsara from "./samsara/samsara.index";
import servicenow from "./servicenow/servicenow.index";
import sharepoint from "./sharepoint/sharepoint.index";
import slack from "./slack/slack.index";
import smartthings from "./smartthings/smartthings.index";
import teams from "./teams/teams.index";
import verkada from "./verkada/verkada.index";
import workday from "./workday/workday.index";
import zendesk from "./zendesk/zendesk.index";
import zoom from "./zoom/zoom.index";

const integrations = new OpenAPIHono<AuthEnv>();

integrations.route("/gmail", gmail);
integrations.route("/github", github);
integrations.route("/gitlab", gitlab);
integrations.route("/google-drive", googleDrive);
integrations.route("/linear", linear);
integrations.route("/notion", notion);
integrations.route("/samsara", samsara);
integrations.route("/slack", slack);
integrations.route("/verkada", verkada);
integrations.route("/aws-iot", awsIot);
integrations.route("/azure-iot", azureIot);
integrations.route("/smartthings", smartthings);
integrations.route("/onenote", onenote);
integrations.route("/outlook", outlook);
integrations.route("/sharepoint", sharepoint);
integrations.route("/teams", teams);
integrations.route("/confluence", confluence);
integrations.route("/box", box);
integrations.route("/dropbox", dropbox);
integrations.route("/egnyte", egnyte);
integrations.route("/bynder", bynder);
integrations.route("/jira", jira);
integrations.route("/salesforce", salesforce);
integrations.route("/google-sites", googleSites);
integrations.route("/google-calendar", googleCalendar);
integrations.route("/google-chat", googleChat);
integrations.route("/microsoft-calendar", microsoftCalendar);
integrations.route("/servicenow", servicenow);
integrations.route("/zendesk", zendesk);
integrations.route("/asana", asana);
integrations.route("/hubspot", hubspot);
integrations.route("/intercom", intercom);
integrations.route("/figma", figma);
integrations.route("/zoom", zoom);
integrations.route("/bitbucket", bitbucket);
integrations.route("/monday", monday);
integrations.route("/pagerduty", pagerduty);
integrations.route("/pipedrive", pipedrive);
integrations.route("/clickup", clickup);
integrations.route("/coda", coda);
integrations.route("/azure-devops", azureDevOps);
integrations.route("/s3", s3);
integrations.route("/freshservice", freshservice);
integrations.route("/gong", gong);
integrations.route("/bamboohr", bamboohr);
integrations.route("/workday", workday);
integrations.route("/greenhouse", greenhouse);
integrations.route("/guru", guru);
integrations.route("/highspot", highspot);
integrations.route("/airtable", airtable);
integrations.route("/miro", miro);
integrations.route("/dynamics365", dynamics365);
integrations.route("/opsgenie", opsgenie);
integrations.route("/datadog", datadog);
integrations.route("/docusign", docusign);
integrations.route("/marketo", marketo);
integrations.route("/canva", canva);
integrations.route("/amplitude", amplitude);
integrations.route("/aha", aha);
integrations.route("/evernote", evernote);
integrations.route("/fellow", fellow);
integrations.route("/harvest", harvest);
integrations.route("/haystack", haystack);
integrations.route("/fifteen-five", fifteenFive);
integrations.route("/benchling", benchling);
integrations.route("/coupa", coupa);
integrations.route("/docebo", docebo);
integrations.route("/insided", insided);
integrations.route("/interact", interact);

integrations.get("/health", (c) =>
  c.json({
    status: "healthy",
    timestamp: new Date().toISOString(),
  })
);

export default integrations;
