{{- if or .Values.gateway.token .Values.gateway.daytona.apiKey .Values.gateway.daytona.jwtToken .Values.gateway.daytona.organizationId .Values.gateway.redis.url -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sandbox-gateway.fullname" . }}
  labels:
    {{- include "sandbox-gateway.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.gateway.token }}
  SANDBOX_API_TOKEN: {{ .Values.gateway.token | quote }}
  {{- end }}
  {{- if .Values.gateway.redis.url }}
  SANDBOX_REDIS_URL: {{ .Values.gateway.redis.url | quote }}
  {{- end }}
  {{- if .Values.gateway.daytona.apiKey }}
  DAYTONA_API_KEY: {{ .Values.gateway.daytona.apiKey | quote }}
  {{- end }}
  {{- if .Values.gateway.daytona.jwtToken }}
  DAYTONA_JWT_TOKEN: {{ .Values.gateway.daytona.jwtToken | quote }}
  {{- end }}
  {{- if .Values.gateway.daytona.organizationId }}
  DAYTONA_ORGANIZATION_ID: {{ .Values.gateway.daytona.organizationId | quote }}
  {{- end }}
{{- end }}
