import {
  AppType,
  AuthType,
  ConnectorType,
  SyncMode,
  type UnifiedApp,
} from "../types";

export const netsuiteApp: UnifiedApp = {
  id: AppType.NETSUITE,
  name: "NetSuite",
  category: "ERP & Financial Management",
  active: true,
  logo: AppType.NETSUITE,
  short_description:
    "Search customers, vendors, invoices, sales orders, purchase orders, and employees.",
  description:
    "Connect Oracle NetSuite to search across ERP data including customers, vendors, invoices, sales orders, purchase orders, and employees. Uses OAuth 1.0 Token-Based Authentication with offset-based pagination.",
  images: [],
  installed: false,
  type: "official",
  connectorType: ConnectorType.SOURCE,
  developerName: "Oracle",
  website: "https://www.netsuite.com",

  searchDisplay: {
    defaultIconKey: "Briefcase",
    documentTypes: {
      customer: {
        label: "customer",
        iconKey: "Users",
        category: "contact",
      },
      vendor: {
        label: "vendor",
        iconKey: "Building",
        category: "contact",
      },
      invoice: {
        label: "invoice",
        iconKey: "Receipt",
        category: "document",
      },
      sales_order: {
        label: "sales order",
        iconKey: "ShoppingCart",
        category: "document",
      },
      purchase_order: {
        label: "purchase order",
        iconKey: "ClipboardList",
        category: "document",
      },
      employee: {
        label: "employee",
        iconKey: "UserCircle",
        category: "contact",
      },
    },
  },

  features: [
    "Customer directory with contact, email, and balance data",
    "Vendor listing with payment terms and contact details",
    "Invoice search with status, amount, and due date filtering",
    "Sales order indexing with item lines and fulfillment status",
    "Purchase order discovery with vendor and approval tracking",
    "Employee directory with department and role information",
    "OAuth 1.0 Token-Based Authentication (TBA)",
    "Incremental sync via lastModifiedDate filters",
  ],

  auth: {
    type: AuthType.API_KEY,
    config: {
      headerName: "Authorization",
      documentationUrl:
        "https://docs.oracle.com/en/cloud/saas/netsuite/ns-online-help/section_157771281570.html",
    },
  },

  streams: [
    {
      name: "customers",
      label: "Customers",
      description: "Customer records with contact and financial data",
      entityType: "resource",
      dataPoints: [
        "Company Name",
        "Email",
        "Phone",
        "Status",
        "Balance",
        "Currency",
        "Subsidiary",
      ],
      isPii: true,
      syncMode: SyncMode.PERIODIC,
      defaultInterval: 30,
      supportsBackfill: true,
    },
    {
      name: "vendors",
      label: "Vendors",
      description: "Vendor records with payment terms and contact info",
      entityType: "resource",
      dataPoints: [
        "Company Name",
        "Email",
        "Phone",
        "Status",
        "Payment Terms",
        "Currency",
        "Balance",
      ],
      isPii: true,
      syncMode: SyncMode.PERIODIC,
      defaultInterval: 30,
      supportsBackfill: true,
    },
    {
      name: "invoices",
      label: "Invoices",
      description: "Invoices with line items and payment status",
      entityType: "resource",
      dataPoints: [
        "Invoice Number",
        "Status",
        "Total",
        "Currency",
        "Customer",
        "Due Date",
        "Balance",
      ],
      isPii: false,
      syncMode: SyncMode.PERIODIC,
      defaultInterval: 30,
      supportsBackfill: true,
    },
    {
      name: "sales_orders",
      label: "Sales Orders",
      description: "Sales orders with line items and fulfillment status",
      entityType: "resource",
      dataPoints: [
        "Order Number",
        "Status",
        "Total",
        "Currency",
        "Customer",
        "Ship Date",
        "Memo",
      ],
      isPii: false,
      syncMode: SyncMode.PERIODIC,
      defaultInterval: 30,
      supportsBackfill: true,
    },
    {
      name: "purchase_orders",
      label: "Purchase Orders",
      description: "Purchase orders with vendor and approval tracking",
      entityType: "resource",
      dataPoints: [
        "PO Number",
        "Status",
        "Total",
        "Currency",
        "Vendor",
        "Expected Receipt Date",
        "Memo",
      ],
      isPii: false,
      syncMode: SyncMode.PERIODIC,
      defaultInterval: 30,
      supportsBackfill: true,
    },
    {
      name: "employees",
      label: "Employees",
      description: "Employee records with department and role info",
      entityType: "resource",
      dataPoints: [
        "Name",
        "Email",
        "Title",
        "Department",
        "Subsidiary",
        "Supervisor",
        "Status",
      ],
      isPii: true,
      syncMode: SyncMode.PERIODIC,
      defaultInterval: 60,
      supportsBackfill: true,
    },
  ],

  settings: [
    {
      id: "account_id",
      label: "Account ID",
      description:
        "Your NetSuite account ID (e.g., 1234567 or TSTDRV1234567). Found under Setup > Company > Company Information.",
      type: "text",
      required: true,
      value: "",
      placeholder: "1234567",
    },
    {
      id: "consumer_key",
      label: "Consumer Key",
      description:
        "OAuth 1.0 consumer key from Setup > Integration > Manage Integrations.",
      type: "text",
      required: true,
      value: "",
      placeholder: "your-consumer-key",
    },
    {
      id: "consumer_secret",
      label: "Consumer Secret",
      description: "OAuth 1.0 consumer secret from the integration record.",
      type: "password",
      required: true,
      value: "",
    },
    {
      id: "token_key",
      label: "Token ID",
      description: "Access token ID from Setup > Users/Roles > Access Tokens.",
      type: "text",
      required: true,
      value: "",
      placeholder: "your-token-id",
    },
    {
      id: "token_secret",
      label: "Token Secret",
      description: "Access token secret generated with the token ID.",
      type: "password",
      required: true,
      value: "",
    },
    {
      id: "sync_customers",
      label: "Sync Customers",
      description: "Index customer records.",
      type: "switch",
      required: false,
      value: true,
    },
    {
      id: "sync_vendors",
      label: "Sync Vendors",
      description: "Index vendor records.",
      type: "switch",
      required: false,
      value: true,
    },
    {
      id: "sync_invoices",
      label: "Sync Invoices",
      description: "Index invoices.",
      type: "switch",
      required: false,
      value: true,
    },
    {
      id: "sync_sales_orders",
      label: "Sync Sales Orders",
      description: "Index sales orders.",
      type: "switch",
      required: false,
      value: true,
    },
    {
      id: "sync_purchase_orders",
      label: "Sync Purchase Orders",
      description: "Index purchase orders.",
      type: "switch",
      required: false,
      value: true,
    },
    {
      id: "sync_employees",
      label: "Sync Employees",
      description: "Index employee directory.",
      type: "switch",
      required: false,
      value: true,
    },
  ],
};

export default netsuiteApp;
