apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal
  namespace: openbeam
  labels:
    app: temporal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporal
  template:
    metadata:
      labels:
        app: temporal
    spec:
      containers:
        - name: temporal
          image: temporalio/auto-setup:1.29.2
          ports:
            - containerPort: 7233
          env:
            - name: DB
              value: "postgres12"
            - name: DB_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PWD
              value: "postgres"
            - name: POSTGRES_SEEDS
              value: "postgres"
            - name: SKIP_DYNAMIC_CONFIG_UPDATE
              value: "true"
            - name: BIND_ON_IP
              value: "0.0.0.0"
          readinessProbe:
            tcpSocket:
              port: 7233
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 1Gi
