import type { ConnectorActionsRegistry } from "@openbeam/types/connector-actions";

export const ahaActionsRegistry: ConnectorActionsRegistry = {
  connectorType: "aha",
  connectorName: "Aha!",
  connectorIcon: "aha",
  actions: [
    {
      id: "feature_create",
      name: "Create Feature",
      description: "Create a new feature in an Aha! product",
      connectorType: "aha",
      resource: "feature",
      category: "create",
      stakes: "medium",
      reversible: false,
      batchSupport: false,
      idempotent: false,
      inputs: [
        {
          id: "productId",
          name: "Product ID",
          type: "string",
          required: true,
          description: "Aha! product ID",
        },
        {
          id: "name",
          name: "Name",
          type: "string",
          required: true,
          description: "Feature name",
        },
        {
          id: "description",
          name: "Description",
          type: "string",
          required: false,
          description: "Feature description",
        },
        {
          id: "workflow_status",
          name: "Workflow Status",
          type: "string",
          required: false,
          description: "Initial workflow status",
        },
        {
          id: "assigned_to_user",
          name: "Assigned To",
          type: "string",
          required: false,
          description: "User email to assign",
        },
        {
          id: "release",
          name: "Release",
          type: "string",
          required: false,
          description: "Release to associate with",
        },
        {
          id: "due_date",
          name: "Due Date",
          type: "date",
          required: false,
          description: "Due date (YYYY-MM-DD)",
        },
        {
          id: "tags",
          name: "Tags",
          type: "array",
          required: false,
          description: "Array of tag strings",
        },
      ],
      outputs: [
        { id: "id", name: "Feature ID", type: "string" },
        { id: "url", name: "Feature URL", type: "string" },
      ],
    },
    {
      id: "idea_create",
      name: "Create Idea",
      description: "Create a new idea in an Aha! product",
      connectorType: "aha",
      resource: "idea",
      category: "create",
      stakes: "low",
      reversible: false,
      batchSupport: false,
      idempotent: false,
      inputs: [
        {
          id: "productId",
          name: "Product ID",
          type: "string",
          required: true,
          description: "Aha! product ID",
        },
        {
          id: "name",
          name: "Name",
          type: "string",
          required: true,
          description: "Idea name",
        },
        {
          id: "description",
          name: "Description",
          type: "string",
          required: false,
          description: "Idea description",
        },
        {
          id: "workflow_status",
          name: "Workflow Status",
          type: "string",
          required: false,
        },
        {
          id: "assigned_to_user",
          name: "Assigned To",
          type: "string",
          required: false,
        },
        { id: "tags", name: "Tags", type: "array", required: false },
      ],
      outputs: [
        { id: "id", name: "Idea ID", type: "string" },
        { id: "url", name: "Idea URL", type: "string" },
      ],
    },
    {
      id: "idea_update",
      name: "Update Idea",
      description: "Update an existing idea in Aha!",
      connectorType: "aha",
      resource: "idea",
      category: "update",
      stakes: "low",
      reversible: true,
      batchSupport: false,
      idempotent: true,
      inputs: [
        {
          id: "ideaId",
          name: "Idea ID",
          type: "string",
          required: true,
          description: "ID of the idea to update",
        },
        { id: "name", name: "Name", type: "string", required: false },
        {
          id: "description",
          name: "Description",
          type: "string",
          required: false,
        },
        {
          id: "workflow_status",
          name: "Workflow Status",
          type: "string",
          required: false,
        },
        {
          id: "assigned_to_user",
          name: "Assigned To",
          type: "string",
          required: false,
        },
      ],
      outputs: [
        { id: "id", name: "Idea ID", type: "string" },
        { id: "url", name: "Idea URL", type: "string" },
      ],
    },
  ],
};
