import type { ConnectorActionsRegistry } from "@openbeam/types/canvas";

export const airtableActionsRegistry: ConnectorActionsRegistry = {
  connectorType: "airtable",
  connectorName: "Airtable",
  connectorIcon: "airtable",
  actions: [
    {
      id: "record_create",
      name: "Create Record",
      description: "Create a new record in an Airtable table",
      connectorType: "airtable",
      resource: "record",
      category: "create",
      stakes: "medium",
      reversible: false,
      batchSupport: false,
      inputs: [
        {
          id: "base_id",
          name: "Base ID",
          type: "string",
          required: true,
          description: "Airtable base ID (e.g. appXXXXXXXXXX)",
        },
        {
          id: "table_id",
          name: "Table ID or Name",
          type: "string",
          required: true,
          description: "Table ID or name within the base",
        },
        {
          id: "fields",
          name: "Fields",
          type: "json",
          required: true,
          description: "JSON object of field name to value pairs",
        },
      ],
      outputs: [
        { id: "recordId", name: "Record ID", type: "string" },
        { id: "url", name: "Record URL", type: "string" },
      ],
    },
    {
      id: "record_update",
      name: "Update Record",
      description: "Update an existing record in an Airtable table",
      connectorType: "airtable",
      resource: "record",
      category: "update",
      stakes: "low",
      reversible: true,
      batchSupport: false,
      inputs: [
        {
          id: "base_id",
          name: "Base ID",
          type: "string",
          required: true,
          description: "Airtable base ID (e.g. appXXXXXXXXXX)",
        },
        {
          id: "table_id",
          name: "Table ID or Name",
          type: "string",
          required: true,
          description: "Table ID or name within the base",
        },
        {
          id: "record_id",
          name: "Record ID",
          type: "string",
          required: true,
          description: "ID of the record to update",
        },
        {
          id: "fields",
          name: "Fields",
          type: "json",
          required: true,
          description: "JSON object of field name to value pairs to update",
        },
      ],
      outputs: [
        { id: "recordId", name: "Record ID", type: "string" },
        { id: "url", name: "Record URL", type: "string" },
      ],
    },
    {
      id: "record_delete",
      name: "Delete Record",
      description: "Delete a record from an Airtable table",
      connectorType: "airtable",
      resource: "record",
      category: "delete",
      stakes: "high",
      reversible: false,
      batchSupport: false,
      inputs: [
        {
          id: "base_id",
          name: "Base ID",
          type: "string",
          required: true,
          description: "Airtable base ID (e.g. appXXXXXXXXXX)",
        },
        {
          id: "table_id",
          name: "Table ID or Name",
          type: "string",
          required: true,
          description: "Table ID or name within the base",
        },
        {
          id: "record_id",
          name: "Record ID",
          type: "string",
          required: true,
          description: "ID of the record to delete",
        },
      ],
      outputs: [{ id: "recordId", name: "Record ID", type: "string" }],
    },
  ],
};
