import type { ConnectorActionsRegistry } from "@openbeam/types/canvas";

export const asanaActionsRegistry: ConnectorActionsRegistry = {
  connectorType: "asana",
  connectorName: "Asana",
  connectorIcon: "asana",
  actions: [
    {
      id: "workspace_list",
      name: "List Workspaces",
      description:
        "List all Asana workspaces accessible to the connected account. Use this first to discover workspace GIDs before calling project_list or task_create.",
      connectorType: "asana",
      resource: "workspace",
      category: "list",
      stakes: "low",
      reversible: true,
      batchSupport: false,
      inputs: [],
      outputs: [
        {
          id: "workspaces",
          name: "Workspaces",
          type: "object",
          description: "Array of workspaces with gid and name",
        },
      ],
    },
    {
      id: "project_list",
      name: "List Projects",
      description:
        "List all projects in an Asana workspace. Use workspace_list first to get the workspace_gid, then use this to discover project GIDs before calling task_create.",
      connectorType: "asana",
      resource: "project",
      category: "list",
      stakes: "low",
      reversible: true,
      batchSupport: false,
      inputs: [
        {
          id: "workspace_gid",
          name: "Workspace GID",
          type: "string",
          required: true,
          description: "Asana workspace GID — get from workspace_list",
        },
      ],
      outputs: [
        {
          id: "projects",
          name: "Projects",
          type: "object",
          description: "Array of projects with gid, name, and archived status",
        },
      ],
    },
    {
      id: "task_create",
      name: "Create Task",
      description:
        "Create a new Asana task. Requires workspace_gid — call workspace_list first. Optionally call project_list to get a project_gid.",
      connectorType: "asana",
      resource: "task",
      category: "create",
      stakes: "medium",
      reversible: false,
      batchSupport: false,
      inputs: [
        {
          id: "workspace_gid",
          name: "Workspace GID",
          type: "string",
          required: true,
          description: "Asana workspace GID — get from workspace_list",
        },
        {
          id: "name",
          name: "Task Name",
          type: "string",
          required: true,
          description: "Name of the task",
        },
        {
          id: "notes",
          name: "Notes",
          type: "string",
          required: false,
          description: "Task description",
        },
        {
          id: "project_gid",
          name: "Project GID",
          type: "string",
          required: false,
          description: "Project to add the task to — get from project_list",
        },
        {
          id: "assignee_gid",
          name: "Assignee GID",
          type: "string",
          required: false,
          description: "Asana user GID to assign",
        },
        {
          id: "due_on",
          name: "Due Date",
          type: "string",
          required: false,
          description: "Due date (YYYY-MM-DD)",
        },
      ],
      outputs: [
        { id: "taskGid", name: "Task GID", type: "string" },
        { id: "url", name: "Task URL", type: "string" },
      ],
    },
    {
      id: "task_update",
      name: "Update Task",
      description: "Update fields on an existing Asana task",
      connectorType: "asana",
      resource: "task",
      category: "update",
      stakes: "low",
      reversible: true,
      batchSupport: false,
      inputs: [
        {
          id: "task_gid",
          name: "Task GID",
          type: "string",
          required: true,
          description: "GID of the task to update",
        },
        {
          id: "name",
          name: "Task Name",
          type: "string",
          required: false,
        },
        {
          id: "notes",
          name: "Notes",
          type: "string",
          required: false,
        },
        {
          id: "assignee_gid",
          name: "Assignee GID",
          type: "string",
          required: false,
        },
        {
          id: "due_on",
          name: "Due Date",
          type: "string",
          required: false,
        },
      ],
      outputs: [{ id: "taskGid", name: "Task GID", type: "string" }],
    },
    {
      id: "task_complete",
      name: "Complete Task",
      description: "Mark an Asana task as complete",
      connectorType: "asana",
      resource: "task",
      category: "update",
      stakes: "medium",
      reversible: true,
      batchSupport: false,
      inputs: [
        {
          id: "task_gid",
          name: "Task GID",
          type: "string",
          required: true,
          description: "GID of the task to complete",
        },
      ],
      outputs: [{ id: "taskGid", name: "Task GID", type: "string" }],
    },
    {
      id: "comment_add",
      name: "Add Comment",
      description: "Add a comment to an Asana task",
      connectorType: "asana",
      resource: "comment",
      category: "create",
      stakes: "low",
      reversible: false,
      batchSupport: false,
      inputs: [
        {
          id: "task_gid",
          name: "Task GID",
          type: "string",
          required: true,
          description: "GID of the task to comment on",
        },
        {
          id: "text",
          name: "Comment Text",
          type: "string",
          required: true,
          description: "Comment body",
        },
      ],
      outputs: [{ id: "storyGid", name: "Story GID", type: "string" }],
    },
  ],
};
