import type { ConnectorActionsRegistry } from "@openbeam/types/canvas";

export const asanaActionsRegistry: ConnectorActionsRegistry = {
  connectorType: "asana",
  connectorName: "Asana",
  connectorIcon: "asana",
  actions: [
    {
      id: "task_create",
      name: "Create Task",
      description: "Create a new Asana task",
      connectorType: "asana",
      resource: "task",
      category: "create",
      stakes: "medium",
      reversible: false,
      batchSupport: false,
      inputs: [
        {
          id: "name",
          name: "Task Name",
          type: "string",
          required: true,
          description: "Name of the task",
        },
        {
          id: "notes",
          name: "Notes",
          type: "string",
          required: false,
          description: "Task description",
        },
        {
          id: "project_gid",
          name: "Project GID",
          type: "string",
          required: false,
          description: "Project to add the task to",
        },
        {
          id: "assignee_gid",
          name: "Assignee GID",
          type: "string",
          required: false,
          description: "Asana user GID to assign",
        },
        {
          id: "due_on",
          name: "Due Date",
          type: "string",
          required: false,
          description: "Due date (YYYY-MM-DD)",
        },
      ],
      outputs: [
        { id: "taskGid", name: "Task GID", type: "string" },
        { id: "url", name: "Task URL", type: "string" },
      ],
    },
    {
      id: "task_update",
      name: "Update Task",
      description: "Update fields on an existing Asana task",
      connectorType: "asana",
      resource: "task",
      category: "update",
      stakes: "low",
      reversible: true,
      batchSupport: false,
      inputs: [
        {
          id: "task_gid",
          name: "Task GID",
          type: "string",
          required: true,
          description: "GID of the task to update",
        },
        {
          id: "name",
          name: "Task Name",
          type: "string",
          required: false,
        },
        {
          id: "notes",
          name: "Notes",
          type: "string",
          required: false,
        },
        {
          id: "assignee_gid",
          name: "Assignee GID",
          type: "string",
          required: false,
        },
        {
          id: "due_on",
          name: "Due Date",
          type: "string",
          required: false,
        },
      ],
      outputs: [{ id: "taskGid", name: "Task GID", type: "string" }],
    },
    {
      id: "task_complete",
      name: "Complete Task",
      description: "Mark an Asana task as complete",
      connectorType: "asana",
      resource: "task",
      category: "update",
      stakes: "medium",
      reversible: true,
      batchSupport: false,
      inputs: [
        {
          id: "task_gid",
          name: "Task GID",
          type: "string",
          required: true,
          description: "GID of the task to complete",
        },
      ],
      outputs: [{ id: "taskGid", name: "Task GID", type: "string" }],
    },
    {
      id: "comment_add",
      name: "Add Comment",
      description: "Add a comment to an Asana task",
      connectorType: "asana",
      resource: "comment",
      category: "create",
      stakes: "low",
      reversible: false,
      batchSupport: false,
      inputs: [
        {
          id: "task_gid",
          name: "Task GID",
          type: "string",
          required: true,
          description: "GID of the task to comment on",
        },
        {
          id: "text",
          name: "Comment Text",
          type: "string",
          required: true,
          description: "Comment body",
        },
      ],
      outputs: [{ id: "storyGid", name: "Story GID", type: "string" }],
    },
  ],
};
