import type { ConnectorActionsRegistry } from "@openbeam/types/connector-actions";

export const azureDevOpsActionsRegistry: ConnectorActionsRegistry = {
  connectorType: "azure-devops",
  connectorName: "Azure DevOps",
  connectorIcon: "azure-devops",
  actions: [
    {
      id: "project_list",
      name: "List Projects",
      description:
        "List Azure DevOps projects in the organization. Returns id, name, state, description, and url. Call this FIRST before work_item_create or work_item_update to discover the exact project NAME (not ID — Azure DevOps work-item APIs use the project name in the URL path). Do NOT guess project names.",
      connectorType: "azure_devops",
      resource: "project",
      category: "list",
      stakes: "low",
      reversible: true,
      batchSupport: false,
      idempotent: true,
      inputs: [
        {
          id: "limit",
          name: "Limit",
          type: "number",
          required: false,
          description: "Max projects to return (1-500, default 100).",
        },
      ],
      outputs: [
        {
          id: "projects",
          name: "Projects",
          type: "array",
          description:
            "Array of { id, name, state, description, url }. Use 'name' as the project input to work_item_create / work_item_update.",
        },
      ],
    },
    {
      id: "work_item_create",
      name: "Create Work Item",
      description: "Create a new work item in an Azure DevOps project",
      connectorType: "azure-devops",
      resource: "work_item",
      category: "create",
      stakes: "medium",
      reversible: false,
      batchSupport: false,
      idempotent: false,
      inputs: [
        {
          id: "project",
          name: "Project",
          type: "string",
          required: true,
          description: "Azure DevOps project name",
        },
        {
          id: "work_item_type",
          name: "Work Item Type",
          type: "string",
          required: true,
          description: "Bug, Task, User Story, Feature, Epic",
          default: "Task",
        },
        {
          id: "title",
          name: "Title",
          type: "string",
          required: true,
          description: "Work item title",
        },
        {
          id: "description",
          name: "Description",
          type: "string",
          required: false,
          description: "Work item description (HTML supported)",
        },
        {
          id: "assigned_to",
          name: "Assigned To",
          type: "string",
          required: false,
          description: "Email or display name of the assignee",
        },
        {
          id: "priority",
          name: "Priority",
          type: "number",
          required: false,
          description: "1 (Critical), 2 (High), 3 (Medium), 4 (Low)",
        },
        {
          id: "tags",
          name: "Tags",
          type: "string",
          required: false,
          description: "Semicolon-separated tags",
        },
      ],
      outputs: [
        { id: "workItemId", name: "Work Item ID", type: "string" },
        { id: "url", name: "Work Item URL", type: "string" },
      ],
    },
    {
      id: "work_item_update",
      name: "Update Work Item",
      description: "Update fields on an existing Azure DevOps work item",
      connectorType: "azure-devops",
      resource: "work_item",
      category: "update",
      stakes: "low",
      reversible: true,
      batchSupport: false,
      idempotent: true,
      inputs: [
        {
          id: "project",
          name: "Project",
          type: "string",
          required: true,
          description: "Azure DevOps project name",
        },
        {
          id: "work_item_id",
          name: "Work Item ID",
          type: "number",
          required: true,
          description: "Numeric work item ID",
        },
        {
          id: "title",
          name: "Title",
          type: "string",
          required: false,
        },
        {
          id: "description",
          name: "Description",
          type: "string",
          required: false,
        },
        {
          id: "state",
          name: "State",
          type: "string",
          required: false,
          description: "New, Active, Resolved, Closed",
        },
        {
          id: "assigned_to",
          name: "Assigned To",
          type: "string",
          required: false,
        },
        {
          id: "priority",
          name: "Priority",
          type: "number",
          required: false,
        },
        {
          id: "tags",
          name: "Tags",
          type: "string",
          required: false,
        },
      ],
      outputs: [
        { id: "workItemId", name: "Work Item ID", type: "string" },
        { id: "url", name: "Work Item URL", type: "string" },
      ],
    },
    {
      id: "work_item_comment",
      name: "Add Comment",
      description: "Add a comment to an Azure DevOps work item",
      connectorType: "azure-devops",
      resource: "comment",
      category: "create",
      stakes: "low",
      reversible: false,
      batchSupport: false,
      idempotent: false,
      inputs: [
        {
          id: "project",
          name: "Project",
          type: "string",
          required: true,
        },
        {
          id: "work_item_id",
          name: "Work Item ID",
          type: "number",
          required: true,
        },
        {
          id: "text",
          name: "Comment Text",
          type: "string",
          required: true,
          description: "Comment body text",
        },
      ],
      outputs: [{ id: "commentId", name: "Comment ID", type: "string" }],
    },
  ],
};
