import type { ConnectorActionsRegistry } from "@openbeam/types/connector-actions";

export const bitbucketActionsRegistry: ConnectorActionsRegistry = {
  connectorType: "bitbucket",
  connectorName: "Bitbucket",
  connectorIcon: "bitbucket",
  actions: [
    {
      id: "pull_request_create",
      name: "Create Pull Request",
      description: "Create a pull request between branches",
      connectorType: "bitbucket",
      resource: "pull_request",
      category: "create",
      stakes: "high",
      reversible: true,
      batchSupport: false,
      inputs: [
        {
          id: "repoSlug",
          name: "Repository",
          type: "string",
          required: true,
          description: "Repository slug",
        },
        {
          id: "title",
          name: "Title",
          type: "string",
          required: true,
          description: "Pull request title",
        },
        {
          id: "sourceBranch",
          name: "Source Branch",
          type: "string",
          required: true,
          description: "Source branch name",
        },
        {
          id: "destinationBranch",
          name: "Destination Branch",
          type: "string",
          required: true,
          description: "Target branch name",
        },
        {
          id: "description",
          name: "Description",
          type: "string",
          required: false,
          description: "Pull request description",
        },
      ],
      outputs: [
        {
          id: "id",
          name: "PR ID",
          type: "number",
          description: "Created pull request ID",
        },
        {
          id: "url",
          name: "URL",
          type: "string",
          description: "Pull request URL",
        },
      ],
    },
    {
      id: "pull_request_comment",
      name: "Add PR Comment",
      description: "Add a comment to a pull request",
      connectorType: "bitbucket",
      resource: "pull_request",
      category: "create",
      stakes: "low",
      reversible: false,
      batchSupport: false,
      inputs: [
        {
          id: "repoSlug",
          name: "Repository",
          type: "string",
          required: true,
          description: "Repository slug",
        },
        {
          id: "prId",
          name: "PR ID",
          type: "number",
          required: true,
          description: "Pull request ID",
        },
        {
          id: "body",
          name: "Comment",
          type: "string",
          required: true,
          description: "Comment content",
        },
      ],
      outputs: [
        {
          id: "id",
          name: "Comment ID",
          type: "number",
          description: "Created comment ID",
        },
      ],
    },
    {
      id: "issue_create",
      name: "Create Issue",
      description: "Create an issue in a repository",
      connectorType: "bitbucket",
      resource: "issue",
      category: "create",
      stakes: "medium",
      reversible: true,
      batchSupport: false,
      inputs: [
        {
          id: "repoSlug",
          name: "Repository",
          type: "string",
          required: true,
          description: "Repository slug",
        },
        {
          id: "title",
          name: "Title",
          type: "string",
          required: true,
          description: "Issue title",
        },
        {
          id: "content",
          name: "Content",
          type: "string",
          required: false,
          description: "Issue description",
        },
        {
          id: "priority",
          name: "Priority",
          type: "string",
          required: false,
          description:
            "Issue priority (trivial, minor, major, critical, blocker)",
        },
      ],
      outputs: [
        {
          id: "id",
          name: "Issue ID",
          type: "number",
          description: "Created issue ID",
        },
        {
          id: "url",
          name: "URL",
          type: "string",
          description: "Issue URL",
        },
      ],
    },
    {
      id: "issue_comment",
      name: "Add Issue Comment",
      description: "Add a comment to an issue",
      connectorType: "bitbucket",
      resource: "issue",
      category: "create",
      stakes: "low",
      reversible: false,
      batchSupport: false,
      inputs: [
        {
          id: "repoSlug",
          name: "Repository",
          type: "string",
          required: true,
          description: "Repository slug",
        },
        {
          id: "issueId",
          name: "Issue ID",
          type: "number",
          required: true,
          description: "Issue ID",
        },
        {
          id: "body",
          name: "Comment",
          type: "string",
          required: true,
          description: "Comment content",
        },
      ],
      outputs: [
        {
          id: "id",
          name: "Comment ID",
          type: "number",
          description: "Created comment ID",
        },
      ],
    },
  ],
};
