import type { ConnectorActionsRegistry } from "@openbeam/types/canvas";

export const boxActionsRegistry: ConnectorActionsRegistry = {
  connectorType: "box",
  connectorName: "Box",
  connectorIcon: "box",
  actions: [
    {
      id: "folder_create",
      name: "Create Folder",
      description: "Create a new folder in Box",
      connectorType: "box",
      resource: "folder",
      category: "create",
      stakes: "low",
      reversible: true,
      batchSupport: false,
      inputs: [
        {
          id: "name",
          name: "Folder Name",
          type: "string",
          required: true,
          description: "Name for the new folder",
        },
        {
          id: "parent_id",
          name: "Parent Folder ID",
          type: "string",
          required: true,
          description: "ID of the parent folder (0 for root)",
        },
      ],
      outputs: [
        { id: "id", name: "Folder ID", type: "string" },
        { id: "url", name: "Folder URL", type: "string" },
      ],
    },
    {
      id: "item_move",
      name: "Move Item",
      description: "Move a file or folder to a new parent folder",
      connectorType: "box",
      resource: "file",
      category: "update",
      stakes: "medium",
      reversible: true,
      batchSupport: false,
      inputs: [
        {
          id: "item_type",
          name: "Item Type",
          type: "string",
          required: true,
          description: "Type of item: file or folder",
        },
        {
          id: "item_id",
          name: "Item ID",
          type: "string",
          required: true,
          description: "ID of the file or folder to move",
        },
        {
          id: "new_parent_id",
          name: "Destination Folder ID",
          type: "string",
          required: true,
          description: "ID of the destination folder",
        },
      ],
      outputs: [
        { id: "id", name: "Item ID", type: "string" },
        { id: "url", name: "URL", type: "string" },
      ],
    },
    {
      id: "item_delete",
      name: "Delete Item",
      description: "Delete a file or folder from Box",
      connectorType: "box",
      resource: "file",
      category: "delete",
      stakes: "high",
      reversible: false,
      batchSupport: false,
      inputs: [
        {
          id: "item_type",
          name: "Item Type",
          type: "string",
          required: true,
          description: "Type of item: file or folder",
        },
        {
          id: "item_id",
          name: "Item ID",
          type: "string",
          required: true,
          description: "ID of the file or folder to delete",
        },
      ],
      outputs: [{ id: "id", name: "Deleted Item ID", type: "string" }],
    },
    {
      id: "item_share",
      name: "Share Item",
      description: "Create a shared link for a file or folder",
      connectorType: "box",
      resource: "file",
      category: "update",
      stakes: "medium",
      reversible: true,
      batchSupport: false,
      inputs: [
        {
          id: "item_type",
          name: "Item Type",
          type: "string",
          required: true,
          description: "Type of item: file or folder",
        },
        {
          id: "item_id",
          name: "Item ID",
          type: "string",
          required: true,
          description: "ID of the file or folder to share",
        },
        {
          id: "access",
          name: "Access Level",
          type: "string",
          required: false,
          description: "Access level: open, company, or collaborators",
        },
      ],
      outputs: [
        { id: "id", name: "Item ID", type: "string" },
        { id: "url", name: "Shared Link URL", type: "string" },
      ],
    },
  ],
};
