import type { ConnectorActionsRegistry } from "@openbeam/types/connector-actions";

export const boxActionsRegistry: ConnectorActionsRegistry = {
  connectorType: "box",
  connectorName: "Box",
  connectorIcon: "box",
  actions: [
    {
      id: "folder_list",
      name: "List Folder Items",
      description:
        "List files and folders inside a Box folder. Use this to discover folder IDs needed by folder_create and item_move. Pass folder_id=0 (or omit) for root.",
      connectorType: "box",
      resource: "folder",
      category: "read",
      stakes: "low",
      reversible: true,
      batchSupport: false,
      idempotent: true,
      inputs: [
        {
          id: "folder_id",
          name: "Folder ID",
          type: "string",
          required: false,
          description: "ID of the folder to list. Defaults to 0 (root).",
        },
      ],
      outputs: [{ id: "items", name: "Items", type: "array" }],
    },
    {
      id: "folder_create",
      name: "Create Folder",
      description:
        "Create a new folder in Box. Use folder_list first to discover the parent_id.",
      connectorType: "box",
      resource: "folder",
      category: "create",
      stakes: "low",
      reversible: true,
      batchSupport: false,
      idempotent: false,
      inputs: [
        {
          id: "name",
          name: "Folder Name",
          type: "string",
          required: true,
          description: "Name for the new folder",
        },
        {
          id: "parent_id",
          name: "Parent Folder ID",
          type: "string",
          required: true,
          description:
            "ID of the parent folder (0 for root). Use folder_list to discover available folders.",
        },
      ],
      outputs: [
        { id: "id", name: "Folder ID", type: "string" },
        { id: "url", name: "Folder URL", type: "string" },
      ],
    },
    {
      id: "item_move",
      name: "Move Item",
      description:
        "Move a file or folder to a new parent folder. Use folder_list first to discover the new_parent_id.",
      connectorType: "box",
      resource: "file",
      category: "update",
      stakes: "medium",
      reversible: true,
      batchSupport: false,
      idempotent: true,
      inputs: [
        {
          id: "item_type",
          name: "Item Type",
          type: "string",
          required: true,
          description: "Type of item: file or folder",
        },
        {
          id: "item_id",
          name: "Item ID",
          type: "string",
          required: true,
          description: "ID of the file or folder to move",
        },
        {
          id: "new_parent_id",
          name: "Destination Folder ID",
          type: "string",
          required: true,
          description:
            "ID of the destination folder. Use folder_list to discover available folders.",
        },
      ],
      outputs: [
        { id: "id", name: "Item ID", type: "string" },
        { id: "url", name: "URL", type: "string" },
      ],
    },
    {
      id: "item_delete",
      name: "Delete Item",
      description: "Delete a file or folder from Box",
      connectorType: "box",
      resource: "file",
      category: "delete",
      stakes: "high",
      reversible: false,
      batchSupport: false,
      idempotent: true,
      inputs: [
        {
          id: "item_type",
          name: "Item Type",
          type: "string",
          required: true,
          description: "Type of item: file or folder",
        },
        {
          id: "item_id",
          name: "Item ID",
          type: "string",
          required: true,
          description: "ID of the file or folder to delete",
        },
      ],
      outputs: [{ id: "id", name: "Deleted Item ID", type: "string" }],
    },
    {
      id: "item_share",
      name: "Share Item",
      description: "Create a shared link for a file or folder",
      connectorType: "box",
      resource: "file",
      category: "update",
      stakes: "medium",
      reversible: true,
      batchSupport: false,
      idempotent: true,
      inputs: [
        {
          id: "item_type",
          name: "Item Type",
          type: "string",
          required: true,
          description: "Type of item: file or folder",
        },
        {
          id: "item_id",
          name: "Item ID",
          type: "string",
          required: true,
          description: "ID of the file or folder to share",
        },
        {
          id: "access",
          name: "Access Level",
          type: "string",
          required: false,
          description: "Access level: open, company, or collaborators",
        },
      ],
      outputs: [
        { id: "id", name: "Item ID", type: "string" },
        { id: "url", name: "Shared Link URL", type: "string" },
      ],
    },
  ],
};
