import type { ConnectorActionsRegistry } from "@openbeam/types/canvas";

export const clickUpActionsRegistry: ConnectorActionsRegistry = {
  connectorType: "clickup",
  connectorName: "ClickUp",
  connectorIcon: "clickup",
  actions: [
    {
      id: "task_create",
      name: "Create Task",
      description: "Create a new ClickUp task",
      connectorType: "clickup",
      resource: "task",
      category: "create",
      stakes: "medium",
      reversible: true,
      batchSupport: false,
      inputs: [
        {
          id: "listId",
          name: "List ID",
          type: "string",
          required: true,
          description: "List to create task in",
        },
        {
          id: "name",
          name: "Name",
          type: "string",
          required: true,
          description: "Task name",
        },
        {
          id: "description",
          name: "Description",
          type: "string",
          required: false,
          description: "Task description",
        },
        {
          id: "priority",
          name: "Priority",
          type: "number",
          required: false,
          description: "Priority (1=Urgent, 2=High, 3=Normal, 4=Low)",
        },
        {
          id: "dueDate",
          name: "Due Date",
          type: "number",
          required: false,
          description: "Due date (unix ms timestamp)",
        },
      ],
      outputs: [
        {
          id: "id",
          name: "Task ID",
          type: "string",
          description: "Created task ID",
        },
        { id: "url", name: "URL", type: "string", description: "Task URL" },
      ],
    },
    {
      id: "task_update",
      name: "Update Task",
      description: "Update an existing ClickUp task",
      connectorType: "clickup",
      resource: "task",
      category: "update",
      stakes: "medium",
      reversible: true,
      batchSupport: false,
      inputs: [
        {
          id: "taskId",
          name: "Task ID",
          type: "string",
          required: true,
          description: "Task ID",
        },
        {
          id: "name",
          name: "Name",
          type: "string",
          required: false,
          description: "New name",
        },
        {
          id: "description",
          name: "Description",
          type: "string",
          required: false,
          description: "New description",
        },
        {
          id: "status",
          name: "Status",
          type: "string",
          required: false,
          description: "New status",
        },
        {
          id: "priority",
          name: "Priority",
          type: "number",
          required: false,
          description: "New priority",
        },
      ],
      outputs: [
        {
          id: "id",
          name: "Task ID",
          type: "string",
          description: "Updated task ID",
        },
        {
          id: "success",
          name: "Success",
          type: "boolean",
          description: "Whether update succeeded",
        },
      ],
    },
    {
      id: "task_add_comment",
      name: "Add Comment",
      description: "Add a comment to a task",
      connectorType: "clickup",
      resource: "task",
      category: "create",
      stakes: "low",
      reversible: false,
      batchSupport: false,
      inputs: [
        {
          id: "taskId",
          name: "Task ID",
          type: "string",
          required: true,
          description: "Task ID",
        },
        {
          id: "commentText",
          name: "Comment Text",
          type: "string",
          required: true,
          description: "Comment body",
        },
      ],
      outputs: [
        {
          id: "id",
          name: "Comment ID",
          type: "string",
          description: "Created comment ID",
        },
      ],
    },
  ],
};
