import type { ConnectorActionsRegistry } from "@openbeam/types/canvas";

export const codaActionsRegistry: ConnectorActionsRegistry = {
  connectorType: "coda",
  connectorName: "Coda",
  connectorIcon: "coda",
  actions: [
    {
      id: "doc_create",
      name: "Create Doc",
      description: "Create a new Coda document",
      connectorType: "coda",
      resource: "doc",
      category: "create",
      stakes: "medium",
      reversible: false,
      batchSupport: false,
      inputs: [
        {
          id: "title",
          name: "Title",
          type: "string",
          required: true,
          description: "Document title",
        },
        {
          id: "folderId",
          name: "Folder ID",
          type: "string",
          required: false,
          description: "Target folder ID",
        },
      ],
      outputs: [
        { id: "recordId", name: "Doc ID", type: "string" },
        { id: "url", name: "Doc URL", type: "string" },
      ],
    },
    {
      id: "row_create",
      name: "Create Row",
      description: "Add a new row to a Coda table",
      connectorType: "coda",
      resource: "row",
      category: "create",
      stakes: "low",
      reversible: true,
      batchSupport: false,
      inputs: [
        {
          id: "doc_id",
          name: "Doc ID",
          type: "string",
          required: true,
          description: "ID of the Coda document",
        },
        {
          id: "table_id",
          name: "Table ID",
          type: "string",
          required: true,
          description: "ID of the table to add the row to",
        },
        {
          id: "cells",
          name: "Cells",
          type: "json",
          required: true,
          description:
            'Array of {column, value} objects, e.g. [{"column":"Name","value":"Alice"}]',
        },
      ],
      outputs: [{ id: "recordId", name: "Row ID", type: "string" }],
    },
    {
      id: "row_update",
      name: "Update Row",
      description: "Update an existing row in a Coda table",
      connectorType: "coda",
      resource: "row",
      category: "update",
      stakes: "low",
      reversible: true,
      batchSupport: false,
      inputs: [
        {
          id: "doc_id",
          name: "Doc ID",
          type: "string",
          required: true,
          description: "ID of the Coda document",
        },
        {
          id: "table_id",
          name: "Table ID",
          type: "string",
          required: true,
          description: "ID of the table",
        },
        {
          id: "row_id",
          name: "Row ID",
          type: "string",
          required: true,
          description: "ID of the row to update",
        },
        {
          id: "cells",
          name: "Cells",
          type: "json",
          required: true,
          description: "Array of {column, value} objects to update",
        },
      ],
      outputs: [{ id: "recordId", name: "Row ID", type: "string" }],
    },
    {
      id: "row_delete",
      name: "Delete Row",
      description: "Delete a row from a Coda table",
      connectorType: "coda",
      resource: "row",
      category: "delete",
      stakes: "medium",
      reversible: false,
      batchSupport: false,
      inputs: [
        {
          id: "doc_id",
          name: "Doc ID",
          type: "string",
          required: true,
          description: "ID of the Coda document",
        },
        {
          id: "table_id",
          name: "Table ID",
          type: "string",
          required: true,
          description: "ID of the table",
        },
        {
          id: "row_id",
          name: "Row ID",
          type: "string",
          required: true,
          description: "ID of the row to delete",
        },
      ],
      outputs: [{ id: "recordId", name: "Row ID", type: "string" }],
    },
  ],
};
