import type { ConnectorActionsRegistry } from "@openbeam/types/connector-actions";

export const datadogActionsRegistry: ConnectorActionsRegistry = {
  connectorType: "datadog",
  connectorName: "Datadog",
  connectorIcon: "datadog",
  actions: [
    {
      id: "monitor_create",
      name: "Create Monitor",
      description: "Create a new monitor in Datadog",
      connectorType: "datadog",
      resource: "monitor",
      category: "create",
      stakes: "medium",
      reversible: true,
      batchSupport: false,
      idempotent: false,
      inputs: [
        {
          id: "name",
          name: "Name",
          type: "string",
          required: true,
          description: "Monitor name",
        },
        {
          id: "type",
          name: "Type",
          type: "string",
          required: true,
          description:
            "Monitor type: metric alert, service check, event alert, query alert, etc.",
        },
        {
          id: "query",
          name: "Query",
          type: "string",
          required: true,
          description: "Monitor query definition",
        },
        {
          id: "message",
          name: "Message",
          type: "string",
          required: false,
          description: "Notification message body with @-mentions",
        },
        {
          id: "tags",
          name: "Tags",
          type: "string",
          required: false,
          description: "Comma-separated list of tags",
        },
        {
          id: "priority",
          name: "Priority",
          type: "string",
          required: false,
          description: "Monitor priority (1-5)",
        },
      ],
      outputs: [{ id: "monitorId", name: "Monitor ID", type: "string" }],
    },
    {
      id: "monitor_update",
      name: "Update Monitor",
      description: "Update an existing monitor in Datadog",
      connectorType: "datadog",
      resource: "monitor",
      category: "update",
      stakes: "medium",
      reversible: true,
      batchSupport: false,
      idempotent: false,
      inputs: [
        {
          id: "monitor_id",
          name: "Monitor ID",
          type: "string",
          required: true,
          description: "ID of the monitor to update",
        },
        {
          id: "name",
          name: "Name",
          type: "string",
          required: false,
          description: "Updated monitor name",
        },
        {
          id: "query",
          name: "Query",
          type: "string",
          required: false,
          description: "Updated monitor query",
        },
        {
          id: "message",
          name: "Message",
          type: "string",
          required: false,
          description: "Updated notification message",
        },
        {
          id: "tags",
          name: "Tags",
          type: "string",
          required: false,
          description: "Comma-separated list of tags",
        },
      ],
      outputs: [{ id: "monitorId", name: "Monitor ID", type: "string" }],
    },
    {
      id: "monitor_mute",
      name: "Mute Monitor",
      description: "Mute a monitor to suppress notifications",
      connectorType: "datadog",
      resource: "monitor",
      category: "update",
      stakes: "low",
      reversible: true,
      batchSupport: false,
      idempotent: false,
      inputs: [
        {
          id: "monitor_id",
          name: "Monitor ID",
          type: "string",
          required: true,
          description: "ID of the monitor to mute",
        },
        {
          id: "scope",
          name: "Scope",
          type: "string",
          required: false,
          description: "Scope to mute (e.g., host:myhost)",
        },
        {
          id: "end",
          name: "End Timestamp",
          type: "string",
          required: false,
          description: "POSIX timestamp for when the mute should end",
        },
      ],
      outputs: [{ id: "monitorId", name: "Monitor ID", type: "string" }],
    },
    {
      id: "monitor_unmute",
      name: "Unmute Monitor",
      description: "Unmute a previously muted monitor",
      connectorType: "datadog",
      resource: "monitor",
      category: "update",
      stakes: "low",
      reversible: true,
      batchSupport: false,
      idempotent: false,
      inputs: [
        {
          id: "monitor_id",
          name: "Monitor ID",
          type: "string",
          required: true,
          description: "ID of the monitor to unmute",
        },
        {
          id: "scope",
          name: "Scope",
          type: "string",
          required: false,
          description: "Scope to unmute",
        },
      ],
      outputs: [{ id: "monitorId", name: "Monitor ID", type: "string" }],
    },
  ],
};
