import type { ConnectorActionsRegistry } from "@openplane/types/canvas";

export const githubActionsRegistry: ConnectorActionsRegistry = {
  connectorType: "github",
  connectorName: "GitHub",
  connectorIcon: "github",
  actions: [
    {
      id: "issue_create",
      name: "Create Issue",
      description: "Create a new issue in a repository",
      connectorType: "github",
      resource: "issue",
      category: "create",
      stakes: "medium",
      reversible: true,
      batchSupport: false,
      inputs: [
        {
          id: "owner",
          name: "Owner",
          type: "string",
          required: true,
          description: "Repository owner (user or org)",
        },
        {
          id: "repo",
          name: "Repository",
          type: "string",
          required: true,
          description: "Repository name",
        },
        {
          id: "title",
          name: "Title",
          type: "string",
          required: true,
          description: "Issue title",
        },
        {
          id: "body",
          name: "Body",
          type: "string",
          required: false,
          description: "Issue body markdown",
        },
        {
          id: "labels",
          name: "Labels",
          type: "array",
          required: false,
          description: "Issue labels",
        },
      ],
      outputs: [
        {
          id: "issueNumber",
          name: "Issue Number",
          type: "number",
          description: "Created issue number",
        },
        {
          id: "url",
          name: "URL",
          type: "string",
          description: "Issue URL",
        },
      ],
    },
    {
      id: "issue_comment",
      name: "Add Issue Comment",
      description: "Post a comment on an issue",
      connectorType: "github",
      resource: "issue",
      category: "create",
      stakes: "low",
      reversible: false,
      batchSupport: false,
      inputs: [
        {
          id: "owner",
          name: "Owner",
          type: "string",
          required: true,
          description: "Repository owner",
        },
        {
          id: "repo",
          name: "Repository",
          type: "string",
          required: true,
          description: "Repository name",
        },
        {
          id: "issueNumber",
          name: "Issue Number",
          type: "number",
          required: true,
          description: "Issue number",
        },
        {
          id: "body",
          name: "Comment",
          type: "string",
          required: true,
          description: "Comment markdown",
        },
      ],
      outputs: [
        {
          id: "commentId",
          name: "Comment ID",
          type: "number",
          description: "Created comment id",
        },
        {
          id: "url",
          name: "URL",
          type: "string",
          description: "Comment URL",
        },
      ],
    },
    {
      id: "pull_request_create",
      name: "Create Pull Request",
      description: "Create a pull request between branches",
      connectorType: "github",
      resource: "pull_request",
      category: "create",
      stakes: "high",
      reversible: true,
      batchSupport: false,
      inputs: [
        {
          id: "owner",
          name: "Owner",
          type: "string",
          required: true,
          description: "Repository owner",
        },
        {
          id: "repo",
          name: "Repository",
          type: "string",
          required: true,
          description: "Repository name",
        },
        {
          id: "title",
          name: "Title",
          type: "string",
          required: true,
          description: "Pull request title",
        },
        {
          id: "head",
          name: "Head Branch",
          type: "string",
          required: true,
          description: "Source branch",
        },
        {
          id: "base",
          name: "Base Branch",
          type: "string",
          required: true,
          description: "Target branch",
        },
        {
          id: "body",
          name: "Body",
          type: "string",
          required: false,
          description: "Pull request description",
        },
      ],
      outputs: [
        {
          id: "pullRequestNumber",
          name: "PR Number",
          type: "number",
          description: "Created pull request number",
        },
        {
          id: "url",
          name: "URL",
          type: "string",
          description: "Pull request URL",
        },
      ],
    },
    {
      id: "pull_request_comment",
      name: "Add Pull Request Comment",
      description: "Add a review comment to a pull request",
      connectorType: "github",
      resource: "pull_request",
      category: "create",
      stakes: "medium",
      reversible: false,
      batchSupport: false,
      inputs: [
        {
          id: "owner",
          name: "Owner",
          type: "string",
          required: true,
          description: "Repository owner",
        },
        {
          id: "repo",
          name: "Repository",
          type: "string",
          required: true,
          description: "Repository name",
        },
        {
          id: "pullRequestNumber",
          name: "PR Number",
          type: "number",
          required: true,
          description: "Pull request number",
        },
        {
          id: "body",
          name: "Comment",
          type: "string",
          required: true,
          description: "Comment content",
        },
      ],
      outputs: [
        {
          id: "commentId",
          name: "Comment ID",
          type: "number",
          description: "Created comment id",
        },
      ],
    },
    {
      id: "issues_search",
      name: "Search Issues",
      description: "Search issues and pull requests",
      connectorType: "github",
      resource: "issue",
      category: "search",
      stakes: "low",
      reversible: false,
      batchSupport: false,
      inputs: [
        {
          id: "query",
          name: "Query",
          type: "string",
          required: true,
          description: "GitHub issue search query",
        },
        {
          id: "limit",
          name: "Limit",
          type: "number",
          required: false,
          description: "Maximum result count",
        },
      ],
      outputs: [
        {
          id: "items",
          name: "Items",
          type: "array",
          description: "Matching issues and pull requests",
        },
        {
          id: "totalCount",
          name: "Total Count",
          type: "number",
          description: "Total matches",
        },
      ],
    },
    {
      id: "repository_get",
      name: "Get Repository",
      description: "Retrieve repository details",
      connectorType: "github",
      resource: "repository",
      category: "read",
      stakes: "low",
      reversible: false,
      batchSupport: false,
      inputs: [
        {
          id: "owner",
          name: "Owner",
          type: "string",
          required: true,
          description: "Repository owner",
        },
        {
          id: "repo",
          name: "Repository",
          type: "string",
          required: true,
          description: "Repository name",
        },
      ],
      outputs: [
        {
          id: "repository",
          name: "Repository",
          type: "object",
          description: "Repository details",
        },
      ],
    },
  ],
};
