import type { ConnectorActionsRegistry } from "@openbeam/types/connector-actions";

export const gitlabActionsRegistry: ConnectorActionsRegistry = {
  connectorType: "gitlab",
  connectorName: "GitLab",
  connectorIcon: "gitlab",
  actions: [
    {
      id: "project_list",
      name: "List Projects",
      description:
        "List GitLab projects the current user is a member of. Returns up to 100 projects ordered by last activity with id, name, full path, and visibility. Call this FIRST before issue_create or merge_request_create to discover the required numeric projectId. Do NOT guess project IDs.",
      connectorType: "gitlab",
      resource: "project",
      category: "list",
      stakes: "low",
      reversible: true,
      batchSupport: false,
      idempotent: true,
      inputs: [
        {
          id: "visibility",
          name: "Visibility",
          type: "string",
          required: false,
          description:
            "Filter by visibility: 'public', 'internal', or 'private'.",
        },
        {
          id: "limit",
          name: "Limit",
          type: "number",
          required: false,
          description: "Max projects to return (1-100, default 50).",
        },
      ],
      outputs: [
        {
          id: "projects",
          name: "Projects",
          type: "array",
          description:
            "Array of { id, name, path, visibility }. Use 'id' as the projectId input to issue_create or merge_request_create.",
        },
      ],
    },
    {
      id: "issue_create",
      name: "Create Issue",
      description:
        "Create a new issue in a GitLab project. Requires projectId (numeric) — call project_list first to discover available projects. Returns the issue URL.",
      connectorType: "gitlab",
      resource: "issue",
      category: "create",
      stakes: "medium",
      reversible: true,
      batchSupport: false,
      idempotent: false,
      inputs: [
        {
          id: "projectId",
          name: "Project ID",
          type: "number",
          required: true,
          description: "GitLab project ID",
        },
        {
          id: "title",
          name: "Title",
          type: "string",
          required: true,
          description: "Issue title",
        },
        {
          id: "description",
          name: "Description",
          type: "string",
          required: false,
          description: "Issue description markdown",
        },
        {
          id: "labels",
          name: "Labels",
          type: "string",
          required: false,
          description: "Comma-separated labels",
        },
      ],
      outputs: [
        {
          id: "issueIid",
          name: "Issue IID",
          type: "number",
          description: "Created issue IID within project",
        },
        {
          id: "url",
          name: "URL",
          type: "string",
          description: "Issue URL",
        },
      ],
    },
    {
      id: "issue_comment",
      name: "Add Issue Note",
      description: "Post a note (comment) on an issue",
      connectorType: "gitlab",
      resource: "issue",
      category: "create",
      stakes: "low",
      reversible: false,
      batchSupport: false,
      idempotent: false,
      inputs: [
        {
          id: "projectId",
          name: "Project ID",
          type: "number",
          required: true,
          description: "GitLab project ID",
        },
        {
          id: "issueIid",
          name: "Issue IID",
          type: "number",
          required: true,
          description: "Issue IID within the project",
        },
        {
          id: "body",
          name: "Note",
          type: "string",
          required: true,
          description: "Note content",
        },
      ],
      outputs: [
        {
          id: "noteId",
          name: "Note ID",
          type: "number",
          description: "Created note ID",
        },
      ],
    },
    {
      id: "merge_request_create",
      name: "Create Merge Request",
      description:
        "Create a merge request between branches in a GitLab project. Requires projectId (numeric) — call project_list first to discover available projects. Also requires source and target branch names.",
      connectorType: "gitlab",
      resource: "merge_request",
      category: "create",
      stakes: "high",
      reversible: true,
      batchSupport: false,
      idempotent: false,
      inputs: [
        {
          id: "projectId",
          name: "Project ID",
          type: "number",
          required: true,
          description: "GitLab project ID",
        },
        {
          id: "title",
          name: "Title",
          type: "string",
          required: true,
          description: "Merge request title",
        },
        {
          id: "sourceBranch",
          name: "Source Branch",
          type: "string",
          required: true,
          description: "Source branch name",
        },
        {
          id: "targetBranch",
          name: "Target Branch",
          type: "string",
          required: true,
          description: "Target branch name",
        },
        {
          id: "description",
          name: "Description",
          type: "string",
          required: false,
          description: "Merge request description",
        },
      ],
      outputs: [
        {
          id: "mergeRequestIid",
          name: "MR IID",
          type: "number",
          description: "Created merge request IID",
        },
        {
          id: "url",
          name: "URL",
          type: "string",
          description: "Merge request URL",
        },
      ],
    },
    {
      id: "merge_request_comment",
      name: "Add MR Note",
      description: "Add a note to a merge request",
      connectorType: "gitlab",
      resource: "merge_request",
      category: "create",
      stakes: "medium",
      reversible: false,
      batchSupport: false,
      idempotent: false,
      inputs: [
        {
          id: "projectId",
          name: "Project ID",
          type: "number",
          required: true,
          description: "GitLab project ID",
        },
        {
          id: "mergeRequestIid",
          name: "MR IID",
          type: "number",
          required: true,
          description: "Merge request IID",
        },
        {
          id: "body",
          name: "Note",
          type: "string",
          required: true,
          description: "Note content",
        },
      ],
      outputs: [
        {
          id: "noteId",
          name: "Note ID",
          type: "number",
          description: "Created note ID",
        },
      ],
    },
  ],
};
