import type { ConnectorActionsRegistry } from "@openbeam/types/connector-actions";

export const gitlabActionsRegistry: ConnectorActionsRegistry = {
  connectorType: "gitlab",
  connectorName: "GitLab",
  connectorIcon: "gitlab",
  actions: [
    {
      id: "issue_create",
      name: "Create Issue",
      description: "Create a new issue in a project",
      connectorType: "gitlab",
      resource: "issue",
      category: "create",
      stakes: "medium",
      reversible: true,
      batchSupport: false,
      inputs: [
        {
          id: "projectId",
          name: "Project ID",
          type: "number",
          required: true,
          description: "GitLab project ID",
        },
        {
          id: "title",
          name: "Title",
          type: "string",
          required: true,
          description: "Issue title",
        },
        {
          id: "description",
          name: "Description",
          type: "string",
          required: false,
          description: "Issue description markdown",
        },
        {
          id: "labels",
          name: "Labels",
          type: "string",
          required: false,
          description: "Comma-separated labels",
        },
      ],
      outputs: [
        {
          id: "issueIid",
          name: "Issue IID",
          type: "number",
          description: "Created issue IID within project",
        },
        {
          id: "url",
          name: "URL",
          type: "string",
          description: "Issue URL",
        },
      ],
    },
    {
      id: "issue_comment",
      name: "Add Issue Note",
      description: "Post a note (comment) on an issue",
      connectorType: "gitlab",
      resource: "issue",
      category: "create",
      stakes: "low",
      reversible: false,
      batchSupport: false,
      inputs: [
        {
          id: "projectId",
          name: "Project ID",
          type: "number",
          required: true,
          description: "GitLab project ID",
        },
        {
          id: "issueIid",
          name: "Issue IID",
          type: "number",
          required: true,
          description: "Issue IID within the project",
        },
        {
          id: "body",
          name: "Note",
          type: "string",
          required: true,
          description: "Note content",
        },
      ],
      outputs: [
        {
          id: "noteId",
          name: "Note ID",
          type: "number",
          description: "Created note ID",
        },
      ],
    },
    {
      id: "merge_request_create",
      name: "Create Merge Request",
      description: "Create a merge request between branches",
      connectorType: "gitlab",
      resource: "merge_request",
      category: "create",
      stakes: "high",
      reversible: true,
      batchSupport: false,
      inputs: [
        {
          id: "projectId",
          name: "Project ID",
          type: "number",
          required: true,
          description: "GitLab project ID",
        },
        {
          id: "title",
          name: "Title",
          type: "string",
          required: true,
          description: "Merge request title",
        },
        {
          id: "sourceBranch",
          name: "Source Branch",
          type: "string",
          required: true,
          description: "Source branch name",
        },
        {
          id: "targetBranch",
          name: "Target Branch",
          type: "string",
          required: true,
          description: "Target branch name",
        },
        {
          id: "description",
          name: "Description",
          type: "string",
          required: false,
          description: "Merge request description",
        },
      ],
      outputs: [
        {
          id: "mergeRequestIid",
          name: "MR IID",
          type: "number",
          description: "Created merge request IID",
        },
        {
          id: "url",
          name: "URL",
          type: "string",
          description: "Merge request URL",
        },
      ],
    },
    {
      id: "merge_request_comment",
      name: "Add MR Note",
      description: "Add a note to a merge request",
      connectorType: "gitlab",
      resource: "merge_request",
      category: "create",
      stakes: "medium",
      reversible: false,
      batchSupport: false,
      inputs: [
        {
          id: "projectId",
          name: "Project ID",
          type: "number",
          required: true,
          description: "GitLab project ID",
        },
        {
          id: "mergeRequestIid",
          name: "MR IID",
          type: "number",
          required: true,
          description: "Merge request IID",
        },
        {
          id: "body",
          name: "Note",
          type: "string",
          required: true,
          description: "Note content",
        },
      ],
      outputs: [
        {
          id: "noteId",
          name: "Note ID",
          type: "number",
          description: "Created note ID",
        },
      ],
    },
  ],
};
