import type { ConnectorActionsRegistry } from "@openplane/types/canvas";

export const gmailActions: ConnectorActionsRegistry = {
  connectorType: "gmail",
  connectorName: "Gmail",
  connectorIcon: "gmail",
  actions: [
    {
      id: "email_send",
      name: "Send Email",
      description: "Send a new email message",
      connectorType: "gmail",
      resource: "email",
      category: "create",
      stakes: "high",
      reversible: false,
      batchSupport: false,
      requiredScopes: ["https://www.googleapis.com/auth/gmail.send"],
      inputs: [
        {
          id: "to",
          name: "To",
          type: "email",
          required: true,
          description: "Recipient email address",
        },
        {
          id: "subject",
          name: "Subject",
          type: "string",
          required: true,
          description: "Email subject line",
        },
        {
          id: "body",
          name: "Body",
          type: "html",
          required: true,
          description: "Email body content",
        },
        {
          id: "cc",
          name: "CC",
          type: "string",
          required: false,
          description: "CC recipients (comma-separated)",
        },
        {
          id: "bcc",
          name: "BCC",
          type: "string",
          required: false,
          description: "BCC recipients (comma-separated)",
        },
        {
          id: "reply_to",
          name: "Reply To",
          type: "email",
          required: false,
          description: "Reply-to email address",
        },
      ],
      outputs: [
        {
          id: "id",
          name: "Message ID",
          type: "string",
          description: "Sent message ID",
        },
        {
          id: "threadId",
          name: "Thread ID",
          type: "string",
          description: "Thread ID",
        },
      ],
    },
    {
      id: "email_reply",
      name: "Reply to Email",
      description: "Reply to an existing email thread",
      connectorType: "gmail",
      resource: "email",
      category: "create",
      stakes: "high",
      reversible: false,
      batchSupport: false,
      requiredScopes: ["https://www.googleapis.com/auth/gmail.send"],
      inputs: [
        {
          id: "threadId",
          name: "Thread ID",
          type: "string",
          required: true,
          description: "Thread to reply to",
        },
        {
          id: "messageId",
          name: "Message ID",
          type: "string",
          required: true,
          description: "Message to reply to",
        },
        {
          id: "body",
          name: "Body",
          type: "html",
          required: true,
          description: "Reply body content",
        },
        {
          id: "replyAll",
          name: "Reply All",
          type: "boolean",
          required: false,
          description: "Reply to all recipients",
        },
      ],
      outputs: [
        {
          id: "id",
          name: "Message ID",
          type: "string",
          description: "Reply message ID",
        },
      ],
    },
    {
      id: "email_forward",
      name: "Forward Email",
      description: "Forward an email to another recipient",
      connectorType: "gmail",
      resource: "email",
      category: "create",
      stakes: "high",
      reversible: false,
      batchSupport: false,
      requiredScopes: ["https://www.googleapis.com/auth/gmail.send"],
      inputs: [
        {
          id: "messageId",
          name: "Message ID",
          type: "string",
          required: true,
          description: "Message to forward",
        },
        {
          id: "to",
          name: "To",
          type: "email",
          required: true,
          description: "Forward recipient",
        },
        {
          id: "body",
          name: "Body",
          type: "html",
          required: false,
          description: "Additional message",
        },
      ],
      outputs: [
        {
          id: "id",
          name: "Message ID",
          type: "string",
          description: "Forwarded message ID",
        },
      ],
    },
    {
      id: "email_search",
      name: "Search Emails",
      description: "Search emails using Gmail query syntax",
      connectorType: "gmail",
      resource: "email",
      category: "search",
      stakes: "low",
      reversible: false,
      batchSupport: false,
      requiredScopes: ["https://www.googleapis.com/auth/gmail.readonly"],
      inputs: [
        {
          id: "query",
          name: "Query",
          type: "string",
          required: true,
          description:
            "Gmail search query (e.g. 'from:user@example.com subject:invoice')",
        },
        {
          id: "maxResults",
          name: "Max Results",
          type: "number",
          required: false,
          description: "Maximum emails to return",
          validation: { min: 1, max: 500 },
        },
        {
          id: "labelIds",
          name: "Labels",
          type: "string",
          required: false,
          description: "Filter by label IDs (comma-separated)",
          dynamic: true,
          resourceType: "label",
        },
      ],
      outputs: [
        {
          id: "messages",
          name: "Messages",
          type: "array",
          description: "Matching email messages",
        },
        {
          id: "resultSizeEstimate",
          name: "Estimated Total",
          type: "number",
          description: "Estimated total results",
        },
      ],
    },
    {
      id: "email_get",
      name: "Get Email",
      description: "Retrieve a specific email by ID",
      connectorType: "gmail",
      resource: "email",
      category: "read",
      stakes: "low",
      reversible: false,
      batchSupport: true,
      requiredScopes: ["https://www.googleapis.com/auth/gmail.readonly"],
      inputs: [
        {
          id: "messageId",
          name: "Message ID",
          type: "string",
          required: true,
          description: "Email message ID",
        },
        {
          id: "format",
          name: "Format",
          type: "string",
          required: false,
          description: "Response format",
          options: [
            { label: "Full", value: "full" },
            { label: "Metadata", value: "metadata" },
            { label: "Minimal", value: "minimal" },
          ],
        },
      ],
      outputs: [
        {
          id: "id",
          name: "Message ID",
          type: "string",
          description: "Message ID",
        },
        {
          id: "threadId",
          name: "Thread ID",
          type: "string",
          description: "Thread ID",
        },
        {
          id: "subject",
          name: "Subject",
          type: "string",
          description: "Email subject",
        },
        {
          id: "from",
          name: "From",
          type: "string",
          description: "Sender address",
        },
        {
          id: "snippet",
          name: "Snippet",
          type: "string",
          description: "Email preview",
        },
      ],
    },
    {
      id: "email_trash",
      name: "Trash Email",
      description: "Move an email to trash",
      connectorType: "gmail",
      resource: "email",
      category: "delete",
      stakes: "medium",
      reversible: true,
      batchSupport: true,
      requiredScopes: ["https://www.googleapis.com/auth/gmail.modify"],
      inputs: [
        {
          id: "messageId",
          name: "Message ID",
          type: "string",
          required: true,
          description: "Message to trash",
        },
      ],
      outputs: [
        {
          id: "id",
          name: "Message ID",
          type: "string",
          description: "Trashed message ID",
        },
      ],
    },
    {
      id: "email_modify_labels",
      name: "Modify Labels",
      description: "Add or remove labels from an email",
      connectorType: "gmail",
      resource: "email",
      category: "update",
      stakes: "low",
      reversible: true,
      batchSupport: true,
      requiredScopes: ["https://www.googleapis.com/auth/gmail.modify"],
      inputs: [
        {
          id: "messageId",
          name: "Message ID",
          type: "string",
          required: true,
          description: "Message to modify",
        },
        {
          id: "addLabelIds",
          name: "Add Labels",
          type: "string",
          required: false,
          description: "Label IDs to add (comma-separated)",
          dynamic: true,
          resourceType: "label",
        },
        {
          id: "removeLabelIds",
          name: "Remove Labels",
          type: "string",
          required: false,
          description: "Label IDs to remove (comma-separated)",
          dynamic: true,
          resourceType: "label",
        },
      ],
      outputs: [
        {
          id: "id",
          name: "Message ID",
          type: "string",
          description: "Modified message ID",
        },
        {
          id: "labelIds",
          name: "Labels",
          type: "array",
          description: "Current label IDs",
        },
      ],
    },
    {
      id: "label_list",
      name: "List Labels",
      description: "List all Gmail labels",
      connectorType: "gmail",
      resource: "label",
      category: "list",
      stakes: "low",
      reversible: false,
      batchSupport: false,
      requiredScopes: ["https://www.googleapis.com/auth/gmail.labels"],
      inputs: [],
      outputs: [
        {
          id: "labels",
          name: "Labels",
          type: "array",
          description: "All Gmail labels",
        },
      ],
    },
    {
      id: "label_create",
      name: "Create Label",
      description: "Create a new Gmail label",
      connectorType: "gmail",
      resource: "label",
      category: "create",
      stakes: "low",
      reversible: true,
      batchSupport: false,
      requiredScopes: ["https://www.googleapis.com/auth/gmail.labels"],
      inputs: [
        {
          id: "name",
          name: "Name",
          type: "string",
          required: true,
          description: "Label name",
        },
        {
          id: "labelListVisibility",
          name: "Visibility",
          type: "string",
          required: false,
          description: "Label visibility in list",
          options: [
            { label: "Show", value: "labelShow" },
            { label: "Hide", value: "labelHide" },
            { label: "Show If Unread", value: "labelShowIfUnread" },
          ],
        },
      ],
      outputs: [
        {
          id: "id",
          name: "Label ID",
          type: "string",
          description: "Created label ID",
        },
        { id: "name", name: "Name", type: "string", description: "Label name" },
      ],
    },
    {
      id: "draft_create",
      name: "Create Draft",
      description: "Create an email draft",
      connectorType: "gmail",
      resource: "draft",
      category: "create",
      stakes: "low",
      reversible: true,
      batchSupport: false,
      requiredScopes: ["https://www.googleapis.com/auth/gmail.compose"],
      inputs: [
        {
          id: "to",
          name: "To",
          type: "email",
          required: true,
          description: "Recipient email",
        },
        {
          id: "subject",
          name: "Subject",
          type: "string",
          required: true,
          description: "Email subject",
        },
        {
          id: "body",
          name: "Body",
          type: "html",
          required: true,
          description: "Email body",
        },
      ],
      outputs: [
        {
          id: "id",
          name: "Draft ID",
          type: "string",
          description: "Created draft ID",
        },
        {
          id: "messageId",
          name: "Message ID",
          type: "string",
          description: "Draft message ID",
        },
      ],
    },
    {
      id: "thread_get",
      name: "Get Thread",
      description: "Retrieve all messages in a thread",
      connectorType: "gmail",
      resource: "thread",
      category: "read",
      stakes: "low",
      reversible: false,
      batchSupport: false,
      requiredScopes: ["https://www.googleapis.com/auth/gmail.readonly"],
      inputs: [
        {
          id: "threadId",
          name: "Thread ID",
          type: "string",
          required: true,
          description: "Thread ID to retrieve",
        },
      ],
      outputs: [
        {
          id: "id",
          name: "Thread ID",
          type: "string",
          description: "Thread ID",
        },
        {
          id: "messages",
          name: "Messages",
          type: "array",
          description: "Messages in thread",
        },
        {
          id: "snippet",
          name: "Snippet",
          type: "string",
          description: "Thread preview",
        },
      ],
    },
    {
      id: "thread_trash",
      name: "Trash Thread",
      description: "Move an entire thread to trash",
      connectorType: "gmail",
      resource: "thread",
      category: "delete",
      stakes: "medium",
      reversible: true,
      batchSupport: false,
      requiredScopes: ["https://www.googleapis.com/auth/gmail.modify"],
      inputs: [
        {
          id: "threadId",
          name: "Thread ID",
          type: "string",
          required: true,
          description: "Thread to trash",
        },
      ],
      outputs: [
        {
          id: "id",
          name: "Thread ID",
          type: "string",
          description: "Trashed thread ID",
        },
      ],
    },
  ],
};
