import type { ConnectorActionsRegistry } from "@openbeam/types/canvas";

export const gmailActionsRegistry: ConnectorActionsRegistry = {
  connectorType: "gmail",
  connectorName: "Gmail",
  connectorIcon: "gmail",
  actions: [
    {
      id: "email_send",
      name: "Send Email",
      description: "Send a new email",
      connectorType: "gmail",
      resource: "email",
      category: "create",
      stakes: "high",
      reversible: false,
      batchSupport: false,
      requiredScopes: ["https://www.googleapis.com/auth/gmail.send"],
      inputs: [
        {
          id: "to",
          name: "To",
          type: "email",
          required: true,
          description: "Recipient email address(es)",
        },
        {
          id: "subject",
          name: "Subject",
          type: "string",
          required: true,
          description: "Email subject",
        },
        {
          id: "body",
          name: "Body",
          type: "string",
          required: true,
          description: "Email body (HTML supported)",
        },
        {
          id: "cc",
          name: "CC",
          type: "email",
          required: false,
          description: "CC recipients",
        },
        {
          id: "bcc",
          name: "BCC",
          type: "email",
          required: false,
          description: "BCC recipients",
        },
      ],
      outputs: [
        {
          id: "id",
          name: "Message ID",
          type: "string",
          description: "Sent message ID",
        },
        {
          id: "threadId",
          name: "Thread ID",
          type: "string",
          description: "Thread ID",
        },
      ],
    },
    {
      id: "email_reply",
      name: "Reply to Email",
      description: "Reply to an existing email",
      connectorType: "gmail",
      resource: "email",
      category: "create",
      stakes: "high",
      reversible: false,
      batchSupport: false,
      requiredScopes: ["https://www.googleapis.com/auth/gmail.send"],
      inputs: [
        {
          id: "messageId",
          name: "Message ID",
          type: "string",
          required: true,
          description: "Original message ID",
        },
        {
          id: "body",
          name: "Body",
          type: "string",
          required: true,
          description: "Reply body",
        },
        {
          id: "replyAll",
          name: "Reply All",
          type: "boolean",
          required: false,
          description: "Reply to all recipients",
        },
      ],
      outputs: [
        {
          id: "id",
          name: "Message ID",
          type: "string",
          description: "Reply message ID",
        },
        {
          id: "threadId",
          name: "Thread ID",
          type: "string",
          description: "Thread ID",
        },
      ],
    },
    {
      id: "email_forward",
      name: "Forward Email",
      description: "Forward an email to another recipient",
      connectorType: "gmail",
      resource: "email",
      category: "create",
      stakes: "high",
      reversible: false,
      batchSupport: false,
      requiredScopes: ["https://www.googleapis.com/auth/gmail.send"],
      inputs: [
        {
          id: "messageId",
          name: "Message ID",
          type: "string",
          required: true,
          description: "Message to forward",
        },
        {
          id: "to",
          name: "To",
          type: "email",
          required: true,
          description: "Forward recipient(s)",
        },
        {
          id: "body",
          name: "Body",
          type: "string",
          required: false,
          description: "Additional message",
        },
      ],
      outputs: [
        {
          id: "id",
          name: "Message ID",
          type: "string",
          description: "Forwarded message ID",
        },
      ],
    },
    {
      id: "email_search",
      name: "Search Emails",
      description: "Search emails using Gmail query syntax",
      connectorType: "gmail",
      resource: "email",
      category: "search",
      stakes: "low",
      reversible: false,
      batchSupport: false,
      requiredScopes: ["https://www.googleapis.com/auth/gmail.readonly"],
      inputs: [
        {
          id: "query",
          name: "Query",
          type: "string",
          required: true,
          description: "Gmail search query",
        },
        {
          id: "maxResults",
          name: "Max Results",
          type: "number",
          required: false,
          description: "Maximum results to return",
        },
      ],
      outputs: [
        {
          id: "messages",
          name: "Messages",
          type: "array",
          description: "Matching messages",
        },
        {
          id: "total",
          name: "Total",
          type: "number",
          description: "Total result count",
        },
      ],
    },
    {
      id: "email_get",
      name: "Get Email",
      description: "Get a specific email by ID",
      connectorType: "gmail",
      resource: "email",
      category: "read",
      stakes: "low",
      reversible: false,
      batchSupport: true,
      requiredScopes: ["https://www.googleapis.com/auth/gmail.readonly"],
      inputs: [
        {
          id: "messageId",
          name: "Message ID",
          type: "string",
          required: true,
          description: "Message ID",
        },
      ],
      outputs: [
        {
          id: "message",
          name: "Message",
          type: "object",
          description: "Email message",
        },
      ],
    },
    {
      id: "email_trash",
      name: "Trash Email",
      description: "Move an email to trash",
      connectorType: "gmail",
      resource: "email",
      category: "delete",
      stakes: "medium",
      reversible: true,
      batchSupport: true,
      requiredScopes: ["https://www.googleapis.com/auth/gmail.modify"],
      inputs: [
        {
          id: "messageId",
          name: "Message ID",
          type: "string",
          required: true,
          description: "Message to trash",
        },
      ],
      outputs: [
        {
          id: "id",
          name: "Message ID",
          type: "string",
          description: "Trashed message ID",
        },
      ],
    },
    {
      id: "email_modify_labels",
      name: "Modify Labels",
      description: "Add or remove labels from an email",
      connectorType: "gmail",
      resource: "email",
      category: "update",
      stakes: "low",
      reversible: true,
      batchSupport: true,
      requiredScopes: ["https://www.googleapis.com/auth/gmail.modify"],
      inputs: [
        {
          id: "messageId",
          name: "Message ID",
          type: "string",
          required: true,
          description: "Message ID",
        },
        {
          id: "addLabelIds",
          name: "Add Labels",
          type: "array",
          required: false,
          description: "Label IDs to add",
        },
        {
          id: "removeLabelIds",
          name: "Remove Labels",
          type: "array",
          required: false,
          description: "Label IDs to remove",
        },
      ],
      outputs: [
        {
          id: "id",
          name: "Message ID",
          type: "string",
          description: "Modified message ID",
        },
        {
          id: "labelIds",
          name: "Label IDs",
          type: "array",
          description: "Current label IDs",
        },
      ],
    },
    {
      id: "label_list",
      name: "List Labels",
      description: "List all Gmail labels",
      connectorType: "gmail",
      resource: "label",
      category: "list",
      stakes: "low",
      reversible: false,
      batchSupport: false,
      requiredScopes: ["https://www.googleapis.com/auth/gmail.labels"],
      inputs: [],
      outputs: [
        {
          id: "labels",
          name: "Labels",
          type: "array",
          description: "All labels",
        },
      ],
    },
    {
      id: "label_create",
      name: "Create Label",
      description: "Create a new Gmail label",
      connectorType: "gmail",
      resource: "label",
      category: "create",
      stakes: "low",
      reversible: true,
      batchSupport: false,
      requiredScopes: ["https://www.googleapis.com/auth/gmail.labels"],
      inputs: [
        {
          id: "name",
          name: "Name",
          type: "string",
          required: true,
          description: "Label name",
        },
        {
          id: "labelListVisibility",
          name: "List Visibility",
          type: "string",
          required: false,
          description: "Visibility in label list",
        },
        {
          id: "messageListVisibility",
          name: "Message Visibility",
          type: "string",
          required: false,
          description: "Visibility in message list",
        },
      ],
      outputs: [
        {
          id: "id",
          name: "Label ID",
          type: "string",
          description: "Created label ID",
        },
        { id: "name", name: "Name", type: "string", description: "Label name" },
      ],
    },
    {
      id: "draft_create",
      name: "Create Draft",
      description: "Create an email draft",
      connectorType: "gmail",
      resource: "draft",
      category: "create",
      stakes: "low",
      reversible: true,
      batchSupport: false,
      requiredScopes: ["https://www.googleapis.com/auth/gmail.compose"],
      inputs: [
        {
          id: "to",
          name: "To",
          type: "email",
          required: false,
          description: "Recipient email(s)",
        },
        {
          id: "subject",
          name: "Subject",
          type: "string",
          required: false,
          description: "Email subject",
        },
        {
          id: "body",
          name: "Body",
          type: "string",
          required: false,
          description: "Email body",
        },
      ],
      outputs: [
        {
          id: "id",
          name: "Draft ID",
          type: "string",
          description: "Created draft ID",
        },
        {
          id: "messageId",
          name: "Message ID",
          type: "string",
          description: "Draft message ID",
        },
      ],
    },
    {
      id: "thread_get",
      name: "Get Thread",
      description: "Get all messages in a thread",
      connectorType: "gmail",
      resource: "thread",
      category: "read",
      stakes: "low",
      reversible: false,
      batchSupport: false,
      requiredScopes: ["https://www.googleapis.com/auth/gmail.readonly"],
      inputs: [
        {
          id: "threadId",
          name: "Thread ID",
          type: "string",
          required: true,
          description: "Thread ID",
        },
      ],
      outputs: [
        {
          id: "thread",
          name: "Thread",
          type: "object",
          description: "Thread with messages",
        },
      ],
    },
    {
      id: "thread_trash",
      name: "Trash Thread",
      description: "Move entire thread to trash",
      connectorType: "gmail",
      resource: "thread",
      category: "delete",
      stakes: "medium",
      reversible: true,
      batchSupport: false,
      requiredScopes: ["https://www.googleapis.com/auth/gmail.modify"],
      inputs: [
        {
          id: "threadId",
          name: "Thread ID",
          type: "string",
          required: true,
          description: "Thread to trash",
        },
      ],
      outputs: [
        {
          id: "id",
          name: "Thread ID",
          type: "string",
          description: "Trashed thread ID",
        },
      ],
    },
  ],
};
