import type { ConnectorActionsRegistry } from "@openbeam/types/canvas";

export const googleDriveActionsRegistry: ConnectorActionsRegistry = {
  connectorType: "google_drive",
  connectorName: "Google Drive",
  connectorIcon: "google-drive",
  actions: [
    {
      id: "file_get",
      name: "Get File",
      description: "Get file metadata",
      connectorType: "google_drive",
      resource: "file",
      category: "read",
      stakes: "low",
      reversible: false,
      batchSupport: true,
      inputs: [
        {
          id: "fileId",
          name: "File ID",
          type: "string",
          required: true,
          description: "File ID",
        },
        {
          id: "fields",
          name: "Fields",
          type: "string",
          required: false,
          description: "Fields to include",
        },
      ],
      outputs: [
        {
          id: "file",
          name: "File",
          type: "object",
          description: "File metadata",
        },
      ],
    },
    {
      id: "file_search",
      name: "Search Files",
      description: "Search for files in Google Drive",
      connectorType: "google_drive",
      resource: "file",
      category: "search",
      stakes: "low",
      reversible: false,
      batchSupport: false,
      inputs: [
        {
          id: "query",
          name: "Query",
          type: "string",
          required: true,
          description: "Drive query string",
        },
        {
          id: "pageSize",
          name: "Page Size",
          type: "number",
          required: false,
          description: "Results per page",
        },
        {
          id: "orderBy",
          name: "Order By",
          type: "string",
          required: false,
          description: "Sort order",
        },
      ],
      outputs: [
        {
          id: "files",
          name: "Files",
          type: "array",
          description: "Matching files",
        },
        {
          id: "nextPageToken",
          name: "Next Page Token",
          type: "string",
          description: "Pagination token",
        },
      ],
    },
    {
      id: "file_create",
      name: "Create File",
      description: "Create a new file",
      connectorType: "google_drive",
      resource: "file",
      category: "create",
      stakes: "medium",
      reversible: true,
      batchSupport: false,
      inputs: [
        {
          id: "name",
          name: "Name",
          type: "string",
          required: true,
          description: "File name",
        },
        {
          id: "mimeType",
          name: "MIME Type",
          type: "string",
          required: false,
          description: "File MIME type",
        },
        {
          id: "parents",
          name: "Parent Folders",
          type: "array",
          required: false,
          description: "Parent folder IDs",
        },
        {
          id: "content",
          name: "Content",
          type: "string",
          required: false,
          description: "File content",
        },
      ],
      outputs: [
        {
          id: "id",
          name: "File ID",
          type: "string",
          description: "Created file ID",
        },
        { id: "name", name: "Name", type: "string", description: "File name" },
        {
          id: "webViewLink",
          name: "Web Link",
          type: "string",
          description: "View URL",
        },
      ],
    },
    {
      id: "file_copy",
      name: "Copy File",
      description: "Copy a file",
      connectorType: "google_drive",
      resource: "file",
      category: "create",
      stakes: "low",
      reversible: true,
      batchSupport: false,
      inputs: [
        {
          id: "fileId",
          name: "File ID",
          type: "string",
          required: true,
          description: "Source file ID",
        },
        {
          id: "name",
          name: "Name",
          type: "string",
          required: false,
          description: "New file name",
        },
        {
          id: "parents",
          name: "Parent Folders",
          type: "array",
          required: false,
          description: "Destination folder IDs",
        },
      ],
      outputs: [
        {
          id: "id",
          name: "File ID",
          type: "string",
          description: "Copied file ID",
        },
        { id: "name", name: "Name", type: "string", description: "File name" },
      ],
    },
    {
      id: "file_move",
      name: "Move File",
      description: "Move a file to a different folder",
      connectorType: "google_drive",
      resource: "file",
      category: "update",
      stakes: "medium",
      reversible: true,
      batchSupport: false,
      inputs: [
        {
          id: "fileId",
          name: "File ID",
          type: "string",
          required: true,
          description: "File to move",
        },
        {
          id: "addParents",
          name: "Destination Folder",
          type: "string",
          required: true,
          description: "Target folder ID",
        },
        {
          id: "removeParents",
          name: "Source Folder",
          type: "string",
          required: false,
          description: "Current folder ID",
        },
      ],
      outputs: [
        {
          id: "id",
          name: "File ID",
          type: "string",
          description: "Moved file ID",
        },
        {
          id: "parents",
          name: "Parents",
          type: "array",
          description: "New parent folders",
        },
      ],
    },
    {
      id: "file_rename",
      name: "Rename File",
      description: "Rename a file",
      connectorType: "google_drive",
      resource: "file",
      category: "update",
      stakes: "low",
      reversible: true,
      batchSupport: false,
      inputs: [
        {
          id: "fileId",
          name: "File ID",
          type: "string",
          required: true,
          description: "File to rename",
        },
        {
          id: "name",
          name: "Name",
          type: "string",
          required: true,
          description: "New name",
        },
      ],
      outputs: [
        { id: "id", name: "File ID", type: "string", description: "File ID" },
        { id: "name", name: "Name", type: "string", description: "New name" },
      ],
    },
    {
      id: "file_delete",
      name: "Delete File",
      description: "Move file to trash",
      connectorType: "google_drive",
      resource: "file",
      category: "delete",
      stakes: "high",
      reversible: true,
      batchSupport: false,
      inputs: [
        {
          id: "fileId",
          name: "File ID",
          type: "string",
          required: true,
          description: "File to delete",
        },
      ],
      outputs: [
        {
          id: "id",
          name: "File ID",
          type: "string",
          description: "Deleted file ID",
        },
      ],
    },
    {
      id: "permission_create",
      name: "Share File",
      description: "Share a file with a user",
      connectorType: "google_drive",
      resource: "permission",
      category: "create",
      stakes: "high",
      reversible: true,
      batchSupport: false,
      inputs: [
        {
          id: "fileId",
          name: "File ID",
          type: "string",
          required: true,
          description: "File to share",
        },
        {
          id: "email",
          name: "Email",
          type: "email",
          required: true,
          description: "User email",
        },
        {
          id: "role",
          name: "Role",
          type: "string",
          required: true,
          description: "Permission role (reader, writer, commenter)",
        },
        {
          id: "sendNotification",
          name: "Send Notification",
          type: "boolean",
          required: false,
          description: "Email the user",
        },
      ],
      outputs: [
        {
          id: "id",
          name: "Permission ID",
          type: "string",
          description: "Created permission ID",
        },
      ],
    },
    {
      id: "permission_remove",
      name: "Remove Access",
      description: "Remove user access from a file",
      connectorType: "google_drive",
      resource: "permission",
      category: "delete",
      stakes: "high",
      reversible: false,
      batchSupport: false,
      inputs: [
        {
          id: "fileId",
          name: "File ID",
          type: "string",
          required: true,
          description: "File ID",
        },
        {
          id: "email",
          name: "Email",
          type: "email",
          required: true,
          description: "User to remove",
        },
      ],
      outputs: [
        {
          id: "ok",
          name: "Success",
          type: "boolean",
          description: "Whether removal succeeded",
        },
      ],
    },
    {
      id: "folder_create",
      name: "Create Folder",
      description: "Create a new folder",
      connectorType: "google_drive",
      resource: "folder",
      category: "create",
      stakes: "low",
      reversible: true,
      batchSupport: false,
      inputs: [
        {
          id: "name",
          name: "Name",
          type: "string",
          required: true,
          description: "Folder name",
        },
        {
          id: "parents",
          name: "Parent Folders",
          type: "array",
          required: false,
          description: "Parent folder IDs",
        },
      ],
      outputs: [
        {
          id: "id",
          name: "Folder ID",
          type: "string",
          description: "Created folder ID",
        },
        {
          id: "name",
          name: "Name",
          type: "string",
          description: "Folder name",
        },
        {
          id: "webViewLink",
          name: "Web Link",
          type: "string",
          description: "View URL",
        },
      ],
    },
  ],
};
