import type { ConnectorActionsRegistry } from "@openplane/types/canvas";

export const googleDriveActions: ConnectorActionsRegistry = {
  connectorType: "google_drive",
  connectorName: "Google Drive",
  connectorIcon: "google-drive",
  actions: [
    {
      id: "file_get",
      name: "Get File",
      description: "Get metadata for a file or folder",
      connectorType: "google_drive",
      resource: "file",
      category: "read",
      stakes: "low",
      reversible: false,
      batchSupport: true,
      requiredScopes: ["https://www.googleapis.com/auth/drive.readonly"],
      inputs: [
        {
          id: "fileId",
          name: "File ID",
          type: "string",
          required: true,
          description: "Drive file or folder ID",
        },
        {
          id: "fields",
          name: "Fields",
          type: "string",
          required: false,
          description: "Specific fields to return (comma-separated)",
        },
      ],
      outputs: [
        { id: "id", name: "File ID", type: "string", description: "File ID" },
        { id: "name", name: "Name", type: "string", description: "File name" },
        {
          id: "mimeType",
          name: "MIME Type",
          type: "string",
          description: "File type",
        },
        {
          id: "webViewLink",
          name: "Link",
          type: "string",
          description: "Web view URL",
        },
      ],
    },
    {
      id: "file_search",
      name: "Search Files",
      description: "Search for files and folders in Drive",
      connectorType: "google_drive",
      resource: "file",
      category: "search",
      stakes: "low",
      reversible: false,
      batchSupport: false,
      requiredScopes: ["https://www.googleapis.com/auth/drive.readonly"],
      inputs: [
        {
          id: "query",
          name: "Query",
          type: "string",
          required: true,
          description: "Drive search query (e.g. \"name contains 'report'\")",
        },
        {
          id: "pageSize",
          name: "Page Size",
          type: "number",
          required: false,
          description: "Results per page",
          validation: { min: 1, max: 1000 },
        },
        {
          id: "orderBy",
          name: "Order By",
          type: "string",
          required: false,
          description: "Sort order",
          options: [
            { label: "Modified Time", value: "modifiedTime desc" },
            { label: "Name", value: "name" },
            { label: "Created Time", value: "createdTime desc" },
          ],
        },
      ],
      outputs: [
        {
          id: "files",
          name: "Files",
          type: "array",
          description: "Matching files",
        },
        {
          id: "nextPageToken",
          name: "Next Page Token",
          type: "string",
          description: "Pagination token",
        },
      ],
    },
    {
      id: "file_create",
      name: "Create File",
      description: "Create a new file in Google Drive",
      connectorType: "google_drive",
      resource: "file",
      category: "create",
      stakes: "medium",
      reversible: true,
      batchSupport: false,
      requiredScopes: ["https://www.googleapis.com/auth/drive.file"],
      inputs: [
        {
          id: "name",
          name: "Name",
          type: "string",
          required: true,
          description: "File name",
        },
        {
          id: "mimeType",
          name: "MIME Type",
          type: "string",
          required: true,
          description:
            "File MIME type (e.g. 'application/vnd.google-apps.document')",
        },
        {
          id: "parentId",
          name: "Parent Folder",
          type: "string",
          required: false,
          description: "Parent folder ID",
          dynamic: true,
          resourceType: "shared_drive",
        },
        {
          id: "content",
          name: "Content",
          type: "string",
          required: false,
          description: "File content (for text-based files)",
        },
      ],
      outputs: [
        {
          id: "id",
          name: "File ID",
          type: "string",
          description: "Created file ID",
        },
        {
          id: "webViewLink",
          name: "Link",
          type: "string",
          description: "Web view URL",
        },
      ],
    },
    {
      id: "file_copy",
      name: "Copy File",
      description: "Create a copy of an existing file",
      connectorType: "google_drive",
      resource: "file",
      category: "create",
      stakes: "low",
      reversible: true,
      batchSupport: true,
      requiredScopes: ["https://www.googleapis.com/auth/drive.file"],
      inputs: [
        {
          id: "fileId",
          name: "Source File ID",
          type: "string",
          required: true,
          description: "File to copy",
        },
        {
          id: "name",
          name: "New Name",
          type: "string",
          required: false,
          description: "Name for the copy",
        },
        {
          id: "parentId",
          name: "Destination Folder",
          type: "string",
          required: false,
          description: "Folder for the copy",
          dynamic: true,
          resourceType: "shared_drive",
        },
      ],
      outputs: [
        {
          id: "id",
          name: "File ID",
          type: "string",
          description: "Copied file ID",
        },
        { id: "name", name: "Name", type: "string", description: "File name" },
      ],
    },
    {
      id: "file_move",
      name: "Move File",
      description: "Move a file to a different folder",
      connectorType: "google_drive",
      resource: "file",
      category: "update",
      stakes: "medium",
      reversible: true,
      batchSupport: true,
      requiredScopes: ["https://www.googleapis.com/auth/drive"],
      inputs: [
        {
          id: "fileId",
          name: "File ID",
          type: "string",
          required: true,
          description: "File to move",
        },
        {
          id: "destinationId",
          name: "Destination Folder",
          type: "string",
          required: true,
          description: "Target folder ID",
          dynamic: true,
          resourceType: "shared_drive",
        },
      ],
      outputs: [
        {
          id: "id",
          name: "File ID",
          type: "string",
          description: "Moved file ID",
        },
        {
          id: "parents",
          name: "Parents",
          type: "array",
          description: "New parent folder IDs",
        },
      ],
    },
    {
      id: "file_rename",
      name: "Rename File",
      description: "Rename a file or folder",
      connectorType: "google_drive",
      resource: "file",
      category: "update",
      stakes: "low",
      reversible: true,
      batchSupport: true,
      requiredScopes: ["https://www.googleapis.com/auth/drive"],
      inputs: [
        {
          id: "fileId",
          name: "File ID",
          type: "string",
          required: true,
          description: "File to rename",
        },
        {
          id: "name",
          name: "New Name",
          type: "string",
          required: true,
          description: "New file name",
        },
      ],
      outputs: [
        {
          id: "id",
          name: "File ID",
          type: "string",
          description: "Renamed file ID",
        },
        {
          id: "name",
          name: "Name",
          type: "string",
          description: "Updated name",
        },
      ],
    },
    {
      id: "file_delete",
      name: "Delete File",
      description: "Permanently delete a file (bypasses trash)",
      connectorType: "google_drive",
      resource: "file",
      category: "delete",
      stakes: "high",
      reversible: false,
      batchSupport: true,
      requiredScopes: ["https://www.googleapis.com/auth/drive"],
      inputs: [
        {
          id: "fileId",
          name: "File ID",
          type: "string",
          required: true,
          description: "File to delete",
        },
      ],
      outputs: [
        {
          id: "ok",
          name: "Success",
          type: "boolean",
          description: "Whether deletion succeeded",
        },
      ],
    },
    {
      id: "permission_create",
      name: "Share File",
      description: "Grant access to a file or folder",
      connectorType: "google_drive",
      resource: "permission",
      category: "create",
      stakes: "high",
      reversible: true,
      batchSupport: false,
      requiredScopes: ["https://www.googleapis.com/auth/drive"],
      inputs: [
        {
          id: "fileId",
          name: "File ID",
          type: "string",
          required: true,
          description: "File to share",
        },
        {
          id: "email",
          name: "Email",
          type: "email",
          required: true,
          description: "Email of the person to share with",
        },
        {
          id: "role",
          name: "Role",
          type: "string",
          required: true,
          description: "Permission role",
          options: [
            { label: "Viewer", value: "reader" },
            { label: "Commenter", value: "commenter" },
            { label: "Editor", value: "writer" },
          ],
        },
        {
          id: "sendNotification",
          name: "Send Notification",
          type: "boolean",
          required: false,
          description: "Send email notification",
        },
      ],
      outputs: [
        {
          id: "id",
          name: "Permission ID",
          type: "string",
          description: "Created permission ID",
        },
        {
          id: "role",
          name: "Role",
          type: "string",
          description: "Granted role",
        },
      ],
    },
    {
      id: "permission_remove",
      name: "Remove Access",
      description: "Remove someone's access to a file",
      connectorType: "google_drive",
      resource: "permission",
      category: "delete",
      stakes: "high",
      reversible: false,
      batchSupport: false,
      requiredScopes: ["https://www.googleapis.com/auth/drive"],
      inputs: [
        {
          id: "fileId",
          name: "File ID",
          type: "string",
          required: true,
          description: "File to modify",
        },
        {
          id: "permissionId",
          name: "Permission ID",
          type: "string",
          required: true,
          description: "Permission to remove",
        },
      ],
      outputs: [
        {
          id: "ok",
          name: "Success",
          type: "boolean",
          description: "Whether removal succeeded",
        },
      ],
    },
    {
      id: "folder_create",
      name: "Create Folder",
      description: "Create a new folder in Drive",
      connectorType: "google_drive",
      resource: "folder",
      category: "create",
      stakes: "low",
      reversible: true,
      batchSupport: false,
      requiredScopes: ["https://www.googleapis.com/auth/drive.file"],
      inputs: [
        {
          id: "name",
          name: "Name",
          type: "string",
          required: true,
          description: "Folder name",
        },
        {
          id: "parentId",
          name: "Parent Folder",
          type: "string",
          required: false,
          description: "Parent folder ID",
          dynamic: true,
          resourceType: "shared_drive",
        },
      ],
      outputs: [
        {
          id: "id",
          name: "Folder ID",
          type: "string",
          description: "Created folder ID",
        },
        {
          id: "webViewLink",
          name: "Link",
          type: "string",
          description: "Folder URL",
        },
      ],
    },
  ],
};
