import type { ConnectorActionsRegistry } from "@openbeam/types/connector-actions";

export const googleCalendarActionsRegistry: ConnectorActionsRegistry = {
  connectorType: "google_calendar",
  connectorName: "Google Calendar",
  connectorIcon: "google-calendar",
  actions: [
    {
      id: "calendar_list",
      name: "List Calendars",
      description:
        "List Google Calendars the current user has access to, including shared and team calendars. Returns id, summary, primary flag, access role, and timezone. Call this before event_create when the user wants to target a specific non-primary calendar (e.g. 'Team Calendar' or 'Engineering Standups'). For the user's main calendar, pass calendar_id='primary' without calling this first.",
      connectorType: "google_calendar",
      resource: "calendar",
      category: "list",
      stakes: "low",
      reversible: true,
      batchSupport: false,
      idempotent: true,
      inputs: [
        {
          id: "limit",
          name: "Limit",
          type: "number",
          required: false,
          description: "Max calendars to return (1-250, default 50).",
        },
      ],
      outputs: [
        {
          id: "calendars",
          name: "Calendars",
          type: "array",
          description:
            "Array of { id, summary, primary, accessRole, timeZone }. Use 'id' as the calendar_id input to event_create or event_update.",
        },
      ],
    },
    {
      id: "event_create",
      name: "Create Event",
      description: "Create a new calendar event",
      connectorType: "google_calendar",
      resource: "event",
      category: "create",
      stakes: "medium",
      reversible: true,
      batchSupport: false,
      idempotent: false,
      inputs: [
        {
          id: "summary",
          name: "Title",
          type: "string",
          required: true,
        },
        {
          id: "start_date_time",
          name: "Start Time",
          type: "date",
          required: true,
          description: "ISO 8601 datetime",
        },
        {
          id: "end_date_time",
          name: "End Time",
          type: "date",
          required: true,
          description: "ISO 8601 datetime",
        },
        {
          id: "description",
          name: "Description",
          type: "string",
          required: false,
        },
        {
          id: "location",
          name: "Location",
          type: "string",
          required: false,
        },
        {
          id: "attendees",
          name: "Attendees",
          type: "array",
          required: false,
          description: "Email addresses of attendees",
        },
        {
          id: "calendar_id",
          name: "Calendar ID",
          type: "string",
          required: false,
          default: "primary",
        },
      ],
      outputs: [
        { id: "eventId", name: "Event ID", type: "string" },
        { id: "url", name: "Event URL", type: "string" },
      ],
    },
    {
      id: "event_update",
      name: "Update Event",
      description: "Update an existing calendar event",
      connectorType: "google_calendar",
      resource: "event",
      category: "update",
      stakes: "low",
      reversible: true,
      batchSupport: false,
      idempotent: true,
      inputs: [
        {
          id: "event_id",
          name: "Event ID",
          type: "string",
          required: true,
        },
        {
          id: "summary",
          name: "Title",
          type: "string",
          required: false,
        },
        {
          id: "start_date_time",
          name: "Start Time",
          type: "date",
          required: false,
        },
        {
          id: "end_date_time",
          name: "End Time",
          type: "date",
          required: false,
        },
        {
          id: "description",
          name: "Description",
          type: "string",
          required: false,
        },
        {
          id: "location",
          name: "Location",
          type: "string",
          required: false,
        },
        {
          id: "calendar_id",
          name: "Calendar ID",
          type: "string",
          required: false,
          default: "primary",
        },
      ],
      outputs: [
        { id: "eventId", name: "Event ID", type: "string" },
        { id: "url", name: "Event URL", type: "string" },
      ],
    },
    {
      id: "event_delete",
      name: "Delete Event",
      description: "Delete a calendar event",
      connectorType: "google_calendar",
      resource: "event",
      category: "delete",
      stakes: "high",
      reversible: false,
      batchSupport: false,
      idempotent: true,
      inputs: [
        {
          id: "event_id",
          name: "Event ID",
          type: "string",
          required: true,
        },
        {
          id: "calendar_id",
          name: "Calendar ID",
          type: "string",
          required: false,
          default: "primary",
        },
      ],
      outputs: [{ id: "eventId", name: "Event ID", type: "string" }],
    },
  ],
};
