import type { ConnectorActionsRegistry } from "@openbeam/types/canvas";

export const jiraActionsRegistry: ConnectorActionsRegistry = {
  connectorType: "jira",
  connectorName: "Jira",
  connectorIcon: "jira",
  actions: [
    {
      id: "issue_create",
      name: "Create Issue",
      description: "Create a new Jira issue in a project",
      connectorType: "jira",
      resource: "issue",
      category: "create",
      stakes: "medium",
      reversible: false,
      batchSupport: false,
      inputs: [
        {
          id: "project_key",
          name: "Project Key",
          type: "string",
          required: true,
          description: "Project key (e.g., ENG, PLATFORM)",
        },
        {
          id: "summary",
          name: "Summary",
          type: "string",
          required: true,
          description: "Issue title",
        },
        {
          id: "description",
          name: "Description",
          type: "string",
          required: false,
          description: "Issue description",
        },
        {
          id: "issue_type",
          name: "Issue Type",
          type: "string",
          required: false,
          description: "Task, Bug, Story, Epic",
          default: "Task",
        },
        {
          id: "priority",
          name: "Priority",
          type: "string",
          required: false,
          description: "Highest, High, Medium, Low, Lowest",
        },
        {
          id: "assignee_id",
          name: "Assignee Account ID",
          type: "string",
          required: false,
          description: "Atlassian account ID of assignee",
        },
        {
          id: "labels",
          name: "Labels",
          type: "array",
          required: false,
          description: "Comma-separated labels",
        },
      ],
      outputs: [
        { id: "issueId", name: "Issue ID", type: "string" },
        { id: "issueKey", name: "Issue Key", type: "string" },
        { id: "url", name: "Issue URL", type: "string" },
      ],
    },
    {
      id: "issue_update",
      name: "Update Issue",
      description: "Update fields on an existing Jira issue",
      connectorType: "jira",
      resource: "issue",
      category: "update",
      stakes: "low",
      reversible: true,
      batchSupport: false,
      inputs: [
        {
          id: "issue_key",
          name: "Issue Key",
          type: "string",
          required: true,
          description: "Issue key (e.g., ENG-123)",
        },
        {
          id: "summary",
          name: "Summary",
          type: "string",
          required: false,
        },
        {
          id: "description",
          name: "Description",
          type: "string",
          required: false,
        },
        {
          id: "priority",
          name: "Priority",
          type: "string",
          required: false,
        },
        {
          id: "labels",
          name: "Labels",
          type: "array",
          required: false,
        },
      ],
      outputs: [{ id: "issueKey", name: "Issue Key", type: "string" }],
    },
    {
      id: "issue_transition",
      name: "Transition Issue",
      description: "Change the status of a Jira issue",
      connectorType: "jira",
      resource: "issue",
      category: "update",
      stakes: "medium",
      reversible: true,
      batchSupport: false,
      inputs: [
        {
          id: "issue_key",
          name: "Issue Key",
          type: "string",
          required: true,
        },
        {
          id: "target_status",
          name: "Target Status",
          type: "string",
          required: true,
          description: "Status name to transition to (e.g., Done, In Progress)",
        },
      ],
      outputs: [{ id: "issueKey", name: "Issue Key", type: "string" }],
    },
    {
      id: "issue_assign",
      name: "Assign Issue",
      description: "Assign an issue to a user",
      connectorType: "jira",
      resource: "issue",
      category: "update",
      stakes: "low",
      reversible: true,
      batchSupport: false,
      inputs: [
        {
          id: "issue_key",
          name: "Issue Key",
          type: "string",
          required: true,
        },
        {
          id: "assignee_id",
          name: "Assignee Account ID",
          type: "string",
          required: true,
          description: "Atlassian account ID",
        },
      ],
      outputs: [{ id: "issueKey", name: "Issue Key", type: "string" }],
    },
    {
      id: "comment_add",
      name: "Add Comment",
      description: "Add a comment to a Jira issue",
      connectorType: "jira",
      resource: "comment",
      category: "create",
      stakes: "low",
      reversible: false,
      batchSupport: false,
      inputs: [
        {
          id: "issue_key",
          name: "Issue Key",
          type: "string",
          required: true,
        },
        {
          id: "body",
          name: "Comment Body",
          type: "string",
          required: true,
          description: "Comment text",
        },
      ],
      outputs: [{ id: "commentId", name: "Comment ID", type: "string" }],
    },
    {
      id: "issue_search",
      name: "Search Issues",
      description: "Search Jira issues using JQL",
      connectorType: "jira",
      resource: "issue",
      category: "search",
      stakes: "low",
      reversible: false,
      batchSupport: false,
      inputs: [
        {
          id: "jql",
          name: "JQL Query",
          type: "string",
          required: true,
          description: "JQL search query",
        },
        {
          id: "max_results",
          name: "Max Results",
          type: "number",
          required: false,
          default: 20,
        },
      ],
      outputs: [
        { id: "issues", name: "Issues", type: "array" },
        { id: "total", name: "Total Count", type: "number" },
      ],
    },
  ],
};
