import type { ConnectorActionsRegistry } from "@openbeam/types/canvas";

export const linearActionsRegistry: ConnectorActionsRegistry = {
  connectorType: "linear",
  connectorName: "Linear",
  connectorIcon: "linear",
  actions: [
    {
      id: "issue_create",
      name: "Create Issue",
      description:
        "Create a new Linear issue. Requires teamId — call team_list first to discover team IDs.",
      connectorType: "linear",
      resource: "issue",
      category: "create",
      stakes: "medium",
      reversible: true,
      batchSupport: false,
      inputs: [
        {
          id: "title",
          name: "Title",
          type: "string",
          required: true,
          description: "Issue title",
        },
        {
          id: "description",
          name: "Description",
          type: "string",
          required: false,
          description: "Issue description (markdown)",
        },
        {
          id: "teamId",
          name: "Team ID",
          type: "string",
          required: true,
          description: "Team ID",
        },
        {
          id: "assigneeId",
          name: "Assignee ID",
          type: "string",
          required: false,
          description: "Assignee user ID",
        },
        {
          id: "priority",
          name: "Priority",
          type: "number",
          required: false,
          description: "Priority (0-4)",
        },
        {
          id: "stateId",
          name: "State ID",
          type: "string",
          required: false,
          description: "Workflow state ID",
        },
        {
          id: "labelIds",
          name: "Label IDs",
          type: "array",
          required: false,
          description: "Label IDs",
        },
        {
          id: "projectId",
          name: "Project ID",
          type: "string",
          required: false,
          description: "Project ID",
        },
        {
          id: "cycleId",
          name: "Cycle ID",
          type: "string",
          required: false,
          description: "Cycle ID",
        },
      ],
      outputs: [
        {
          id: "id",
          name: "Issue ID",
          type: "string",
          description: "Created issue ID",
        },
        {
          id: "identifier",
          name: "Identifier",
          type: "string",
          description: "Issue identifier (e.g., ENG-123)",
        },
        { id: "url", name: "URL", type: "string", description: "Issue URL" },
      ],
    },
    {
      id: "issue_update",
      name: "Update Issue",
      description: "Update an existing Linear issue",
      connectorType: "linear",
      resource: "issue",
      category: "update",
      stakes: "medium",
      reversible: true,
      batchSupport: false,
      inputs: [
        {
          id: "issueId",
          name: "Issue ID",
          type: "string",
          required: true,
          description: "Issue ID",
        },
        {
          id: "title",
          name: "Title",
          type: "string",
          required: false,
          description: "New title",
        },
        {
          id: "description",
          name: "Description",
          type: "string",
          required: false,
          description: "New description",
        },
        {
          id: "assigneeId",
          name: "Assignee ID",
          type: "string",
          required: false,
          description: "New assignee",
        },
        {
          id: "priority",
          name: "Priority",
          type: "number",
          required: false,
          description: "New priority",
        },
        {
          id: "stateId",
          name: "State ID",
          type: "string",
          required: false,
          description: "New state",
        },
      ],
      outputs: [
        {
          id: "id",
          name: "Issue ID",
          type: "string",
          description: "Updated issue ID",
        },
        {
          id: "success",
          name: "Success",
          type: "boolean",
          description: "Whether update succeeded",
        },
      ],
    },
    {
      id: "issue_search",
      name: "Search Issues",
      description: "Search for Linear issues",
      connectorType: "linear",
      resource: "issue",
      category: "search",
      stakes: "low",
      reversible: false,
      batchSupport: false,
      inputs: [
        {
          id: "query",
          name: "Query",
          type: "string",
          required: true,
          description: "Search query",
        },
        {
          id: "teamId",
          name: "Team ID",
          type: "string",
          required: false,
          description: "Filter by team",
        },
        {
          id: "first",
          name: "Limit",
          type: "number",
          required: false,
          description: "Max results",
        },
      ],
      outputs: [
        {
          id: "issues",
          name: "Issues",
          type: "array",
          description: "Matching issues",
        },
        {
          id: "totalCount",
          name: "Total Count",
          type: "number",
          description: "Total matches",
        },
      ],
    },
    {
      id: "issue_assign",
      name: "Assign Issue",
      description: "Assign an issue to a user",
      connectorType: "linear",
      resource: "issue",
      category: "update",
      stakes: "low",
      reversible: true,
      batchSupport: false,
      inputs: [
        {
          id: "issueId",
          name: "Issue ID",
          type: "string",
          required: true,
          description: "Issue ID",
        },
        {
          id: "assigneeId",
          name: "Assignee ID",
          type: "string",
          required: true,
          description: "User ID to assign",
        },
      ],
      outputs: [
        {
          id: "success",
          name: "Success",
          type: "boolean",
          description: "Whether assignment succeeded",
        },
      ],
    },
    {
      id: "issue_add_comment",
      name: "Add Comment",
      description: "Add a comment to an issue",
      connectorType: "linear",
      resource: "issue",
      category: "create",
      stakes: "low",
      reversible: false,
      batchSupport: false,
      inputs: [
        {
          id: "issueId",
          name: "Issue ID",
          type: "string",
          required: true,
          description: "Issue ID",
        },
        {
          id: "body",
          name: "Body",
          type: "string",
          required: true,
          description: "Comment body (markdown)",
        },
      ],
      outputs: [
        {
          id: "id",
          name: "Comment ID",
          type: "string",
          description: "Created comment ID",
        },
      ],
    },
    {
      id: "issue_add_label",
      name: "Add Label",
      description: "Add a label to an issue",
      connectorType: "linear",
      resource: "issue",
      category: "update",
      stakes: "low",
      reversible: true,
      batchSupport: false,
      inputs: [
        {
          id: "issueId",
          name: "Issue ID",
          type: "string",
          required: true,
          description: "Issue ID",
        },
        {
          id: "labelId",
          name: "Label ID",
          type: "string",
          required: true,
          description: "Label ID to add",
        },
      ],
      outputs: [
        {
          id: "success",
          name: "Success",
          type: "boolean",
          description: "Whether label was added",
        },
      ],
    },
    {
      id: "project_get",
      name: "Get Project",
      description: "Get project details",
      connectorType: "linear",
      resource: "project",
      category: "read",
      stakes: "low",
      reversible: false,
      batchSupport: false,
      inputs: [
        {
          id: "projectId",
          name: "Project ID",
          type: "string",
          required: true,
          description: "Project ID",
        },
      ],
      outputs: [
        {
          id: "project",
          name: "Project",
          type: "object",
          description: "Project data",
        },
      ],
    },
    {
      id: "project_create",
      name: "Create Project",
      description: "Create a new project",
      connectorType: "linear",
      resource: "project",
      category: "create",
      stakes: "medium",
      reversible: true,
      batchSupport: false,
      inputs: [
        {
          id: "name",
          name: "Name",
          type: "string",
          required: true,
          description: "Project name",
        },
        {
          id: "teamIds",
          name: "Team IDs",
          type: "array",
          required: true,
          description: "Team IDs",
        },
        {
          id: "description",
          name: "Description",
          type: "string",
          required: false,
          description: "Project description",
        },
        {
          id: "leadId",
          name: "Lead ID",
          type: "string",
          required: false,
          description: "Project lead user ID",
        },
        {
          id: "targetDate",
          name: "Target Date",
          type: "date",
          required: false,
          description: "Target completion date",
        },
      ],
      outputs: [
        {
          id: "id",
          name: "Project ID",
          type: "string",
          description: "Created project ID",
        },
        { id: "url", name: "URL", type: "string", description: "Project URL" },
      ],
    },
    {
      id: "cycle_get",
      name: "Get Cycle",
      description: "Get cycle details",
      connectorType: "linear",
      resource: "cycle",
      category: "read",
      stakes: "low",
      reversible: false,
      batchSupport: false,
      inputs: [
        {
          id: "cycleId",
          name: "Cycle ID",
          type: "string",
          required: true,
          description: "Cycle ID",
        },
      ],
      outputs: [
        {
          id: "cycle",
          name: "Cycle",
          type: "object",
          description: "Cycle data",
        },
      ],
    },
    {
      id: "cycle_add_issue",
      name: "Add Issue to Cycle",
      description: "Add an issue to a cycle",
      connectorType: "linear",
      resource: "cycle",
      category: "update",
      stakes: "low",
      reversible: true,
      batchSupport: false,
      inputs: [
        {
          id: "issueId",
          name: "Issue ID",
          type: "string",
          required: true,
          description: "Issue ID",
        },
        {
          id: "cycleId",
          name: "Cycle ID",
          type: "string",
          required: true,
          description: "Cycle ID",
        },
      ],
      outputs: [
        {
          id: "success",
          name: "Success",
          type: "boolean",
          description: "Whether issue was added",
        },
      ],
    },
    {
      id: "team_list",
      name: "List Teams",
      description:
        "List all teams in the Linear workspace. Use this to discover team IDs before creating issues.",
      connectorType: "linear",
      resource: "team",
      category: "list",
      stakes: "low",
      reversible: false,
      batchSupport: false,
      inputs: [],
      outputs: [
        {
          id: "teams",
          name: "Teams",
          type: "array",
          description: "Array of teams with id, name, and key",
        },
      ],
    },
  ],
};
