import type { ConnectorActionsRegistry } from "@openplane/types/canvas";

export const linearActions: ConnectorActionsRegistry = {
  connectorType: "linear",
  connectorName: "Linear",
  connectorIcon: "linear",
  actions: [
    {
      id: "issue_create",
      name: "Create Issue",
      description: "Create a new issue in a Linear team",
      connectorType: "linear",
      resource: "issue",
      category: "create",
      stakes: "medium",
      reversible: true,
      batchSupport: false,
      requiredScopes: ["write"],
      inputs: [
        {
          id: "teamId",
          name: "Team",
          type: "string",
          required: true,
          description: "Linear team ID",
          dynamic: true,
          resourceType: "team",
        },
        {
          id: "title",
          name: "Title",
          type: "string",
          required: true,
          description: "Issue title",
        },
        {
          id: "description",
          name: "Description",
          type: "markdown",
          required: false,
          description: "Issue description (markdown)",
        },
        {
          id: "priority",
          name: "Priority",
          type: "number",
          required: false,
          description: "Priority level",
          options: [
            { label: "Urgent", value: 1 },
            { label: "High", value: 2 },
            { label: "Medium", value: 3 },
            { label: "Low", value: 4 },
          ],
        },
        {
          id: "assigneeId",
          name: "Assignee",
          type: "string",
          required: false,
          description: "Assignee user ID",
        },
        {
          id: "labelIds",
          name: "Labels",
          type: "json",
          required: false,
          description: "Label IDs array",
        },
        {
          id: "stateId",
          name: "State",
          type: "string",
          required: false,
          description: "Workflow state ID",
        },
        {
          id: "projectId",
          name: "Project",
          type: "string",
          required: false,
          description: "Project ID",
          dynamic: true,
          resourceType: "project",
        },
        {
          id: "estimate",
          name: "Estimate",
          type: "number",
          required: false,
          description: "Story points estimate",
        },
      ],
      outputs: [
        {
          id: "id",
          name: "Issue ID",
          type: "string",
          description: "Created issue ID",
        },
        {
          id: "identifier",
          name: "Identifier",
          type: "string",
          description: "Issue identifier (e.g. ENG-123)",
        },
        { id: "url", name: "URL", type: "string", description: "Issue URL" },
      ],
    },
    {
      id: "issue_update",
      name: "Update Issue",
      description: "Update an existing issue's properties",
      connectorType: "linear",
      resource: "issue",
      category: "update",
      stakes: "medium",
      reversible: true,
      batchSupport: true,
      requiredScopes: ["write"],
      inputs: [
        {
          id: "issueId",
          name: "Issue ID",
          type: "string",
          required: true,
          description: "Issue to update",
        },
        {
          id: "title",
          name: "Title",
          type: "string",
          required: false,
          description: "New title",
        },
        {
          id: "description",
          name: "Description",
          type: "markdown",
          required: false,
          description: "New description",
        },
        {
          id: "stateId",
          name: "State",
          type: "string",
          required: false,
          description: "New workflow state ID",
        },
        {
          id: "priority",
          name: "Priority",
          type: "number",
          required: false,
          description: "New priority",
        },
        {
          id: "assigneeId",
          name: "Assignee",
          type: "string",
          required: false,
          description: "New assignee",
        },
      ],
      outputs: [
        {
          id: "id",
          name: "Issue ID",
          type: "string",
          description: "Updated issue ID",
        },
        {
          id: "identifier",
          name: "Identifier",
          type: "string",
          description: "Issue identifier",
        },
      ],
    },
    {
      id: "issue_search",
      name: "Search Issues",
      description: "Search for issues across teams",
      connectorType: "linear",
      resource: "issue",
      category: "search",
      stakes: "low",
      reversible: false,
      batchSupport: false,
      requiredScopes: ["read"],
      inputs: [
        {
          id: "query",
          name: "Query",
          type: "string",
          required: true,
          description: "Search query text",
        },
        {
          id: "teamId",
          name: "Team",
          type: "string",
          required: false,
          description: "Filter by team ID",
          dynamic: true,
          resourceType: "team",
        },
        {
          id: "assigneeId",
          name: "Assignee",
          type: "string",
          required: false,
          description: "Filter by assignee",
        },
        {
          id: "limit",
          name: "Limit",
          type: "number",
          required: false,
          description: "Max results",
          validation: { min: 1, max: 250 },
        },
      ],
      outputs: [
        {
          id: "issues",
          name: "Issues",
          type: "array",
          description: "Matching issues",
        },
        {
          id: "totalCount",
          name: "Total",
          type: "number",
          description: "Total matching issues",
        },
      ],
    },
    {
      id: "issue_assign",
      name: "Assign Issue",
      description: "Assign an issue to a user",
      connectorType: "linear",
      resource: "issue",
      category: "update",
      stakes: "low",
      reversible: true,
      batchSupport: true,
      requiredScopes: ["write"],
      inputs: [
        {
          id: "issueId",
          name: "Issue ID",
          type: "string",
          required: true,
          description: "Issue to assign",
        },
        {
          id: "assigneeId",
          name: "Assignee",
          type: "string",
          required: true,
          description: "User ID to assign",
        },
      ],
      outputs: [
        {
          id: "id",
          name: "Issue ID",
          type: "string",
          description: "Assigned issue ID",
        },
        {
          id: "assignee",
          name: "Assignee",
          type: "string",
          description: "Assignee name",
        },
      ],
    },
    {
      id: "issue_add_comment",
      name: "Add Comment",
      description: "Add a comment to an issue",
      connectorType: "linear",
      resource: "issue",
      category: "create",
      stakes: "low",
      reversible: false,
      batchSupport: false,
      requiredScopes: ["write"],
      inputs: [
        {
          id: "issueId",
          name: "Issue ID",
          type: "string",
          required: true,
          description: "Issue to comment on",
        },
        {
          id: "body",
          name: "Body",
          type: "markdown",
          required: true,
          description: "Comment body (markdown)",
        },
      ],
      outputs: [
        {
          id: "id",
          name: "Comment ID",
          type: "string",
          description: "Created comment ID",
        },
        { id: "url", name: "URL", type: "string", description: "Comment URL" },
      ],
    },
    {
      id: "issue_add_label",
      name: "Add Label",
      description: "Add a label to an issue",
      connectorType: "linear",
      resource: "issue",
      category: "update",
      stakes: "low",
      reversible: true,
      batchSupport: true,
      requiredScopes: ["write"],
      inputs: [
        {
          id: "issueId",
          name: "Issue ID",
          type: "string",
          required: true,
          description: "Issue to label",
        },
        {
          id: "labelId",
          name: "Label ID",
          type: "string",
          required: true,
          description: "Label to add",
        },
      ],
      outputs: [
        {
          id: "id",
          name: "Issue ID",
          type: "string",
          description: "Labeled issue ID",
        },
      ],
    },
    {
      id: "project_get",
      name: "Get Project",
      description: "Get project details",
      connectorType: "linear",
      resource: "project",
      category: "read",
      stakes: "low",
      reversible: false,
      batchSupport: false,
      requiredScopes: ["read"],
      inputs: [
        {
          id: "projectId",
          name: "Project ID",
          type: "string",
          required: true,
          description: "Linear project ID",
          dynamic: true,
          resourceType: "project",
        },
      ],
      outputs: [
        {
          id: "id",
          name: "Project ID",
          type: "string",
          description: "Project ID",
        },
        {
          id: "name",
          name: "Name",
          type: "string",
          description: "Project name",
        },
        {
          id: "state",
          name: "State",
          type: "string",
          description: "Project state",
        },
        {
          id: "progress",
          name: "Progress",
          type: "number",
          description: "Completion percentage",
        },
      ],
    },
    {
      id: "project_create",
      name: "Create Project",
      description: "Create a new Linear project",
      connectorType: "linear",
      resource: "project",
      category: "create",
      stakes: "medium",
      reversible: true,
      batchSupport: false,
      requiredScopes: ["write"],
      inputs: [
        {
          id: "name",
          name: "Name",
          type: "string",
          required: true,
          description: "Project name",
        },
        {
          id: "teamIds",
          name: "Teams",
          type: "json",
          required: true,
          description: "Team IDs array",
        },
        {
          id: "description",
          name: "Description",
          type: "markdown",
          required: false,
          description: "Project description",
        },
        {
          id: "targetDate",
          name: "Target Date",
          type: "date",
          required: false,
          description: "Target completion date",
        },
      ],
      outputs: [
        {
          id: "id",
          name: "Project ID",
          type: "string",
          description: "Created project ID",
        },
        { id: "url", name: "URL", type: "string", description: "Project URL" },
      ],
    },
    {
      id: "cycle_get",
      name: "Get Cycle",
      description: "Get current or specific cycle details",
      connectorType: "linear",
      resource: "cycle",
      category: "read",
      stakes: "low",
      reversible: false,
      batchSupport: false,
      requiredScopes: ["read"],
      inputs: [
        {
          id: "cycleId",
          name: "Cycle ID",
          type: "string",
          required: false,
          description: "Specific cycle ID (omit for current)",
        },
        {
          id: "teamId",
          name: "Team",
          type: "string",
          required: true,
          description: "Team ID",
          dynamic: true,
          resourceType: "team",
        },
      ],
      outputs: [
        { id: "id", name: "Cycle ID", type: "string", description: "Cycle ID" },
        { id: "name", name: "Name", type: "string", description: "Cycle name" },
        {
          id: "startsAt",
          name: "Start Date",
          type: "string",
          description: "Cycle start date",
        },
        {
          id: "endsAt",
          name: "End Date",
          type: "string",
          description: "Cycle end date",
        },
        {
          id: "progress",
          name: "Progress",
          type: "number",
          description: "Completion percentage",
        },
      ],
    },
    {
      id: "cycle_add_issue",
      name: "Add to Cycle",
      description: "Add an issue to a cycle",
      connectorType: "linear",
      resource: "cycle",
      category: "update",
      stakes: "low",
      reversible: true,
      batchSupport: true,
      requiredScopes: ["write"],
      inputs: [
        {
          id: "cycleId",
          name: "Cycle ID",
          type: "string",
          required: true,
          description: "Target cycle",
        },
        {
          id: "issueId",
          name: "Issue ID",
          type: "string",
          required: true,
          description: "Issue to add",
        },
      ],
      outputs: [
        {
          id: "id",
          name: "Issue ID",
          type: "string",
          description: "Added issue ID",
        },
      ],
    },
  ],
};
