import type { ConnectorActionsRegistry } from "@openbeam/types/connector-actions";

export const lumappsActionsRegistry: ConnectorActionsRegistry = {
  connectorType: "lumapps",
  connectorName: "LumApps",
  connectorIcon: "lumapps",
  actions: [
    {
      id: "content_create",
      name: "Create Content",
      description:
        "Create a new content page in LumApps. Requires customer and instance IDs from connector config.",
      connectorType: "lumapps",
      resource: "content",
      category: "create",
      stakes: "medium",
      reversible: false,
      batchSupport: false,
      idempotent: false,
      inputs: [
        { id: "title", name: "Title", type: "string", required: true },
        {
          id: "language",
          name: "Language",
          type: "string",
          required: false,
          description: "Language code for content (defaults to 'en')",
        },
        {
          id: "slug",
          name: "Slug",
          type: "string",
          required: false,
          description: "URL slug (auto-generated from title if omitted)",
        },
        {
          id: "type",
          name: "Content Type",
          type: "string",
          required: false,
          description: "Content type: page, article (defaults to 'page')",
        },
        {
          id: "customContentTypeId",
          name: "Custom Content Type ID",
          type: "string",
          required: false,
        },
        { id: "body", name: "Body HTML", type: "html", required: false },
        {
          id: "feedKeys",
          name: "Feed Keys",
          type: "array",
          required: false,
          description: "Visibility feed keys",
        },
        {
          id: "status",
          name: "Status",
          type: "string",
          required: false,
          description: "Publication status (e.g. LIVE, DRAFT)",
        },
      ],
      outputs: [
        { id: "id", name: "Content ID", type: "string" },
        { id: "url", name: "Content URL", type: "string" },
      ],
    },
    {
      id: "content_update",
      name: "Update Content",
      description: "Update existing content in LumApps by content ID",
      connectorType: "lumapps",
      resource: "content",
      category: "update",
      stakes: "low",
      reversible: true,
      batchSupport: false,
      idempotent: false,
      inputs: [
        { id: "contentId", name: "Content ID", type: "string", required: true },
        { id: "title", name: "Title", type: "string", required: false },
        {
          id: "language",
          name: "Language",
          type: "string",
          required: false,
          description: "Language code (defaults to 'en')",
        },
        { id: "body", name: "Body HTML", type: "html", required: false },
        { id: "slug", name: "Slug", type: "string", required: false },
        {
          id: "status",
          name: "Status",
          type: "string",
          required: false,
          description: "Publication status (e.g. LIVE, DRAFT)",
        },
      ],
      outputs: [
        { id: "id", name: "Content ID", type: "string" },
        { id: "url", name: "Content URL", type: "string" },
      ],
    },
    {
      id: "post_create",
      name: "Create Community Post",
      description:
        "Create a post in a LumApps community. Requires customer and instance IDs from connector config.",
      connectorType: "lumapps",
      resource: "post",
      category: "create",
      stakes: "low",
      reversible: false,
      batchSupport: false,
      idempotent: false,
      inputs: [
        {
          id: "communityId",
          name: "Community ID",
          type: "string",
          required: true,
          description: "The community externalKey / ID to post into",
        },
        {
          id: "title",
          name: "Title",
          type: "string",
          required: false,
          description: "Post title (optional for DEFAULT posts)",
        },
        {
          id: "content",
          name: "Content",
          type: "string",
          required: true,
          description: "Post body (supports markdown)",
        },
        {
          id: "postType",
          name: "Post Type",
          type: "string",
          required: false,
          description: "DEFAULT, IDEA, or QUESTION (defaults to DEFAULT)",
        },
        {
          id: "language",
          name: "Language",
          type: "string",
          required: false,
          description: "Language code (defaults to 'en')",
        },
      ],
      outputs: [
        { id: "id", name: "Post ID", type: "string" },
        { id: "url", name: "Post URL", type: "string" },
      ],
    },
  ],
};
