import type { ConnectorActionsRegistry } from "@openbeam/types/connector-actions";

export const miroActionsRegistry: ConnectorActionsRegistry = {
  connectorType: "miro",
  connectorName: "Miro",
  connectorIcon: "miro",
  actions: [
    {
      id: "board_list",
      name: "List Boards",
      description:
        "List all Miro boards accessible to the connected account. Use this first to discover board IDs before calling sticky_note_create or other board actions.",
      connectorType: "miro",
      resource: "board",
      category: "list",
      stakes: "low",
      reversible: true,
      batchSupport: false,
      idempotent: true,
      inputs: [],
      outputs: [
        {
          id: "boards",
          name: "Boards",
          type: "object",
          description: "Array of boards with id, name, and viewLink",
        },
      ],
    },
    {
      id: "board_create",
      name: "Create Board",
      description: "Create a new Miro board",
      connectorType: "miro",
      resource: "board",
      category: "create",
      stakes: "medium",
      reversible: false,
      batchSupport: false,
      idempotent: false,
      inputs: [
        {
          id: "name",
          name: "Name",
          type: "string",
          required: true,
          description: "Board name",
        },
        {
          id: "description",
          name: "Description",
          type: "string",
          required: false,
          description: "Board description",
        },
      ],
      outputs: [
        { id: "recordId", name: "Board ID", type: "string" },
        { id: "url", name: "Board URL", type: "string" },
      ],
    },
    {
      id: "sticky_note_create",
      name: "Create Sticky Note",
      description:
        "Create a sticky note on a Miro board. Requires board_id — call board_list first to discover board IDs.",
      connectorType: "miro",
      resource: "sticky_note",
      category: "create",
      stakes: "low",
      reversible: true,
      batchSupport: false,
      idempotent: false,
      inputs: [
        {
          id: "board_id",
          name: "Board ID",
          type: "string",
          required: true,
          description: "ID of the board to add the sticky note to",
        },
        {
          id: "content",
          name: "Content",
          type: "string",
          required: true,
          description: "Sticky note text content (supports HTML)",
        },
        {
          id: "shape",
          name: "Shape",
          type: "string",
          required: false,
          description: "Sticky note shape (square or rectangle)",
        },
        {
          id: "x",
          name: "X Position",
          type: "number",
          required: false,
          description: "Horizontal position on the board",
        },
        {
          id: "y",
          name: "Y Position",
          type: "number",
          required: false,
          description: "Vertical position on the board",
        },
      ],
      outputs: [
        { id: "recordId", name: "Item ID", type: "string" },
        { id: "url", name: "Board URL", type: "string" },
      ],
    },
    {
      id: "sticky_note_update",
      name: "Update Sticky Note",
      description:
        "Update a sticky note on a Miro board. Requires board_id — call board_list first to discover board IDs.",
      connectorType: "miro",
      resource: "sticky_note",
      category: "update",
      stakes: "low",
      reversible: true,
      batchSupport: false,
      idempotent: true,
      inputs: [
        {
          id: "board_id",
          name: "Board ID",
          type: "string",
          required: true,
          description: "ID of the board containing the sticky note",
        },
        {
          id: "item_id",
          name: "Item ID",
          type: "string",
          required: true,
          description: "ID of the sticky note to update",
        },
        {
          id: "content",
          name: "Content",
          type: "string",
          required: false,
          description: "Updated text content",
        },
        {
          id: "shape",
          name: "Shape",
          type: "string",
          required: false,
          description: "Updated shape (square or rectangle)",
        },
      ],
      outputs: [
        { id: "recordId", name: "Item ID", type: "string" },
        { id: "url", name: "Board URL", type: "string" },
      ],
    },
    {
      id: "item_delete",
      name: "Delete Item",
      description:
        "Delete an item from a Miro board. Requires board_id — call board_list first to discover board IDs.",
      connectorType: "miro",
      resource: "item",
      category: "delete",
      stakes: "high",
      reversible: false,
      batchSupport: false,
      idempotent: true,
      inputs: [
        {
          id: "board_id",
          name: "Board ID",
          type: "string",
          required: true,
          description: "ID of the board containing the item",
        },
        {
          id: "item_id",
          name: "Item ID",
          type: "string",
          required: true,
          description: "ID of the item to delete",
        },
      ],
      outputs: [{ id: "recordId", name: "Item ID", type: "string" }],
    },
  ],
};
