import type { ConnectorActionsRegistry } from "@openplane/types/canvas";

export const notionActionsRegistry: ConnectorActionsRegistry = {
  connectorType: "notion",
  connectorName: "Notion",
  connectorIcon: "notion",
  actions: [
    {
      id: "page_create",
      name: "Create Page",
      description: "Create a new Notion page",
      connectorType: "notion",
      resource: "page",
      category: "create",
      stakes: "medium",
      reversible: true,
      batchSupport: false,
      inputs: [
        {
          id: "parentId",
          name: "Parent ID",
          type: "string",
          required: true,
          description: "Parent page or database ID",
        },
        {
          id: "title",
          name: "Title",
          type: "string",
          required: true,
          description: "Page title",
        },
        {
          id: "content",
          name: "Content",
          type: "string",
          required: false,
          description: "Initial page content",
        },
        {
          id: "properties",
          name: "Properties",
          type: "object",
          required: false,
          description: "Database properties",
        },
        {
          id: "icon",
          name: "Icon",
          type: "string",
          required: false,
          description: "Page icon (emoji or URL)",
        },
        {
          id: "cover",
          name: "Cover",
          type: "string",
          required: false,
          description: "Cover image URL",
        },
      ],
      outputs: [
        {
          id: "id",
          name: "Page ID",
          type: "string",
          description: "Created page ID",
        },
        { id: "url", name: "URL", type: "string", description: "Page URL" },
      ],
    },
    {
      id: "page_get",
      name: "Get Page",
      description: "Retrieve a Notion page",
      connectorType: "notion",
      resource: "page",
      category: "read",
      stakes: "low",
      reversible: false,
      batchSupport: false,
      inputs: [
        {
          id: "pageId",
          name: "Page ID",
          type: "string",
          required: true,
          description: "Page ID",
        },
      ],
      outputs: [
        { id: "page", name: "Page", type: "object", description: "Page data" },
      ],
    },
    {
      id: "page_update",
      name: "Update Page",
      description: "Update a Notion page properties",
      connectorType: "notion",
      resource: "page",
      category: "update",
      stakes: "medium",
      reversible: true,
      batchSupport: false,
      inputs: [
        {
          id: "pageId",
          name: "Page ID",
          type: "string",
          required: true,
          description: "Page ID",
        },
        {
          id: "properties",
          name: "Properties",
          type: "object",
          required: false,
          description: "Properties to update",
        },
        {
          id: "icon",
          name: "Icon",
          type: "string",
          required: false,
          description: "New icon",
        },
        {
          id: "cover",
          name: "Cover",
          type: "string",
          required: false,
          description: "New cover URL",
        },
      ],
      outputs: [
        {
          id: "id",
          name: "Page ID",
          type: "string",
          description: "Updated page ID",
        },
      ],
    },
    {
      id: "page_archive",
      name: "Archive Page",
      description: "Archive a Notion page",
      connectorType: "notion",
      resource: "page",
      category: "delete",
      stakes: "medium",
      reversible: true,
      batchSupport: false,
      inputs: [
        {
          id: "pageId",
          name: "Page ID",
          type: "string",
          required: true,
          description: "Page to archive",
        },
      ],
      outputs: [
        {
          id: "id",
          name: "Page ID",
          type: "string",
          description: "Archived page ID",
        },
      ],
    },
    {
      id: "database_query",
      name: "Query Database",
      description: "Query a Notion database",
      connectorType: "notion",
      resource: "database",
      category: "search",
      stakes: "low",
      reversible: false,
      batchSupport: false,
      inputs: [
        {
          id: "databaseId",
          name: "Database ID",
          type: "string",
          required: true,
          description: "Database ID",
        },
        {
          id: "filter",
          name: "Filter",
          type: "object",
          required: false,
          description: "Query filter",
        },
        {
          id: "sorts",
          name: "Sorts",
          type: "array",
          required: false,
          description: "Sort conditions",
        },
        {
          id: "pageSize",
          name: "Page Size",
          type: "number",
          required: false,
          description: "Results per page",
        },
      ],
      outputs: [
        {
          id: "results",
          name: "Results",
          type: "array",
          description: "Query results",
        },
        {
          id: "hasMore",
          name: "Has More",
          type: "boolean",
          description: "More results available",
        },
      ],
    },
    {
      id: "database_create",
      name: "Create Database",
      description: "Create a new Notion database",
      connectorType: "notion",
      resource: "database",
      category: "create",
      stakes: "medium",
      reversible: true,
      batchSupport: false,
      inputs: [
        {
          id: "parentId",
          name: "Parent ID",
          type: "string",
          required: true,
          description: "Parent page ID",
        },
        {
          id: "title",
          name: "Title",
          type: "string",
          required: true,
          description: "Database title",
        },
        {
          id: "properties",
          name: "Properties",
          type: "object",
          required: false,
          description: "Database schema",
        },
      ],
      outputs: [
        {
          id: "id",
          name: "Database ID",
          type: "string",
          description: "Created database ID",
        },
        { id: "url", name: "URL", type: "string", description: "Database URL" },
      ],
    },
    {
      id: "block_append",
      name: "Append Block",
      description: "Append content blocks to a page",
      connectorType: "notion",
      resource: "block",
      category: "create",
      stakes: "low",
      reversible: true,
      batchSupport: true,
      inputs: [
        {
          id: "blockId",
          name: "Block ID",
          type: "string",
          required: true,
          description: "Parent block ID",
        },
        {
          id: "children",
          name: "Children",
          type: "array",
          required: true,
          description: "Blocks to append",
        },
      ],
      outputs: [
        {
          id: "results",
          name: "Results",
          type: "array",
          description: "Created blocks",
        },
      ],
    },
    {
      id: "block_delete",
      name: "Delete Block",
      description: "Delete a block",
      connectorType: "notion",
      resource: "block",
      category: "delete",
      stakes: "medium",
      reversible: false,
      batchSupport: false,
      inputs: [
        {
          id: "blockId",
          name: "Block ID",
          type: "string",
          required: true,
          description: "Block to delete",
        },
      ],
      outputs: [
        {
          id: "id",
          name: "Block ID",
          type: "string",
          description: "Deleted block ID",
        },
      ],
    },
    {
      id: "search",
      name: "Search",
      description: "Search Notion workspace",
      connectorType: "notion",
      resource: "workspace",
      category: "search",
      stakes: "low",
      reversible: false,
      batchSupport: false,
      inputs: [
        {
          id: "query",
          name: "Query",
          type: "string",
          required: true,
          description: "Search query",
        },
        {
          id: "filter",
          name: "Filter",
          type: "object",
          required: false,
          description: "Search filter",
        },
        {
          id: "pageSize",
          name: "Page Size",
          type: "number",
          required: false,
          description: "Results per page",
        },
      ],
      outputs: [
        {
          id: "results",
          name: "Results",
          type: "array",
          description: "Search results",
        },
        {
          id: "hasMore",
          name: "Has More",
          type: "boolean",
          description: "More results available",
        },
      ],
    },
    {
      id: "comment_create",
      name: "Add Comment",
      description: "Add a comment to a page",
      connectorType: "notion",
      resource: "comment",
      category: "create",
      stakes: "low",
      reversible: false,
      batchSupport: false,
      inputs: [
        {
          id: "pageId",
          name: "Page ID",
          type: "string",
          required: true,
          description: "Page ID",
        },
        {
          id: "text",
          name: "Text",
          type: "string",
          required: true,
          description: "Comment text",
        },
      ],
      outputs: [
        {
          id: "id",
          name: "Comment ID",
          type: "string",
          description: "Created comment ID",
        },
      ],
    },
  ],
};
