import type { ConnectorActionsRegistry } from "@openplane/types/canvas";

export const notionActions: ConnectorActionsRegistry = {
  connectorType: "notion",
  connectorName: "Notion",
  connectorIcon: "notion",
  actions: [
    {
      id: "page_create",
      name: "Create Page",
      description: "Create a new page in a database or as a child page",
      connectorType: "notion",
      resource: "page",
      category: "create",
      stakes: "medium",
      reversible: true,
      batchSupport: false,
      requiredScopes: [],
      inputs: [
        {
          id: "parentId",
          name: "Parent",
          type: "string",
          required: true,
          description: "Parent page or database ID",
          dynamic: true,
          resourceType: "database",
        },
        {
          id: "title",
          name: "Title",
          type: "string",
          required: true,
          description: "Page title",
        },
        {
          id: "properties",
          name: "Properties",
          type: "json",
          required: false,
          description: "Database properties as JSON",
        },
        {
          id: "content",
          name: "Content",
          type: "markdown",
          required: false,
          description: "Page content in markdown",
        },
      ],
      outputs: [
        {
          id: "id",
          name: "Page ID",
          type: "string",
          description: "Created page ID",
        },
        { id: "url", name: "URL", type: "string", description: "Page URL" },
      ],
    },
    {
      id: "page_get",
      name: "Get Page",
      description: "Retrieve a page and its properties",
      connectorType: "notion",
      resource: "page",
      category: "read",
      stakes: "low",
      reversible: false,
      batchSupport: true,
      requiredScopes: [],
      inputs: [
        {
          id: "pageId",
          name: "Page ID",
          type: "string",
          required: true,
          description: "Notion page ID",
        },
      ],
      outputs: [
        { id: "id", name: "Page ID", type: "string", description: "Page ID" },
        { id: "url", name: "URL", type: "string", description: "Page URL" },
        {
          id: "properties",
          name: "Properties",
          type: "object",
          description: "Page properties",
        },
        {
          id: "title",
          name: "Title",
          type: "string",
          description: "Page title",
        },
      ],
    },
    {
      id: "page_update",
      name: "Update Page",
      description: "Update page properties",
      connectorType: "notion",
      resource: "page",
      category: "update",
      stakes: "medium",
      reversible: true,
      batchSupport: true,
      requiredScopes: [],
      inputs: [
        {
          id: "pageId",
          name: "Page ID",
          type: "string",
          required: true,
          description: "Page to update",
        },
        {
          id: "properties",
          name: "Properties",
          type: "json",
          required: true,
          description: "Properties to update as JSON",
        },
      ],
      outputs: [
        {
          id: "id",
          name: "Page ID",
          type: "string",
          description: "Updated page ID",
        },
        { id: "url", name: "URL", type: "string", description: "Page URL" },
      ],
    },
    {
      id: "page_archive",
      name: "Archive Page",
      description: "Archive (soft-delete) a Notion page",
      connectorType: "notion",
      resource: "page",
      category: "delete",
      stakes: "medium",
      reversible: true,
      batchSupport: true,
      requiredScopes: [],
      inputs: [
        {
          id: "pageId",
          name: "Page ID",
          type: "string",
          required: true,
          description: "Page to archive",
        },
      ],
      outputs: [
        {
          id: "id",
          name: "Page ID",
          type: "string",
          description: "Archived page ID",
        },
      ],
    },
    {
      id: "database_query",
      name: "Query Database",
      description: "Query a Notion database with filters and sorts",
      connectorType: "notion",
      resource: "database",
      category: "search",
      stakes: "low",
      reversible: false,
      batchSupport: false,
      requiredScopes: [],
      inputs: [
        {
          id: "databaseId",
          name: "Database ID",
          type: "string",
          required: true,
          description: "Notion database ID",
          dynamic: true,
          resourceType: "database",
        },
        {
          id: "filter",
          name: "Filter",
          type: "json",
          required: false,
          description: "Notion filter object as JSON",
        },
        {
          id: "sorts",
          name: "Sorts",
          type: "json",
          required: false,
          description: "Sort configuration as JSON",
        },
        {
          id: "pageSize",
          name: "Page Size",
          type: "number",
          required: false,
          description: "Results per page",
          validation: { min: 1, max: 100 },
        },
      ],
      outputs: [
        {
          id: "results",
          name: "Results",
          type: "array",
          description: "Matching pages",
        },
        {
          id: "hasMore",
          name: "Has More",
          type: "boolean",
          description: "More results available",
        },
        {
          id: "nextCursor",
          name: "Next Cursor",
          type: "string",
          description: "Pagination cursor",
        },
      ],
    },
    {
      id: "database_create",
      name: "Create Database",
      description: "Create a new inline database in a page",
      connectorType: "notion",
      resource: "database",
      category: "create",
      stakes: "medium",
      reversible: true,
      batchSupport: false,
      requiredScopes: [],
      inputs: [
        {
          id: "parentId",
          name: "Parent Page",
          type: "string",
          required: true,
          description: "Parent page ID",
          dynamic: true,
          resourceType: "page",
        },
        {
          id: "title",
          name: "Title",
          type: "string",
          required: true,
          description: "Database title",
        },
        {
          id: "properties",
          name: "Properties",
          type: "json",
          required: true,
          description: "Database schema (properties definition)",
        },
      ],
      outputs: [
        {
          id: "id",
          name: "Database ID",
          type: "string",
          description: "Created database ID",
        },
        { id: "url", name: "URL", type: "string", description: "Database URL" },
      ],
    },
    {
      id: "block_append",
      name: "Append Content",
      description: "Append block content to a page",
      connectorType: "notion",
      resource: "block",
      category: "create",
      stakes: "low",
      reversible: true,
      batchSupport: false,
      requiredScopes: [],
      inputs: [
        {
          id: "pageId",
          name: "Page ID",
          type: "string",
          required: true,
          description: "Page to append to",
        },
        {
          id: "content",
          name: "Content",
          type: "markdown",
          required: true,
          description: "Content to append (markdown)",
        },
      ],
      outputs: [
        {
          id: "results",
          name: "Blocks",
          type: "array",
          description: "Created block objects",
        },
      ],
    },
    {
      id: "block_delete",
      name: "Delete Block",
      description: "Delete a content block from a page",
      connectorType: "notion",
      resource: "block",
      category: "delete",
      stakes: "medium",
      reversible: false,
      batchSupport: true,
      requiredScopes: [],
      inputs: [
        {
          id: "blockId",
          name: "Block ID",
          type: "string",
          required: true,
          description: "Block to delete",
        },
      ],
      outputs: [
        {
          id: "id",
          name: "Block ID",
          type: "string",
          description: "Deleted block ID",
        },
      ],
    },
    {
      id: "search",
      name: "Search",
      description: "Search across all pages and databases",
      connectorType: "notion",
      resource: "search",
      category: "search",
      stakes: "low",
      reversible: false,
      batchSupport: false,
      requiredScopes: [],
      inputs: [
        {
          id: "query",
          name: "Query",
          type: "string",
          required: true,
          description: "Search query text",
        },
        {
          id: "filter",
          name: "Filter",
          type: "string",
          required: false,
          description: "Object type filter",
          options: [
            { label: "Pages Only", value: "page" },
            { label: "Databases Only", value: "database" },
          ],
        },
        {
          id: "pageSize",
          name: "Page Size",
          type: "number",
          required: false,
          description: "Results per page",
          validation: { min: 1, max: 100 },
        },
      ],
      outputs: [
        {
          id: "results",
          name: "Results",
          type: "array",
          description: "Matching pages and databases",
        },
        {
          id: "hasMore",
          name: "Has More",
          type: "boolean",
          description: "More results available",
        },
      ],
    },
    {
      id: "comment_create",
      name: "Add Comment",
      description: "Add a comment to a page or discussion",
      connectorType: "notion",
      resource: "comment",
      category: "create",
      stakes: "low",
      reversible: false,
      batchSupport: false,
      requiredScopes: [],
      inputs: [
        {
          id: "pageId",
          name: "Page ID",
          type: "string",
          required: true,
          description: "Page to comment on",
        },
        {
          id: "text",
          name: "Text",
          type: "string",
          required: true,
          description: "Comment text",
        },
      ],
      outputs: [
        {
          id: "id",
          name: "Comment ID",
          type: "string",
          description: "Created comment ID",
        },
      ],
    },
  ],
};
