import type { ConnectorActionsRegistry } from "@openbeam/types/connector-actions";

export const opsgenieActionsRegistry: ConnectorActionsRegistry = {
  connectorType: "opsgenie",
  connectorName: "OpsGenie",
  connectorIcon: "opsgenie",
  actions: [
    {
      id: "alert_create",
      name: "Create Alert",
      description: "Create a new alert in OpsGenie",
      connectorType: "opsgenie",
      resource: "alert",
      category: "create",
      stakes: "medium",
      reversible: true,
      batchSupport: false,
      inputs: [
        {
          id: "message",
          name: "Message",
          type: "string",
          required: true,
          description: "Alert message (max 130 characters)",
        },
        {
          id: "description",
          name: "Description",
          type: "string",
          required: false,
          description: "Detailed description of the alert",
        },
        {
          id: "priority",
          name: "Priority",
          type: "string",
          required: false,
          description: "Alert priority: P1, P2, P3, P4, or P5",
        },
        {
          id: "tags",
          name: "Tags",
          type: "string",
          required: false,
          description: "Comma-separated list of tags",
        },
      ],
      outputs: [{ id: "requestId", name: "Request ID", type: "string" }],
    },
    {
      id: "alert_acknowledge",
      name: "Acknowledge Alert",
      description: "Acknowledge a triggered alert",
      connectorType: "opsgenie",
      resource: "alert",
      category: "update",
      stakes: "low",
      reversible: false,
      batchSupport: false,
      inputs: [
        {
          id: "alert_id",
          name: "Alert ID",
          type: "string",
          required: true,
          description: "ID of the alert to acknowledge",
        },
        {
          id: "note",
          name: "Note",
          type: "string",
          required: false,
          description: "Optional note for the acknowledgement",
        },
      ],
      outputs: [{ id: "alertId", name: "Alert ID", type: "string" }],
    },
    {
      id: "alert_close",
      name: "Close Alert",
      description: "Close an active alert",
      connectorType: "opsgenie",
      resource: "alert",
      category: "update",
      stakes: "medium",
      reversible: false,
      batchSupport: false,
      inputs: [
        {
          id: "alert_id",
          name: "Alert ID",
          type: "string",
          required: true,
          description: "ID of the alert to close",
        },
        {
          id: "note",
          name: "Note",
          type: "string",
          required: false,
          description: "Optional note for closing",
        },
      ],
      outputs: [{ id: "alertId", name: "Alert ID", type: "string" }],
    },
    {
      id: "alert_add_note",
      name: "Add Note to Alert",
      description: "Add a note to an existing alert",
      connectorType: "opsgenie",
      resource: "alert",
      category: "create",
      stakes: "low",
      reversible: false,
      batchSupport: false,
      inputs: [
        {
          id: "alert_id",
          name: "Alert ID",
          type: "string",
          required: true,
          description: "ID of the alert",
        },
        {
          id: "note",
          name: "Note",
          type: "string",
          required: true,
          description: "Note content",
        },
      ],
      outputs: [{ id: "alertId", name: "Alert ID", type: "string" }],
    },
    {
      id: "incident_create",
      name: "Create Incident",
      description: "Create a new incident in OpsGenie",
      connectorType: "opsgenie",
      resource: "incident",
      category: "create",
      stakes: "high",
      reversible: true,
      batchSupport: false,
      inputs: [
        {
          id: "message",
          name: "Message",
          type: "string",
          required: true,
          description: "Incident message",
        },
        {
          id: "description",
          name: "Description",
          type: "string",
          required: false,
          description: "Incident description",
        },
        {
          id: "priority",
          name: "Priority",
          type: "string",
          required: true,
          description: "Incident priority: P1, P2, P3, P4, or P5",
        },
        {
          id: "service_id",
          name: "Impacted Service ID",
          type: "string",
          required: false,
          description: "ID of the impacted service",
        },
        {
          id: "tags",
          name: "Tags",
          type: "string",
          required: false,
          description: "Comma-separated list of tags",
        },
      ],
      outputs: [{ id: "requestId", name: "Request ID", type: "string" }],
    },
    {
      id: "incident_resolve",
      name: "Resolve Incident",
      description: "Resolve an active incident",
      connectorType: "opsgenie",
      resource: "incident",
      category: "update",
      stakes: "medium",
      reversible: false,
      batchSupport: false,
      inputs: [
        {
          id: "incident_id",
          name: "Incident ID",
          type: "string",
          required: true,
          description: "ID of the incident to resolve",
        },
        {
          id: "note",
          name: "Note",
          type: "string",
          required: false,
          description: "Optional resolution note",
        },
      ],
      outputs: [{ id: "incidentId", name: "Incident ID", type: "string" }],
    },
  ],
};
