import type { ConnectorActionsRegistry } from "@openbeam/types/canvas";

export const outlookActionsRegistry: ConnectorActionsRegistry = {
  connectorType: "outlook",
  connectorName: "Microsoft Outlook",
  connectorIcon: "outlook",
  actions: [
    {
      id: "email_send",
      name: "Send Email",
      description: "Send an email via Outlook",
      connectorType: "outlook",
      resource: "email",
      category: "create",
      stakes: "medium",
      reversible: false,
      batchSupport: false,
      inputs: [
        {
          id: "to",
          name: "To",
          type: "array",
          required: true,
          description: "Recipient email addresses",
        },
        { id: "subject", name: "Subject", type: "string", required: true },
        { id: "body", name: "Body", type: "string", required: true },
        { id: "cc", name: "CC", type: "array", required: false },
        { id: "bcc", name: "BCC", type: "array", required: false },
        {
          id: "is_html",
          name: "HTML Body",
          type: "boolean",
          required: false,
          default: false,
        },
      ],
      outputs: [{ id: "messageId", name: "Message ID", type: "string" }],
    },
    {
      id: "email_reply",
      name: "Reply to Email",
      description: "Reply to an existing email thread",
      connectorType: "outlook",
      resource: "email",
      category: "create",
      stakes: "medium",
      reversible: false,
      batchSupport: false,
      inputs: [
        {
          id: "message_id",
          name: "Message ID",
          type: "string",
          required: true,
        },
        { id: "body", name: "Reply Body", type: "string", required: true },
        {
          id: "reply_all",
          name: "Reply All",
          type: "boolean",
          required: false,
          default: false,
        },
      ],
      outputs: [{ id: "messageId", name: "Message ID", type: "string" }],
    },
    {
      id: "email_move",
      name: "Move Email",
      description:
        "Move an email to a different folder. Use folder_list first to discover the destination_folder_id.",
      connectorType: "outlook",
      resource: "email",
      category: "update",
      stakes: "low",
      reversible: true,
      batchSupport: false,
      inputs: [
        {
          id: "message_id",
          name: "Message ID",
          type: "string",
          required: true,
        },
        {
          id: "destination_folder_id",
          name: "Destination Folder ID",
          type: "string",
          required: true,
          description:
            "ID of the target folder. Use folder_list to discover available folders.",
        },
      ],
      outputs: [{ id: "messageId", name: "Message ID", type: "string" }],
    },
    {
      id: "folder_list",
      name: "List Mail Folders",
      description:
        "List all mail folders in the user's mailbox. Use this to discover folder IDs before calling email_move.",
      connectorType: "outlook",
      resource: "folder",
      category: "read",
      stakes: "low",
      reversible: true,
      batchSupport: false,
      inputs: [],
      outputs: [{ id: "folders", name: "Folders", type: "array" }],
    },
  ],
};
