import type { ConnectorActionsRegistry } from "@openbeam/types/canvas";

export const pagerdutyActionsRegistry: ConnectorActionsRegistry = {
  connectorType: "pagerduty",
  connectorName: "PagerDuty",
  connectorIcon: "pagerduty",
  actions: [
    {
      id: "incident_create",
      name: "Create Incident",
      description: "Create a new PagerDuty incident",
      connectorType: "pagerduty",
      resource: "incident",
      category: "create",
      stakes: "medium",
      reversible: true,
      batchSupport: false,
      inputs: [
        {
          id: "service_id",
          name: "Service ID",
          type: "string",
          required: true,
        },
        { id: "title", name: "Title", type: "string", required: true },
        { id: "body", name: "Description", type: "string", required: false },
        {
          id: "urgency",
          name: "Urgency",
          type: "string",
          required: false,
        },
        {
          id: "from_email",
          name: "From Email",
          type: "string",
          required: true,
        },
      ],
      outputs: [
        { id: "incidentId", name: "Incident ID", type: "string" },
        { id: "url", name: "Incident URL", type: "string" },
      ],
    },
    {
      id: "incident_acknowledge",
      name: "Acknowledge Incident",
      description: "Acknowledge a triggered incident",
      connectorType: "pagerduty",
      resource: "incident",
      category: "update",
      stakes: "low",
      reversible: false,
      batchSupport: false,
      inputs: [
        {
          id: "incident_id",
          name: "Incident ID",
          type: "string",
          required: true,
        },
        {
          id: "from_email",
          name: "From Email",
          type: "string",
          required: true,
        },
      ],
      outputs: [{ id: "incidentId", name: "Incident ID", type: "string" }],
    },
    {
      id: "incident_resolve",
      name: "Resolve Incident",
      description: "Resolve an active incident",
      connectorType: "pagerduty",
      resource: "incident",
      category: "update",
      stakes: "medium",
      reversible: false,
      batchSupport: false,
      inputs: [
        {
          id: "incident_id",
          name: "Incident ID",
          type: "string",
          required: true,
        },
        {
          id: "from_email",
          name: "From Email",
          type: "string",
          required: true,
        },
      ],
      outputs: [{ id: "incidentId", name: "Incident ID", type: "string" }],
    },
    {
      id: "incident_add_note",
      name: "Add Note to Incident",
      description: "Add a note to an existing incident",
      connectorType: "pagerduty",
      resource: "incident",
      category: "create",
      stakes: "low",
      reversible: false,
      batchSupport: false,
      inputs: [
        {
          id: "incident_id",
          name: "Incident ID",
          type: "string",
          required: true,
        },
        { id: "content", name: "Note Content", type: "string", required: true },
        {
          id: "from_email",
          name: "From Email",
          type: "string",
          required: true,
        },
      ],
      outputs: [{ id: "noteId", name: "Note ID", type: "string" }],
    },
  ],
};
