import type { ConnectorActionsRegistry } from "@openbeam/types/connector-actions";

export const phabricatorActionsRegistry: ConnectorActionsRegistry = {
  connectorType: "phabricator",
  connectorName: "Phabricator",
  connectorIcon: "phabricator",
  actions: [
    {
      id: "task_create",
      name: "Create Task",
      description: "Create a new Maniphest task in Phabricator",
      connectorType: "phabricator",
      resource: "task",
      category: "create",
      stakes: "low",
      reversible: false,
      batchSupport: false,
      idempotent: false,
      inputs: [
        { id: "title", name: "Title", type: "string", required: true },
        {
          id: "description",
          name: "Description",
          type: "string",
          required: false,
        },
        { id: "priority", name: "Priority", type: "string", required: false },
        {
          id: "ownerPHID",
          name: "Owner PHID",
          type: "string",
          required: false,
        },
        {
          id: "projectPHIDs",
          name: "Project PHIDs",
          type: "array",
          required: false,
        },
      ],
      outputs: [
        { id: "id", name: "Task ID", type: "string" },
        { id: "url", name: "Task URL", type: "string" },
      ],
    },
    {
      id: "task_update",
      name: "Update Task",
      description: "Update a Maniphest task in Phabricator",
      connectorType: "phabricator",
      resource: "task",
      category: "update",
      stakes: "low",
      reversible: true,
      batchSupport: false,
      idempotent: true,
      inputs: [
        { id: "taskId", name: "Task ID", type: "string", required: true },
        { id: "title", name: "Title", type: "string", required: false },
        {
          id: "description",
          name: "Description",
          type: "string",
          required: false,
        },
        { id: "priority", name: "Priority", type: "string", required: false },
        { id: "status", name: "Status", type: "string", required: false },
      ],
      outputs: [{ id: "id", name: "Task ID", type: "string" }],
    },
    {
      id: "wiki_page_create",
      name: "Create Wiki Page",
      description: "Create a new Phriction wiki page in Phabricator",
      connectorType: "phabricator",
      resource: "wiki",
      category: "create",
      stakes: "medium",
      reversible: false,
      batchSupport: false,
      idempotent: false,
      inputs: [
        { id: "title", name: "Title", type: "string", required: true },
        { id: "content", name: "Content", type: "markdown", required: true },
        {
          id: "slug",
          name: "Slug",
          type: "string",
          required: true,
          description: "URL slug for the wiki page",
        },
      ],
      outputs: [
        { id: "id", name: "Page ID", type: "string" },
        { id: "url", name: "Page URL", type: "string" },
      ],
    },
    {
      id: "wiki_page_update",
      name: "Update Wiki Page",
      description: "Update a Phriction wiki page in Phabricator",
      connectorType: "phabricator",
      resource: "wiki",
      category: "update",
      stakes: "low",
      reversible: true,
      batchSupport: false,
      idempotent: true,
      inputs: [
        { id: "slug", name: "Slug", type: "string", required: true },
        { id: "content", name: "Content", type: "markdown", required: true },
        { id: "title", name: "Title", type: "string", required: false },
      ],
      outputs: [{ id: "id", name: "Page ID", type: "string" }],
    },
  ],
};
