import type { ConnectorActionsRegistry } from "@openbeam/types/connector-actions";

export const pipedriveActionsRegistry: ConnectorActionsRegistry = {
  connectorType: "pipedrive",
  connectorName: "Pipedrive",
  connectorIcon: "pipedrive",
  actions: [
    {
      id: "person_list",
      name: "List Persons",
      description:
        "List all contacts (persons) in Pipedrive. Use this to discover person IDs for deals, notes, and activities.",
      connectorType: "pipedrive",
      resource: "person",
      category: "list",
      stakes: "low",
      reversible: false,
      batchSupport: false,
      idempotent: true,
      inputs: [],
      outputs: [
        {
          id: "persons",
          name: "Persons",
          type: "array",
          description: "Array of { id, name, email }",
        },
      ],
    },
    {
      id: "org_list",
      name: "List Organizations",
      description:
        "List all organizations in Pipedrive. Use this to discover organization IDs for deals and contacts.",
      connectorType: "pipedrive",
      resource: "organization",
      category: "list",
      stakes: "low",
      reversible: false,
      batchSupport: false,
      idempotent: true,
      inputs: [],
      outputs: [
        {
          id: "organizations",
          name: "Organizations",
          type: "array",
          description: "Array of { id, name }",
        },
      ],
    },
    {
      id: "deal_create",
      name: "Create Deal",
      description:
        "Create a new deal in Pipedrive. Optional person_id/org_id — call person_list or org_list first to discover IDs.",
      connectorType: "pipedrive",
      resource: "deal",
      category: "create",
      stakes: "medium",
      reversible: false,
      batchSupport: false,
      idempotent: false,
      inputs: [
        {
          id: "title",
          name: "Title",
          type: "string",
          required: true,
          description: "Deal title",
        },
        {
          id: "value",
          name: "Value",
          type: "number",
          required: false,
          description: "Deal monetary value",
        },
        {
          id: "currency",
          name: "Currency",
          type: "string",
          required: false,
          description: "Three-letter currency code (e.g. USD, EUR)",
        },
        {
          id: "person_id",
          name: "Person ID",
          type: "number",
          required: false,
          description: "Associated person (contact) ID",
        },
        {
          id: "org_id",
          name: "Organization ID",
          type: "number",
          required: false,
          description: "Associated organization ID",
        },
      ],
      outputs: [
        { id: "recordId", name: "Deal ID", type: "string" },
        { id: "url", name: "Deal URL", type: "string" },
      ],
    },
    {
      id: "deal_update",
      name: "Update Deal",
      description: "Update an existing deal in Pipedrive",
      connectorType: "pipedrive",
      resource: "deal",
      category: "update",
      stakes: "low",
      reversible: true,
      batchSupport: false,
      idempotent: true,
      inputs: [
        {
          id: "deal_id",
          name: "Deal ID",
          type: "string",
          required: true,
          description: "ID of the deal to update",
        },
        {
          id: "properties",
          name: "Properties",
          type: "object",
          required: true,
          description: "JSON object of field name to value pairs to update",
        },
      ],
      outputs: [
        { id: "recordId", name: "Deal ID", type: "string" },
        { id: "url", name: "Deal URL", type: "string" },
      ],
    },
    {
      id: "person_create",
      name: "Create Person",
      description: "Create a new contact in Pipedrive",
      connectorType: "pipedrive",
      resource: "person",
      category: "create",
      stakes: "medium",
      reversible: false,
      batchSupport: false,
      idempotent: false,
      inputs: [
        {
          id: "name",
          name: "Name",
          type: "string",
          required: true,
          description: "Person full name",
        },
        {
          id: "email",
          name: "Email",
          type: "string",
          required: false,
          description: "Email address",
        },
        {
          id: "phone",
          name: "Phone",
          type: "string",
          required: false,
          description: "Phone number",
        },
        {
          id: "org_id",
          name: "Organization ID",
          type: "number",
          required: false,
          description: "Associated organization ID",
        },
      ],
      outputs: [
        { id: "recordId", name: "Person ID", type: "string" },
        { id: "url", name: "Person URL", type: "string" },
      ],
    },
    {
      id: "note_create",
      name: "Add Note",
      description: "Add a note to a deal, person, or organization",
      connectorType: "pipedrive",
      resource: "note",
      category: "create",
      stakes: "low",
      reversible: false,
      batchSupport: false,
      idempotent: false,
      inputs: [
        {
          id: "content",
          name: "Content",
          type: "string",
          required: true,
          description: "Note content (supports HTML)",
        },
        {
          id: "deal_id",
          name: "Deal ID",
          type: "number",
          required: false,
          description: "Attach note to this deal",
        },
        {
          id: "person_id",
          name: "Person ID",
          type: "number",
          required: false,
          description: "Attach note to this person",
        },
        {
          id: "org_id",
          name: "Organization ID",
          type: "number",
          required: false,
          description: "Attach note to this organization",
        },
      ],
      outputs: [{ id: "recordId", name: "Note ID", type: "string" }],
    },
    {
      id: "activity_create",
      name: "Create Activity",
      description: "Create an activity (call, meeting, task) in Pipedrive",
      connectorType: "pipedrive",
      resource: "activity",
      category: "create",
      stakes: "low",
      reversible: false,
      batchSupport: false,
      idempotent: false,
      inputs: [
        {
          id: "subject",
          name: "Subject",
          type: "string",
          required: true,
          description: "Activity subject line",
        },
        {
          id: "type",
          name: "Type",
          type: "string",
          required: true,
          description: "Activity type (e.g. call, meeting, task, email)",
        },
        {
          id: "due_date",
          name: "Due Date",
          type: "string",
          required: false,
          description: "Due date in YYYY-MM-DD format",
        },
        {
          id: "deal_id",
          name: "Deal ID",
          type: "number",
          required: false,
          description: "Associated deal ID",
        },
        {
          id: "person_id",
          name: "Person ID",
          type: "number",
          required: false,
          description: "Associated person ID",
        },
        {
          id: "note",
          name: "Note",
          type: "string",
          required: false,
          description: "Activity note/description",
        },
      ],
      outputs: [
        { id: "recordId", name: "Activity ID", type: "string" },
        { id: "url", name: "Activity URL", type: "string" },
      ],
    },
  ],
};
