import type { ConnectorActionsRegistry } from "@openbeam/types/canvas";

export const servicenowActionsRegistry: ConnectorActionsRegistry = {
  connectorType: "servicenow",
  connectorName: "ServiceNow",
  connectorIcon: "servicenow",
  actions: [
    {
      id: "incident_create",
      name: "Create Incident",
      description: "Create a new ServiceNow incident",
      connectorType: "servicenow",
      resource: "incident",
      category: "create",
      stakes: "medium",
      reversible: false,
      batchSupport: false,
      inputs: [
        {
          id: "short_description",
          name: "Short Description",
          type: "string",
          required: true,
          description: "Incident summary",
        },
        {
          id: "description",
          name: "Description",
          type: "string",
          required: false,
          description: "Detailed description",
        },
        {
          id: "priority",
          name: "Priority",
          type: "string",
          required: false,
          description:
            "1 (Critical), 2 (High), 3 (Moderate), 4 (Low), 5 (Planning)",
        },
        {
          id: "urgency",
          name: "Urgency",
          type: "string",
          required: false,
          description: "1 (High), 2 (Medium), 3 (Low)",
        },
        {
          id: "category",
          name: "Category",
          type: "string",
          required: false,
          description: "Incident category",
        },
      ],
      outputs: [
        { id: "sysId", name: "Sys ID", type: "string" },
        { id: "number", name: "Incident Number", type: "string" },
        { id: "url", name: "Incident URL", type: "string" },
      ],
    },
    {
      id: "incident_update",
      name: "Update Incident",
      description: "Update fields on an existing ServiceNow incident",
      connectorType: "servicenow",
      resource: "incident",
      category: "update",
      stakes: "low",
      reversible: true,
      batchSupport: false,
      inputs: [
        {
          id: "sys_id",
          name: "Sys ID",
          type: "string",
          required: true,
          description: "Incident sys_id",
        },
        {
          id: "short_description",
          name: "Short Description",
          type: "string",
          required: false,
        },
        {
          id: "state",
          name: "State",
          type: "string",
          required: false,
          description:
            "1 (New), 2 (In Progress), 3 (On Hold), 6 (Resolved), 7 (Closed)",
        },
        {
          id: "priority",
          name: "Priority",
          type: "string",
          required: false,
        },
      ],
      outputs: [{ id: "sysId", name: "Sys ID", type: "string" }],
    },
    {
      id: "comment_add",
      name: "Add Comment",
      description: "Add a comment or work note to a ServiceNow incident",
      connectorType: "servicenow",
      resource: "comment",
      category: "create",
      stakes: "low",
      reversible: false,
      batchSupport: false,
      inputs: [
        {
          id: "sys_id",
          name: "Sys ID",
          type: "string",
          required: true,
          description: "Incident sys_id",
        },
        {
          id: "body",
          name: "Comment Body",
          type: "string",
          required: true,
          description: "Comment text",
        },
        {
          id: "is_work_note",
          name: "Work Note",
          type: "boolean",
          required: false,
          description: "Post as work note instead of customer-visible comment",
          default: false,
        },
      ],
      outputs: [{ id: "sysId", name: "Sys ID", type: "string" }],
    },
  ],
};
