import type { ConnectorActionsRegistry } from "@openbeam/types/canvas";

export const slackActionsRegistry: ConnectorActionsRegistry = {
  connectorType: "slack",
  connectorName: "Slack",
  connectorIcon: "slack",
  actions: [
    {
      id: "message_send",
      name: "Send Message",
      description: "Send a message to a Slack channel",
      connectorType: "slack",
      resource: "message",
      category: "create",
      stakes: "low",
      reversible: true,
      batchSupport: false,
      inputs: [
        {
          id: "channel",
          name: "Channel",
          type: "string",
          required: true,
          description: "Channel ID or name",
        },
        {
          id: "text",
          name: "Text",
          type: "string",
          required: true,
          description: "Message text",
        },
        {
          id: "thread_ts",
          name: "Thread Timestamp",
          type: "string",
          required: false,
          description: "Thread timestamp for replies",
        },
        {
          id: "blocks",
          name: "Blocks",
          type: "array",
          required: false,
          description: "Block Kit blocks",
        },
      ],
      outputs: [
        {
          id: "ts",
          name: "Timestamp",
          type: "string",
          description: "Message timestamp",
        },
        {
          id: "channel",
          name: "Channel",
          type: "string",
          description: "Channel ID",
        },
      ],
    },
    {
      id: "message_update",
      name: "Update Message",
      description: "Update an existing Slack message",
      connectorType: "slack",
      resource: "message",
      category: "update",
      stakes: "low",
      reversible: true,
      batchSupport: false,
      inputs: [
        {
          id: "channel",
          name: "Channel",
          type: "string",
          required: true,
          description: "Channel ID",
        },
        {
          id: "ts",
          name: "Timestamp",
          type: "string",
          required: true,
          description: "Message timestamp",
        },
        {
          id: "text",
          name: "Text",
          type: "string",
          required: true,
          description: "New message text",
        },
        {
          id: "blocks",
          name: "Blocks",
          type: "array",
          required: false,
          description: "Block Kit blocks",
        },
      ],
      outputs: [
        {
          id: "ts",
          name: "Timestamp",
          type: "string",
          description: "Message timestamp",
        },
      ],
    },
    {
      id: "message_delete",
      name: "Delete Message",
      description: "Delete a Slack message",
      connectorType: "slack",
      resource: "message",
      category: "delete",
      stakes: "medium",
      reversible: false,
      batchSupport: false,
      inputs: [
        {
          id: "channel",
          name: "Channel",
          type: "string",
          required: true,
          description: "Channel ID",
        },
        {
          id: "ts",
          name: "Timestamp",
          type: "string",
          required: true,
          description: "Message timestamp",
        },
      ],
      outputs: [
        {
          id: "ok",
          name: "Success",
          type: "boolean",
          description: "Whether deletion succeeded",
        },
      ],
    },
    {
      id: "message_reply",
      name: "Reply to Message",
      description: "Reply to a message in a thread",
      connectorType: "slack",
      resource: "message",
      category: "create",
      stakes: "low",
      reversible: true,
      batchSupport: false,
      inputs: [
        {
          id: "channel",
          name: "Channel",
          type: "string",
          required: true,
          description: "Channel ID",
        },
        {
          id: "thread_ts",
          name: "Thread Timestamp",
          type: "string",
          required: true,
          description: "Parent message timestamp",
        },
        {
          id: "text",
          name: "Text",
          type: "string",
          required: true,
          description: "Reply text",
        },
      ],
      outputs: [
        {
          id: "ts",
          name: "Timestamp",
          type: "string",
          description: "Reply timestamp",
        },
      ],
    },
    {
      id: "message_add_reaction",
      name: "Add Reaction",
      description: "Add an emoji reaction to a message",
      connectorType: "slack",
      resource: "message",
      category: "update",
      stakes: "low",
      reversible: true,
      batchSupport: false,
      inputs: [
        {
          id: "channel",
          name: "Channel",
          type: "string",
          required: true,
          description: "Channel ID",
        },
        {
          id: "ts",
          name: "Timestamp",
          type: "string",
          required: true,
          description: "Message timestamp",
        },
        {
          id: "name",
          name: "Emoji",
          type: "string",
          required: true,
          description: "Emoji name without colons",
        },
      ],
      outputs: [
        {
          id: "ok",
          name: "Success",
          type: "boolean",
          description: "Whether reaction was added",
        },
      ],
    },
    {
      id: "message_search",
      name: "Search Messages",
      description: "Search for messages in Slack",
      connectorType: "slack",
      resource: "message",
      category: "search",
      stakes: "low",
      reversible: false,
      batchSupport: false,
      inputs: [
        {
          id: "query",
          name: "Query",
          type: "string",
          required: true,
          description: "Search query",
        },
        {
          id: "count",
          name: "Count",
          type: "number",
          required: false,
          description: "Max results to return",
        },
        {
          id: "sort",
          name: "Sort",
          type: "string",
          required: false,
          description: "Sort by: score or timestamp",
        },
      ],
      outputs: [
        {
          id: "messages",
          name: "Messages",
          type: "array",
          description: "Matching messages",
        },
        {
          id: "total",
          name: "Total",
          type: "number",
          description: "Total matches",
        },
      ],
    },
    {
      id: "channel_create",
      name: "Create Channel",
      description: "Create a new Slack channel",
      connectorType: "slack",
      resource: "channel",
      category: "create",
      stakes: "medium",
      reversible: true,
      batchSupport: false,
      inputs: [
        {
          id: "name",
          name: "Name",
          type: "string",
          required: true,
          description: "Channel name",
        },
        {
          id: "is_private",
          name: "Private",
          type: "boolean",
          required: false,
          description: "Whether channel is private",
        },
        {
          id: "description",
          name: "Description",
          type: "string",
          required: false,
          description: "Channel purpose",
        },
      ],
      outputs: [
        {
          id: "id",
          name: "Channel ID",
          type: "string",
          description: "Created channel ID",
        },
        {
          id: "name",
          name: "Name",
          type: "string",
          description: "Channel name",
        },
      ],
    },
    {
      id: "channel_archive",
      name: "Archive Channel",
      description: "Archive a Slack channel",
      connectorType: "slack",
      resource: "channel",
      category: "update",
      stakes: "high",
      reversible: true,
      batchSupport: false,
      inputs: [
        {
          id: "channel",
          name: "Channel",
          type: "string",
          required: true,
          description: "Channel ID",
        },
      ],
      outputs: [
        {
          id: "ok",
          name: "Success",
          type: "boolean",
          description: "Whether archive succeeded",
        },
      ],
    },
    {
      id: "channel_set_topic",
      name: "Set Channel Topic",
      description: "Set a channel's topic",
      connectorType: "slack",
      resource: "channel",
      category: "update",
      stakes: "low",
      reversible: true,
      batchSupport: false,
      inputs: [
        {
          id: "channel",
          name: "Channel",
          type: "string",
          required: true,
          description: "Channel ID",
        },
        {
          id: "topic",
          name: "Topic",
          type: "string",
          required: true,
          description: "New topic",
        },
      ],
      outputs: [
        {
          id: "topic",
          name: "Topic",
          type: "string",
          description: "Updated topic",
        },
      ],
    },
    {
      id: "channel_invite",
      name: "Invite to Channel",
      description: "Invite users to a channel",
      connectorType: "slack",
      resource: "channel",
      category: "update",
      stakes: "low",
      reversible: true,
      batchSupport: true,
      inputs: [
        {
          id: "channel",
          name: "Channel",
          type: "string",
          required: true,
          description: "Channel ID",
        },
        {
          id: "user",
          name: "User",
          type: "string",
          required: true,
          description: "User ID(s) to invite",
        },
      ],
      outputs: [
        {
          id: "ok",
          name: "Success",
          type: "boolean",
          description: "Whether invite succeeded",
        },
      ],
    },
    {
      id: "user_lookup",
      name: "Lookup User",
      description: "Look up a Slack user by email or ID",
      connectorType: "slack",
      resource: "user",
      category: "read",
      stakes: "low",
      reversible: false,
      batchSupport: false,
      inputs: [
        {
          id: "email",
          name: "Email",
          type: "email",
          required: false,
          description: "User email",
        },
        {
          id: "user_id",
          name: "User ID",
          type: "string",
          required: false,
          description: "User ID",
        },
      ],
      outputs: [
        { id: "user", name: "User", type: "object", description: "User info" },
      ],
    },
    {
      id: "file_upload",
      name: "Upload File",
      description: "Upload a file to Slack",
      connectorType: "slack",
      resource: "file",
      category: "create",
      stakes: "low",
      reversible: true,
      batchSupport: false,
      inputs: [
        {
          id: "channels",
          name: "Channels",
          type: "string",
          required: true,
          description: "Channel IDs to share with",
        },
        {
          id: "content",
          name: "Content",
          type: "string",
          required: false,
          description: "File content",
        },
        {
          id: "filename",
          name: "Filename",
          type: "string",
          required: false,
          description: "Filename",
        },
        {
          id: "title",
          name: "Title",
          type: "string",
          required: false,
          description: "File title",
        },
      ],
      outputs: [
        {
          id: "id",
          name: "File ID",
          type: "string",
          description: "Uploaded file ID",
        },
      ],
    },
    {
      id: "dm_send",
      name: "Send Direct Message",
      description: "Send a direct message to a user",
      connectorType: "slack",
      resource: "dm",
      category: "create",
      stakes: "low",
      reversible: false,
      batchSupport: false,
      inputs: [
        {
          id: "user",
          name: "User",
          type: "string",
          required: true,
          description: "User ID",
        },
        {
          id: "text",
          name: "Text",
          type: "string",
          required: true,
          description: "Message text",
        },
      ],
      outputs: [
        {
          id: "ts",
          name: "Timestamp",
          type: "string",
          description: "Message timestamp",
        },
        {
          id: "channel",
          name: "Channel",
          type: "string",
          description: "DM channel ID",
        },
      ],
    },
    {
      id: "bookmark_add",
      name: "Add Bookmark",
      description: "Add a bookmark to a channel",
      connectorType: "slack",
      resource: "bookmark",
      category: "create",
      stakes: "low",
      reversible: true,
      batchSupport: false,
      inputs: [
        {
          id: "channel",
          name: "Channel",
          type: "string",
          required: true,
          description: "Channel ID",
        },
        {
          id: "title",
          name: "Title",
          type: "string",
          required: true,
          description: "Bookmark title",
        },
        {
          id: "link",
          name: "Link",
          type: "url",
          required: true,
          description: "Bookmark URL",
        },
      ],
      outputs: [
        {
          id: "id",
          name: "Bookmark ID",
          type: "string",
          description: "Created bookmark ID",
        },
      ],
    },
  ],
};
