import type { ConnectorActionsRegistry } from "@openplane/types/canvas";

export const slackActions: ConnectorActionsRegistry = {
  connectorType: "slack",
  connectorName: "Slack",
  connectorIcon: "slack",
  actions: [
    {
      id: "message_send",
      name: "Send Message",
      description: "Send a message to a Slack channel",
      connectorType: "slack",
      resource: "message",
      category: "create",
      stakes: "medium",
      reversible: false,
      batchSupport: false,
      requiredScopes: ["chat:write"],
      inputs: [
        {
          id: "channel",
          name: "Channel",
          type: "string",
          required: true,
          description: "Channel ID or name to send the message to",
          dynamic: true,
          resourceType: "public_channel",
        },
        {
          id: "text",
          name: "Text",
          type: "string",
          required: true,
          description: "Message text content",
        },
        {
          id: "thread_ts",
          name: "Thread Timestamp",
          type: "string",
          required: false,
          description: "Timestamp of parent message for threading",
        },
        {
          id: "blocks",
          name: "Blocks",
          type: "json",
          required: false,
          description: "Block Kit blocks for rich message formatting",
        },
      ],
      outputs: [
        {
          id: "ts",
          name: "Timestamp",
          type: "string",
          description: "Message timestamp",
        },
        {
          id: "channel",
          name: "Channel",
          type: "string",
          description: "Channel ID",
        },
      ],
    },
    {
      id: "message_update",
      name: "Update Message",
      description: "Update an existing message in a channel",
      connectorType: "slack",
      resource: "message",
      category: "update",
      stakes: "medium",
      reversible: true,
      batchSupport: false,
      requiredScopes: ["chat:write"],
      inputs: [
        {
          id: "channel",
          name: "Channel",
          type: "string",
          required: true,
          description: "Channel containing the message",
          dynamic: true,
          resourceType: "public_channel",
        },
        {
          id: "ts",
          name: "Timestamp",
          type: "string",
          required: true,
          description: "Timestamp of message to update",
        },
        {
          id: "text",
          name: "Text",
          type: "string",
          required: true,
          description: "New message text",
        },
      ],
      outputs: [
        {
          id: "ts",
          name: "Timestamp",
          type: "string",
          description: "Updated message timestamp",
        },
      ],
    },
    {
      id: "message_delete",
      name: "Delete Message",
      description: "Delete a message from a channel",
      connectorType: "slack",
      resource: "message",
      category: "delete",
      stakes: "high",
      reversible: false,
      batchSupport: false,
      requiredScopes: ["chat:write"],
      inputs: [
        {
          id: "channel",
          name: "Channel",
          type: "string",
          required: true,
          description: "Channel containing the message",
          dynamic: true,
          resourceType: "public_channel",
        },
        {
          id: "ts",
          name: "Timestamp",
          type: "string",
          required: true,
          description: "Timestamp of message to delete",
        },
      ],
      outputs: [
        {
          id: "ok",
          name: "Success",
          type: "boolean",
          description: "Whether deletion succeeded",
        },
      ],
    },
    {
      id: "message_reply",
      name: "Reply to Thread",
      description: "Reply to a message thread",
      connectorType: "slack",
      resource: "message",
      category: "create",
      stakes: "medium",
      reversible: false,
      batchSupport: false,
      requiredScopes: ["chat:write"],
      inputs: [
        {
          id: "channel",
          name: "Channel",
          type: "string",
          required: true,
          description: "Channel containing the thread",
          dynamic: true,
          resourceType: "public_channel",
        },
        {
          id: "thread_ts",
          name: "Thread Timestamp",
          type: "string",
          required: true,
          description: "Timestamp of parent message",
        },
        {
          id: "text",
          name: "Text",
          type: "string",
          required: true,
          description: "Reply text content",
        },
      ],
      outputs: [
        {
          id: "ts",
          name: "Timestamp",
          type: "string",
          description: "Reply message timestamp",
        },
      ],
    },
    {
      id: "message_add_reaction",
      name: "Add Reaction",
      description: "Add an emoji reaction to a message",
      connectorType: "slack",
      resource: "message",
      category: "create",
      stakes: "low",
      reversible: true,
      batchSupport: false,
      requiredScopes: ["reactions:write"],
      inputs: [
        {
          id: "channel",
          name: "Channel",
          type: "string",
          required: true,
          description: "Channel containing the message",
          dynamic: true,
          resourceType: "public_channel",
        },
        {
          id: "ts",
          name: "Timestamp",
          type: "string",
          required: true,
          description: "Message timestamp",
        },
        {
          id: "name",
          name: "Emoji Name",
          type: "string",
          required: true,
          description: "Emoji name without colons (e.g. 'thumbsup')",
        },
      ],
      outputs: [
        {
          id: "ok",
          name: "Success",
          type: "boolean",
          description: "Whether reaction was added",
        },
      ],
    },
    {
      id: "message_search",
      name: "Search Messages",
      description: "Search for messages across channels",
      connectorType: "slack",
      resource: "message",
      category: "search",
      stakes: "low",
      reversible: false,
      batchSupport: false,
      requiredScopes: ["search:read"],
      inputs: [
        {
          id: "query",
          name: "Query",
          type: "string",
          required: true,
          description: "Search query text",
        },
        {
          id: "sort",
          name: "Sort",
          type: "string",
          required: false,
          description: "Sort order",
          options: [
            { label: "Relevance", value: "score" },
            { label: "Date", value: "timestamp" },
          ],
        },
        {
          id: "count",
          name: "Count",
          type: "number",
          required: false,
          description: "Max results to return",
          validation: { min: 1, max: 100 },
        },
      ],
      outputs: [
        {
          id: "messages",
          name: "Messages",
          type: "array",
          description: "Matching messages",
        },
        {
          id: "total",
          name: "Total",
          type: "number",
          description: "Total matching messages",
        },
      ],
    },
    {
      id: "channel_create",
      name: "Create Channel",
      description: "Create a new Slack channel",
      connectorType: "slack",
      resource: "channel",
      category: "create",
      stakes: "medium",
      reversible: true,
      batchSupport: false,
      requiredScopes: ["channels:manage"],
      inputs: [
        {
          id: "name",
          name: "Name",
          type: "string",
          required: true,
          description: "Channel name (lowercase, no spaces)",
        },
        {
          id: "is_private",
          name: "Private",
          type: "boolean",
          required: false,
          description: "Create as private channel",
        },
        {
          id: "description",
          name: "Description",
          type: "string",
          required: false,
          description: "Channel description",
        },
      ],
      outputs: [
        {
          id: "id",
          name: "Channel ID",
          type: "string",
          description: "Created channel ID",
        },
        {
          id: "name",
          name: "Name",
          type: "string",
          description: "Channel name",
        },
      ],
    },
    {
      id: "channel_archive",
      name: "Archive Channel",
      description: "Archive a Slack channel",
      connectorType: "slack",
      resource: "channel",
      category: "update",
      stakes: "high",
      reversible: true,
      batchSupport: false,
      requiredScopes: ["channels:manage"],
      inputs: [
        {
          id: "channel",
          name: "Channel",
          type: "string",
          required: true,
          description: "Channel ID to archive",
          dynamic: true,
          resourceType: "public_channel",
        },
      ],
      outputs: [
        {
          id: "ok",
          name: "Success",
          type: "boolean",
          description: "Whether archive succeeded",
        },
      ],
    },
    {
      id: "channel_set_topic",
      name: "Set Topic",
      description: "Set the topic of a channel",
      connectorType: "slack",
      resource: "channel",
      category: "update",
      stakes: "low",
      reversible: true,
      batchSupport: false,
      requiredScopes: ["channels:manage"],
      inputs: [
        {
          id: "channel",
          name: "Channel",
          type: "string",
          required: true,
          description: "Channel ID",
          dynamic: true,
          resourceType: "public_channel",
        },
        {
          id: "topic",
          name: "Topic",
          type: "string",
          required: true,
          description: "New topic text",
        },
      ],
      outputs: [
        {
          id: "topic",
          name: "Topic",
          type: "string",
          description: "Updated topic",
        },
      ],
    },
    {
      id: "channel_invite",
      name: "Invite User",
      description: "Invite a user to a channel",
      connectorType: "slack",
      resource: "channel",
      category: "create",
      stakes: "medium",
      reversible: true,
      batchSupport: false,
      requiredScopes: ["channels:manage"],
      inputs: [
        {
          id: "channel",
          name: "Channel",
          type: "string",
          required: true,
          description: "Channel ID",
          dynamic: true,
          resourceType: "public_channel",
        },
        {
          id: "user",
          name: "User",
          type: "string",
          required: true,
          description: "User ID to invite",
        },
      ],
      outputs: [
        {
          id: "ok",
          name: "Success",
          type: "boolean",
          description: "Whether invitation succeeded",
        },
      ],
    },
    {
      id: "user_lookup",
      name: "Lookup User",
      description: "Find a Slack user by email or ID",
      connectorType: "slack",
      resource: "user",
      category: "read",
      stakes: "low",
      reversible: false,
      batchSupport: false,
      requiredScopes: ["users:read", "users:read.email"],
      inputs: [
        {
          id: "email",
          name: "Email",
          type: "email",
          required: false,
          description: "User's email address",
        },
        {
          id: "user_id",
          name: "User ID",
          type: "string",
          required: false,
          description: "Slack user ID",
        },
      ],
      outputs: [
        {
          id: "id",
          name: "User ID",
          type: "string",
          description: "Slack user ID",
        },
        {
          id: "name",
          name: "Name",
          type: "string",
          description: "Display name",
        },
        {
          id: "email",
          name: "Email",
          type: "string",
          description: "Email address",
        },
      ],
    },
    {
      id: "file_upload",
      name: "Upload File",
      description: "Upload a file to a channel",
      connectorType: "slack",
      resource: "file",
      category: "create",
      stakes: "medium",
      reversible: true,
      batchSupport: false,
      requiredScopes: ["files:write"],
      inputs: [
        {
          id: "channels",
          name: "Channels",
          type: "string",
          required: true,
          description: "Comma-separated channel IDs",
        },
        {
          id: "content",
          name: "Content",
          type: "string",
          required: false,
          description: "File content as text",
        },
        {
          id: "filename",
          name: "Filename",
          type: "string",
          required: true,
          description: "Name for the file",
        },
        {
          id: "title",
          name: "Title",
          type: "string",
          required: false,
          description: "Title for the file",
        },
      ],
      outputs: [
        {
          id: "id",
          name: "File ID",
          type: "string",
          description: "Uploaded file ID",
        },
        {
          id: "url",
          name: "URL",
          type: "string",
          description: "File download URL",
        },
      ],
    },
    {
      id: "dm_send",
      name: "Send Direct Message",
      description: "Send a direct message to a user",
      connectorType: "slack",
      resource: "dm",
      category: "create",
      stakes: "medium",
      reversible: false,
      batchSupport: false,
      requiredScopes: ["chat:write", "im:write"],
      inputs: [
        {
          id: "user",
          name: "User",
          type: "string",
          required: true,
          description: "User ID to message",
        },
        {
          id: "text",
          name: "Text",
          type: "string",
          required: true,
          description: "Message text",
        },
      ],
      outputs: [
        {
          id: "ts",
          name: "Timestamp",
          type: "string",
          description: "Message timestamp",
        },
        {
          id: "channel",
          name: "Channel",
          type: "string",
          description: "DM channel ID",
        },
      ],
    },
    {
      id: "bookmark_add",
      name: "Add Bookmark",
      description: "Add a bookmark to a channel",
      connectorType: "slack",
      resource: "bookmark",
      category: "create",
      stakes: "low",
      reversible: true,
      batchSupport: false,
      requiredScopes: ["bookmarks:write"],
      inputs: [
        {
          id: "channel",
          name: "Channel",
          type: "string",
          required: true,
          description: "Channel ID",
          dynamic: true,
          resourceType: "public_channel",
        },
        {
          id: "title",
          name: "Title",
          type: "string",
          required: true,
          description: "Bookmark title",
        },
        {
          id: "link",
          name: "Link",
          type: "url",
          required: true,
          description: "Bookmark URL",
        },
      ],
      outputs: [
        {
          id: "id",
          name: "Bookmark ID",
          type: "string",
          description: "Created bookmark ID",
        },
      ],
    },
  ],
};
