import type { ConnectorActionsRegistry } from "@openbeam/types/connector-actions";

export const zendeskActionsRegistry: ConnectorActionsRegistry = {
  connectorType: "zendesk",
  connectorName: "Zendesk",
  connectorIcon: "zendesk",
  actions: [
    {
      id: "ticket_create",
      name: "Create Ticket",
      description: "Create a new Zendesk support ticket",
      connectorType: "zendesk",
      resource: "ticket",
      category: "create",
      stakes: "medium",
      reversible: false,
      batchSupport: false,
      inputs: [
        {
          id: "subject",
          name: "Subject",
          type: "string",
          required: true,
          description: "Ticket subject line",
        },
        {
          id: "description",
          name: "Description",
          type: "string",
          required: false,
          description: "Ticket description / first comment",
        },
        {
          id: "priority",
          name: "Priority",
          type: "string",
          required: false,
          description: "urgent, high, normal, low",
        },
        {
          id: "type",
          name: "Type",
          type: "string",
          required: false,
          description: "question, incident, problem, task",
        },
        {
          id: "tags",
          name: "Tags",
          type: "array",
          required: false,
          description: "Comma-separated tags",
        },
      ],
      outputs: [
        { id: "ticketId", name: "Ticket ID", type: "number" },
        { id: "url", name: "Ticket URL", type: "string" },
      ],
    },
    {
      id: "ticket_update",
      name: "Update Ticket",
      description: "Update fields on an existing Zendesk ticket",
      connectorType: "zendesk",
      resource: "ticket",
      category: "update",
      stakes: "low",
      reversible: true,
      batchSupport: false,
      inputs: [
        {
          id: "ticket_id",
          name: "Ticket ID",
          type: "number",
          required: true,
          description: "Zendesk ticket ID",
        },
        {
          id: "subject",
          name: "Subject",
          type: "string",
          required: false,
        },
        {
          id: "status",
          name: "Status",
          type: "string",
          required: false,
          description: "new, open, pending, hold, solved, closed",
        },
        {
          id: "priority",
          name: "Priority",
          type: "string",
          required: false,
        },
        {
          id: "tags",
          name: "Tags",
          type: "array",
          required: false,
        },
      ],
      outputs: [{ id: "ticketId", name: "Ticket ID", type: "number" }],
    },
    {
      id: "comment_add",
      name: "Add Comment",
      description: "Add a comment to a Zendesk ticket",
      connectorType: "zendesk",
      resource: "comment",
      category: "create",
      stakes: "low",
      reversible: false,
      batchSupport: false,
      inputs: [
        {
          id: "ticket_id",
          name: "Ticket ID",
          type: "number",
          required: true,
        },
        {
          id: "body",
          name: "Comment Body",
          type: "string",
          required: true,
          description: "Comment text",
        },
        {
          id: "public",
          name: "Public",
          type: "boolean",
          required: false,
          description: "Whether the comment is public (default true)",
          default: true,
        },
      ],
      outputs: [{ id: "ticketId", name: "Ticket ID", type: "number" }],
    },
  ],
};
