import type { ConnectorActionsRegistry } from "@openbeam/types/connector-actions";

export const zoomActionsRegistry: ConnectorActionsRegistry = {
  connectorType: "zoom",
  connectorName: "Zoom",
  connectorIcon: "zoom",
  actions: [
    {
      id: "user_list",
      name: "List Users",
      description:
        "List all active users in the Zoom account. Use this to discover user IDs before creating meetings.",
      connectorType: "zoom",
      resource: "user",
      category: "list",
      stakes: "low",
      reversible: false,
      batchSupport: false,
      inputs: [],
      outputs: [
        {
          id: "users",
          name: "Users",
          type: "array",
          description: "Array of { id, email, first_name, last_name }",
        },
      ],
    },
    {
      id: "meeting_create",
      name: "Create Meeting",
      description:
        "Schedule a new Zoom meeting. Requires user_id — call user_list first to discover user IDs.",
      connectorType: "zoom",
      resource: "meeting",
      category: "create",
      stakes: "medium",
      reversible: true,
      batchSupport: false,
      inputs: [
        {
          id: "user_id",
          name: "User ID",
          type: "string",
          required: true,
          description: "Zoom user ID or email to schedule the meeting for",
        },
        {
          id: "topic",
          name: "Topic",
          type: "string",
          required: true,
          description: "Meeting topic / title",
        },
        {
          id: "start_time",
          name: "Start Time",
          type: "string",
          required: false,
          description: "Meeting start time in ISO 8601 format",
        },
        {
          id: "duration",
          name: "Duration (minutes)",
          type: "number",
          required: false,
          description: "Meeting duration in minutes",
        },
        {
          id: "agenda",
          name: "Agenda",
          type: "string",
          required: false,
          description: "Meeting agenda or description",
        },
        {
          id: "timezone",
          name: "Timezone",
          type: "string",
          required: false,
          description: "Timezone (e.g., America/Los_Angeles)",
        },
      ],
      outputs: [
        { id: "meetingId", name: "Meeting ID", type: "string" },
        { id: "joinUrl", name: "Join URL", type: "string" },
      ],
    },
    {
      id: "meeting_update",
      name: "Update Meeting",
      description: "Update an existing Zoom meeting",
      connectorType: "zoom",
      resource: "meeting",
      category: "update",
      stakes: "low",
      reversible: true,
      batchSupport: false,
      inputs: [
        {
          id: "meeting_id",
          name: "Meeting ID",
          type: "number",
          required: true,
          description: "Zoom meeting ID",
        },
        {
          id: "topic",
          name: "Topic",
          type: "string",
          required: false,
        },
        {
          id: "start_time",
          name: "Start Time",
          type: "string",
          required: false,
        },
        {
          id: "duration",
          name: "Duration (minutes)",
          type: "number",
          required: false,
        },
        {
          id: "agenda",
          name: "Agenda",
          type: "string",
          required: false,
        },
      ],
      outputs: [{ id: "meetingId", name: "Meeting ID", type: "string" }],
    },
    {
      id: "meeting_delete",
      name: "Delete Meeting",
      description: "Delete a Zoom meeting",
      connectorType: "zoom",
      resource: "meeting",
      category: "delete",
      stakes: "high",
      reversible: false,
      batchSupport: false,
      inputs: [
        {
          id: "meeting_id",
          name: "Meeting ID",
          type: "number",
          required: true,
          description: "Zoom meeting ID to delete",
        },
      ],
      outputs: [{ id: "meetingId", name: "Meeting ID", type: "string" }],
    },
  ],
};
