apiVersion: v1
kind: Service
metadata:
  name: sandbox-gateway
  namespace: openbeam
spec:
  type: NodePort
  selector:
    app: sandbox-gateway
  ports:
    - port: 3800
      targetPort: 3800
      nodePort: 30380
