-- AddAtomicSyncMetrics
ALTER TABLE "sync_history" ADD COLUMN IF NOT EXISTS "documentsAdded" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "sync_history" ADD COLUMN IF NOT EXISTS "documentsUpdated" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "sync_history" ADD COLUMN IF NOT EXISTS "documentsRemoved" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "sync_history" ADD COLUMN IF NOT EXISTS "filesDiscovered" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "sync_history" ADD COLUMN IF NOT EXISTS "mediaDiscovered" INTEGER NOT NULL DEFAULT 0;
