import {
  AppType,
  AuthType,
  ConnectorType,
  SyncMode,
  type UnifiedApp,
} from "../types";

export const niceCxoneApp: UnifiedApp = {
  id: AppType.NICE_CXONE,
  name: "NICE CXone",
  category: "Contact Center & Customer Service",
  active: true,
  logo: AppType.NICE_CXONE,
  short_description:
    "Search contacts, agents, skills, teams, and campaigns from NICE CXone.",
  description:
    "Connect NICE CXone to search across contact center data including completed contacts, agent profiles, routing skills, teams, and campaigns. Uses OAuth 2.0 client credentials with page-based pagination.",
  images: [],
  installed: false,
  type: "official",
  connectorType: ConnectorType.SOURCE,
  developerName: "NICE Ltd",
  website: "https://www.nice.com/products/cxone",

  searchDisplay: {
    defaultIconKey: "Headphones",
    documentTypes: {
      contact: {
        label: "contact",
        iconKey: "Phone",
        category: "ticket",
      },
      agent: {
        label: "agent",
        iconKey: "User",
        category: "contact",
      },
      skill: {
        label: "skill",
        iconKey: "Route",
        category: "document",
      },
      team: {
        label: "team",
        iconKey: "Users",
        category: "document",
      },
      campaign: {
        label: "campaign",
        iconKey: "Megaphone",
        category: "document",
      },
    },
  },

  features: [
    "Contact interaction search with disposition, duration, and agent data",
    "Agent directory with status, skills, and team assignments",
    "Skill/queue listing with service level and routing configuration",
    "Team hierarchy with member count and supervisor info",
    "Campaign search with status, dialing mode, and skill linkage",
    "OAuth 2.0 client credentials authentication",
    "Incremental sync via startDate/endDate filters",
  ],

  auth: {
    type: AuthType.API_KEY,
    config: {
      headerName: "Authorization",
      documentationUrl: "https://developer.niceincontact.com/Documentation",
    },
  },

  streams: [
    {
      name: "contacts",
      label: "Contacts",
      description: "Completed contact interactions with call details",
      entityType: "resource",
      dataPoints: [
        "Contact ID",
        "Agent",
        "Skill",
        "Start Time",
        "Duration",
        "Direction",
        "Disposition",
      ],
      isPii: true,
      syncMode: SyncMode.PERIODIC,
      defaultInterval: 15,
      supportsBackfill: true,
    },
    {
      name: "agents",
      label: "Agents",
      description: "Agent profiles with skills and team membership",
      entityType: "resource",
      dataPoints: ["Name", "Email", "Team", "Status", "Skills", "Last Login"],
      isPii: true,
      syncMode: SyncMode.PERIODIC,
      defaultInterval: 60,
      supportsBackfill: true,
    },
    {
      name: "skills",
      label: "Skills",
      description: "Routing skills and queue configuration",
      entityType: "resource",
      dataPoints: [
        "Name",
        "Media Type",
        "Campaign",
        "Is Active",
        "Service Level",
        "Agents Assigned",
      ],
      isPii: false,
      syncMode: SyncMode.PERIODIC,
      defaultInterval: 60,
      supportsBackfill: true,
    },
    {
      name: "teams",
      label: "Teams",
      description: "Team definitions with agent membership",
      entityType: "resource",
      dataPoints: [
        "Name",
        "Description",
        "Agent Count",
        "Is Active",
        "Team Lead",
      ],
      isPii: false,
      syncMode: SyncMode.PERIODIC,
      defaultInterval: 60,
      supportsBackfill: true,
    },
    {
      name: "campaigns",
      label: "Campaigns",
      description: "Campaign definitions with dialing configuration",
      entityType: "resource",
      dataPoints: ["Name", "Description", "Is Active", "Skills", "Notes"],
      isPii: false,
      syncMode: SyncMode.PERIODIC,
      defaultInterval: 60,
      supportsBackfill: true,
    },
  ],

  settings: [
    {
      id: "base_url",
      label: "CXone Base URL",
      description:
        "Your NICE CXone instance URL (e.g., https://api-c32.niceincontact.com).",
      type: "text",
      required: true,
      value: "",
      placeholder: "https://api-c32.niceincontact.com",
    },
    {
      id: "client_id",
      label: "Client ID",
      description: "OAuth 2.0 client ID from CXone Admin > API Applications.",
      type: "text",
      required: true,
      value: "",
      placeholder: "your-client-id",
    },
    {
      id: "client_secret",
      label: "Client Secret",
      description: "OAuth 2.0 client secret from the same API application.",
      type: "password",
      required: true,
      value: "",
    },
    {
      id: "sync_contacts",
      label: "Sync Contacts",
      description: "Index completed contact interactions.",
      type: "switch",
      required: false,
      value: true,
    },
    {
      id: "sync_agents",
      label: "Sync Agents",
      description: "Index agent directory.",
      type: "switch",
      required: false,
      value: true,
    },
    {
      id: "sync_skills",
      label: "Sync Skills",
      description: "Index routing skills and queues.",
      type: "switch",
      required: false,
      value: true,
    },
    {
      id: "sync_teams",
      label: "Sync Teams",
      description: "Index team definitions.",
      type: "switch",
      required: false,
      value: true,
    },
    {
      id: "sync_campaigns",
      label: "Sync Campaigns",
      description: "Index campaigns.",
      type: "switch",
      required: false,
      value: true,
    },
    {
      id: "lookback_days",
      label: "Lookback Days",
      description:
        "How many days back to sync contacts on the initial full sync (default: 90).",
      type: "text",
      required: false,
      value: "90",
      placeholder: "90",
    },
  ],
};

export default niceCxoneApp;
