import { AppType, AuthType, ConnectorType, type UnifiedApp } from "../types";

export const customApp: UnifiedApp = {
  id: AppType.CUSTOM,
  name: "Custom Connector",
  category: "Custom",
  active: true,
  logo: AppType.CUSTOM,
  short_description: "Connect your own data sources via API",
  description:
    "Push data from any API, webhook, or internal service into OpenBeam. Supports Push API for real-time ingestion, Scheduled Pull for polling external endpoints, and Webhook ingestion for event-driven data. Each connector gets its own API key and endpoint.",
  images: [],
  installed: false,
  type: "official",
  connectorType: ConnectorType.SOURCE,
  developerName: "OpenBeam",
  website: "https://docs.openbeam.work/connectors/custom",

  features: [
    "Push API",
    "Webhook Ingestion",
    "Scheduled Pull",
    "Batch Operations",
    "API Key Auth",
    "Custom Field Mapping",
  ],

  auth: {
    type: AuthType.API_KEY,
    config: {
      headerName: "Authorization",
      documentationUrl: "https://docs.openbeam.work/connectors/custom",
    },
  },

  streams: [],

  settings: [
    {
      id: "mode",
      label: "Ingestion Mode",
      description: "How data flows into OpenBeam.",
      type: "select",
      required: true,
      value: "push",
      options: [
        { label: "Push API", value: "push" },
        { label: "Scheduled Pull", value: "pull" },
        { label: "Webhook", value: "webhook" },
      ],
    },
    {
      id: "connector_name",
      label: "Connector Name",
      description: "Display name for this connector.",
      type: "text",
      required: true,
      value: "",
      placeholder: "e.g. Internal Wiki, CRM Export",
    },
    {
      id: "connector_slug",
      label: "Slug",
      description: "URL-safe identifier. Auto-generated from name.",
      type: "text",
      required: true,
      value: "",
      placeholder: "e.g. internal-wiki",
    },
    {
      id: "connector_description",
      label: "Description",
      description: "What data this connector provides.",
      type: "textarea",
      required: false,
      value: "",
      placeholder: "Documents from our internal knowledge base",
      rows: 3,
    },
    {
      id: "pull_base_url",
      label: "Base URL",
      description: "The API endpoint to pull data from.",
      type: "text",
      required: true,
      value: "",
      placeholder: "https://api.example.com",
      dependsOn: { field: "mode", value: "pull" },
    },
    {
      id: "pull_auth_type",
      label: "Authentication",
      description: "How to authenticate with the external API.",
      type: "select",
      required: true,
      value: "bearer",
      options: [
        { label: "Bearer Token", value: "bearer" },
        { label: "API Key Header", value: "api_key" },
        { label: "Basic Auth", value: "basic" },
      ],
      dependsOn: { field: "mode", value: "pull" },
    },
    {
      id: "pull_auth_value",
      label: "Auth Credential",
      description: "Token, API key, or base64-encoded credentials.",
      type: "password",
      required: true,
      value: "",
      dependsOn: { field: "mode", value: "pull" },
    },
    {
      id: "pull_endpoint_path",
      label: "Endpoint Path",
      description: "Path appended to base URL.",
      type: "text",
      required: false,
      value: "",
      placeholder: "/v1/documents",
      dependsOn: { field: "mode", value: "pull" },
    },
    {
      id: "pull_response_path",
      label: "Response Data Path",
      description: "JSONPath to the array of documents in the response.",
      type: "text",
      required: false,
      value: "$.data",
      placeholder: "$.data",
      dependsOn: { field: "mode", value: "pull" },
    },
    {
      id: "pull_sync_interval",
      label: "Sync Interval",
      description: "How often to pull data.",
      type: "select",
      required: true,
      value: "1h",
      options: [
        { label: "Every 15 minutes", value: "15min" },
        { label: "Every 30 minutes", value: "30min" },
        { label: "Every hour", value: "1h" },
        { label: "Every 6 hours", value: "6h" },
        { label: "Every 12 hours", value: "12h" },
        { label: "Daily", value: "24h" },
      ],
      dependsOn: { field: "mode", value: "pull" },
    },
    {
      id: "webhook_signature_algorithm",
      label: "Signature Algorithm",
      description: "How webhook payloads are signed.",
      type: "select",
      required: false,
      value: "hmac-sha256",
      options: [
        { label: "HMAC-SHA256", value: "hmac-sha256" },
        { label: "HMAC-SHA1", value: "hmac-sha1" },
        { label: "None", value: "none" },
      ],
      dependsOn: { field: "mode", value: "webhook" },
    },
    {
      id: "webhook_signature_header",
      label: "Signature Header",
      description: "HTTP header containing the webhook signature.",
      type: "text",
      required: false,
      value: "X-Webhook-Signature",
      placeholder: "X-Webhook-Signature",
      dependsOn: { field: "mode", value: "webhook" },
    },
  ],
};

export default customApp;
