server:
  replicaCount: 1
  config:
    persistence:
      default:
        driver: sql
        sql:
          driver: postgres12
          host: REPLACE_WITH_POSTGRES_FQDN
          port: 5432
          database: temporal
          user: temporal
          existingSecret: temporal-db-credentials
          maxConns: 20
          maxIdleConns: 20
          maxConnLifetime: 1h
      visibility:
        driver: sql
        sql:
          driver: postgres12
          host: REPLACE_WITH_POSTGRES_FQDN
          port: 5432
          database: temporal_visibility
          user: temporal
          existingSecret: temporal-db-credentials
          maxConns: 10
          maxIdleConns: 10
          maxConnLifetime: 1h
    numHistoryShards: 4

  frontend:
    replicaCount: 1
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 2000m
        memory: 2Gi

  history:
    replicaCount: 1
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 2000m
        memory: 2Gi

  matching:
    replicaCount: 1
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1Gi

  worker:
    replicaCount: 1
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 1Gi

web:
  enabled: true
  replicaCount: 1
  service:
    port: 8233
    type: ClusterIP
  resources:
    requests:
      cpu: 50m
      memory: 96Mi
    limits:
      cpu: 200m
      memory: 192Mi

cassandra:
  enabled: false

mysql:
  enabled: false

postgresql:
  enabled: false

elasticsearch:
  enabled: false

prometheus:
  enabled: false

grafana:
  enabled: false

schema:
  setup:
    enabled: false
  update:
    enabled: false
