export {
  type ConsentPreferences,
  detectRegion,
  type GDPRCompliantConfig,
  getConsentPreferences,
  getDefaultConsentPreferences,
  handleConsentGiven,
  hasGivenConsent,
  initWithGDPRCompliance,
  isEUUser,
  requestDataDeletion,
  requestDataExport,
  revokeConsent,
  updateConsentPreferences,
} from "./gdpr";

export {
  defaultSessionRecordingConfig,
  excludeElement,
  getPrivacyAttributeForMaskedData,
  getPrivacyAttributeForSensitiveData,
  getSensitiveInputSelector,
  includeElement,
  isSessionRecordingActive,
  markSessionAsImportant,
  maskElement,
  PRIVACY_CLASSES,
  type SensitiveFieldType,
  type SessionRecordingConfig,
  sensitiveFieldTypes,
  startSessionRecording,
  stopSessionRecording,
  tagSessionRecording,
  unmaskElement,
} from "./session-recording";
