{{- if .Values.serviceAccount.create }}
{{- $identities := .Values.serviceAccount.workloadIdentities | default dict }}
{{- range $name, $config := $identities }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $config.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "openbeam.labels" $ | nindent 4 }}
  {{- with $config.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
