{{- if and .Values.services.bot.enabled .Values.services.bot.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "openbeam.botName" . }}
  labels:
    {{- include "openbeam.labels" . | nindent 4 }}
    app.kubernetes.io/component: bot
spec:
  type: {{ .Values.services.bot.service.type }}
  selector:
    {{- include "openbeam.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: bot
  ports:
    - name: http
      port: {{ .Values.services.bot.service.port }}
      targetPort: {{ .Values.services.bot.service.targetPort }}
      protocol: TCP
      {{- if and (or (eq .Values.services.bot.service.type "NodePort") (eq .Values.services.bot.service.type "LoadBalancer")) .Values.services.bot.service.nodePort }}
      nodePort: {{ .Values.services.bot.service.nodePort }}
      {{- end }}
{{- end }}
