kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: openbeam-dev
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30001
        hostPort: 3001
        protocol: TCP
      - containerPort: 30000
        hostPort: 3000
        protocol: TCP
      - containerPort: 30080
        hostPort: 8080
        protocol: TCP
      - containerPort: 30233
        hostPort: 8233
        protocol: TCP
      - containerPort: 30800
        hostPort: 8000
        protocol: TCP
      - containerPort: 30900
        hostPort: 9000
        protocol: TCP
      - containerPort: 30901
        hostPort: 9001
        protocol: TCP
      - containerPort: 30090
        hostPort: 9090
        protocol: TCP
      - containerPort: 30002
        hostPort: 3002
        protocol: TCP
      - containerPort: 30880
        hostPort: 7880
        protocol: TCP
      - containerPort: 30380
        hostPort: 3800
        protocol: TCP
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
