export type { SimpplrFile } from "./files";
export { listFiles } from "./files";
export type { SimpplrNewsArticle } from "./news";
export { listNews } from "./news";
export type { SimpplrPage } from "./pages";
export { listPages } from "./pages";
export type { SimpplrPerson } from "./people";
export { listPeople } from "./people";
export type { SimpplrSite } from "./sites";
export { listSites } from "./sites";
