export { SearchService, searchService } from "./service";
export type {
  AuthorFacet,
  AuthorFacetsParams,
  AuthorSearchParams,
  DocumentSearchResult,
  MediaSearchParams,
  MediaSearchRanking,
  MediaSearchResult,
  RecentDocumentsParams,
  ScoredMedia,
  SearchParams,
  SearchRanking,
  SearchScoredDocument,
  SimilarDocumentsParams,
  ThreadSearchParams,
  UnifiedSearchItem,
  UnifiedSearchParams,
  UnifiedSearchResult,
} from "./types";
