export type { RecordActionResult as SalesforceRecordActionResult } from "./actions";
export { createSalesforceRecord, updateSalesforceRecord } from "./actions";
export { createRecord, describeSObject, updateRecord } from "./api";
export { SalesforceAuth } from "./auth";
export type { SalesforceClient, SalesforceClientConfig } from "./client";
export { createSalesforceClient } from "./client";
export { salesforceFullSync } from "./sync/full";
export { salesforceIncrementalSync } from "./sync/incremental";
export type { SalesforceAccount } from "./transformers/account";
export { transformSalesforceAccount } from "./transformers/account";
export type { SalesforceKnowledgeArticle } from "./transformers/article";
export { transformSalesforceArticle } from "./transformers/article";
export type { SalesforceCase } from "./transformers/case";
export { transformSalesforceCase } from "./transformers/case";
export type { SalesforceContact } from "./transformers/contact";
export { transformSalesforceContact } from "./transformers/contact";
export type { SalesforceOpportunity } from "./transformers/opportunity";
export { transformSalesforceOpportunity } from "./transformers/opportunity";
export { SalesforceApiError } from "./types";
