apiVersion: v1
kind: Service
metadata:
  name: worker
  namespace: openplane
spec:
  selector:
    app: worker
  ports:
    - name: metrics
      port: 9091
      targetPort: 9091
    - name: health
      port: 9092
      targetPort: 9092
