import {
  AppType,
  AuthType,
  ConnectorType,
  SyncMode,
  type UnifiedApp,
} from "../types";

export const azureDevOpsApp: UnifiedApp = {
  id: AppType.AZURE_DEVOPS,
  name: "Azure DevOps",
  category: "Development",
  active: true,
  logo: AppType.AZURE_DEVOPS,
  short_description:
    "Search across work items, repositories, pull requests, and wiki pages.",
  description:
    "Connect Azure DevOps to search across work items, repositories, pull requests, and wiki pages. Supports OAuth 2.0 with WIQL-based incremental sync.",
  images: [],
  installed: false,
  type: "official",
  connectorType: ConnectorType.SOURCE,
  developerName: "Microsoft",
  website: "https://azure.microsoft.com/en-us/products/devops",

  searchDisplay: {
    defaultIconKey: "CircleDot",
    documentTypes: {
      work_item: {
        label: "work item",
        iconKey: "CircleDot",
        category: "issue",
      },
      repository: {
        label: "repository",
        iconKey: "GitBranch",
        category: "repository",
      },
      pull_request: {
        label: "pull request",
        iconKey: "GitMerge",
        category: "pull_request",
      },
      wiki_page: {
        label: "wiki page",
        iconKey: "FileText",
        category: "wiki",
      },
    },
  },

  features: [
    "Semantic search across work items, repos, PRs, and wiki pages",
    "Incremental sync via WIQL timestamp filtering",
    "Project-level filtering and exclusion",
  ],

  auth: {
    type: AuthType.OAUTH2,
    config: {
      authUrl: "https://app.vssps.visualstudio.com/oauth2/authorize",
      tokenUrl: "https://app.vssps.visualstudio.com/oauth2/token",
      redirectPath: "/connectors/setup/azure-devops/oauth/callback",
      scopes: ["vso.work", "vso.code", "vso.wiki", "vso.project"],
    },
  },

  streams: [
    {
      name: "work_items",
      label: "Work Items",
      description: "Bugs, tasks, user stories, features, and epics",
      entityType: "activity",
      dataPoints: [
        "Title",
        "Description",
        "State",
        "Assignee",
        "Priority",
        "Tags",
      ],
      isPii: false,
      syncMode: SyncMode.PERIODIC,
      defaultInterval: 15,
      supportsBackfill: true,
    },
    {
      name: "repositories",
      label: "Repositories",
      description: "Git repositories in Azure DevOps projects",
      entityType: "resource",
      dataPoints: ["Name", "Default Branch", "Project", "Size"],
      isPii: false,
      syncMode: SyncMode.PERIODIC,
      defaultInterval: 60,
      supportsBackfill: true,
    },
    {
      name: "pull_requests",
      label: "Pull Requests",
      description: "Pull requests across repositories",
      entityType: "activity",
      dataPoints: [
        "Title",
        "Description",
        "Status",
        "Source Branch",
        "Target Branch",
        "Reviewers",
      ],
      isPii: false,
      syncMode: SyncMode.PERIODIC,
      defaultInterval: 15,
      supportsBackfill: true,
    },
    {
      name: "wiki_pages",
      label: "Wiki Pages",
      description: "Project wiki pages and documentation",
      entityType: "resource",
      dataPoints: ["Title", "Content", "Path"],
      isPii: false,
      syncMode: SyncMode.PERIODIC,
      defaultInterval: 60,
      supportsBackfill: true,
    },
  ],

  settings: [
    {
      id: "oauth_input_method",
      label: "Credentials",
      description: "Enter Azure DevOps OAuth app credentials.",
      type: "select",
      required: true,
      value: "manual",
      options: [{ label: "Enter manually", value: "manual" }],
    },
    {
      id: "client_id",
      label: "App ID",
      description: "From Azure DevOps app registration",
      type: "text",
      required: true,
      value: "",
      placeholder: "your-app-id",
    },
    {
      id: "client_secret",
      label: "Client Secret",
      description: "App secret from Azure DevOps",
      type: "password",
      required: true,
      value: "",
    },
    {
      id: "organization",
      label: "Organization",
      description: "Azure DevOps organization name (from your URL)",
      type: "text",
      required: true,
      value: "",
      placeholder: "my-org",
    },
    {
      id: "include_projects",
      label: "Include Projects",
      description: "Only sync these projects. Leave empty for all.",
      type: "text",
      required: false,
      value: "",
      placeholder: "MyProject, AnotherProject",
    },
    {
      id: "exclude_projects",
      label: "Exclude Projects",
      description: "Skip these projects.",
      type: "text",
      required: false,
      value: "",
    },
    {
      id: "sync_repos",
      label: "Sync Repositories",
      description: "Index Git repositories as searchable documents.",
      type: "switch",
      required: false,
      value: true,
    },
    {
      id: "sync_pull_requests",
      label: "Sync Pull Requests",
      description: "Index pull requests as searchable documents.",
      type: "switch",
      required: false,
      value: true,
    },
    {
      id: "sync_wiki",
      label: "Sync Wiki Pages",
      description: "Index project wiki pages.",
      type: "switch",
      required: false,
      value: false,
    },
    {
      id: "work_item_types",
      label: "Work Item Types",
      description: "Only sync these types. Leave empty for all.",
      type: "text",
      required: false,
      value: "",
      placeholder: "Bug, Task, User Story, Feature, Epic",
    },
    {
      id: "lookback_days",
      label: "History (days)",
      description: "How far back to sync. Leave empty for unlimited.",
      type: "text",
      required: false,
      value: "",
      placeholder: "Unlimited",
    },
  ],
};

export default azureDevOpsApp;
