import {
  AppType,
  AuthType,
  ConnectorType,
  SyncMode,
  type UnifiedApp,
} from "../types";

export const hubspotApp: UnifiedApp = {
  id: AppType.HUBSPOT,
  name: "HubSpot",
  category: "CRM",
  active: true,
  logo: AppType.HUBSPOT,
  short_description:
    "Search across contacts, deals, tickets, and companies from HubSpot CRM.",
  description:
    "Connect HubSpot to search across CRM data including contacts, companies, deals, and tickets. Supports OAuth 2.0 with incremental sync via the Search API.",
  images: [],
  installed: false,
  type: "official",
  connectorType: ConnectorType.SOURCE,
  developerName: "HubSpot, Inc.",
  website: "https://www.hubspot.com",

  searchDisplay: {
    defaultIconKey: "Cloud",
    documentTypes: {
      contact: { label: "contact", iconKey: "UserCircle", category: "contact" },
      company: { label: "company", iconKey: "Building", category: "account" },
      deal: { label: "deal", iconKey: "TrendingUp", category: "deal" },
      ticket: { label: "ticket", iconKey: "Ticket", category: "ticket" },
    },
  },

  features: [
    "Semantic search across CRM objects",
    "Incremental sync via lastmodifieddate filtering",
    "Contacts, companies, deals, and tickets",
  ],

  auth: {
    type: AuthType.OAUTH2,
    config: {
      authUrl: "https://app.hubspot.com/oauth/authorize",
      tokenUrl: "https://api.hubapi.com/oauth/v1/token",
      redirectPath: "/connectors/setup/hubspot/oauth/callback",
      scopes: [
        "crm.objects.contacts.read",
        "crm.objects.companies.read",
        "crm.objects.deals.read",
        "tickets",
      ],
    },
  },

  streams: [
    {
      name: "contacts",
      label: "Contacts",
      description: "CRM contact records",
      entityType: "resource",
      dataPoints: ["Name", "Email", "Phone", "Company", "Job Title"],
      isPii: true,
      syncMode: SyncMode.PERIODIC,
      defaultInterval: 30,
      supportsBackfill: true,
    },
    {
      name: "companies",
      label: "Companies",
      description: "Company records and organizations",
      entityType: "resource",
      dataPoints: ["Name", "Domain", "Industry", "Description", "Employees"],
      isPii: false,
      syncMode: SyncMode.PERIODIC,
      defaultInterval: 30,
      supportsBackfill: true,
    },
    {
      name: "deals",
      label: "Deals",
      description: "Sales deals and pipeline stages",
      entityType: "activity",
      dataPoints: ["Name", "Amount", "Stage", "Pipeline", "Close Date"],
      isPii: false,
      syncMode: SyncMode.PERIODIC,
      defaultInterval: 15,
      supportsBackfill: true,
    },
    {
      name: "tickets",
      label: "Tickets",
      description: "Support tickets and cases",
      entityType: "activity",
      dataPoints: ["Subject", "Content", "Stage", "Priority"],
      isPii: false,
      syncMode: SyncMode.PERIODIC,
      defaultInterval: 15,
      supportsBackfill: true,
    },
  ],

  settings: [
    {
      id: "oauth_input_method",
      label: "Credentials",
      description: "Enter HubSpot app credentials.",
      type: "select",
      required: true,
      value: "manual",
      options: [{ label: "Enter manually", value: "manual" }],
    },
    {
      id: "client_id",
      label: "Client ID",
      description: "From your HubSpot developer app settings",
      type: "text",
      required: true,
      value: "",
      placeholder: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
    },
    {
      id: "client_secret",
      label: "Client Secret",
      description: "From your HubSpot developer app settings",
      type: "password",
      required: true,
      value: "",
    },
    {
      id: "sync_contacts",
      label: "Sync Contacts",
      description: "Index contacts as searchable documents.",
      type: "switch",
      required: false,
      value: true,
    },
    {
      id: "sync_companies",
      label: "Sync Companies",
      description: "Index companies as searchable documents.",
      type: "switch",
      required: false,
      value: true,
    },
    {
      id: "sync_deals",
      label: "Sync Deals",
      description: "Index deals as searchable documents.",
      type: "switch",
      required: false,
      value: true,
    },
    {
      id: "sync_tickets",
      label: "Sync Tickets",
      description: "Index tickets as searchable documents.",
      type: "switch",
      required: false,
      value: true,
    },
    {
      id: "pipeline_filter",
      label: "Pipeline Filter",
      description:
        "Only sync deals in these pipelines (comma-separated IDs). Leave empty for all.",
      type: "text",
      required: false,
      value: "",
      placeholder: "default, sales",
    },
    {
      id: "lookback_days",
      label: "History (days)",
      description: "How far back to sync. Leave empty for unlimited.",
      type: "text",
      required: false,
      value: "",
      placeholder: "Unlimited",
    },
    {
      id: "custom_properties",
      label: "Custom Properties",
      description: "Additional HubSpot properties to index (comma-separated).",
      type: "text",
      required: false,
      value: "",
      placeholder: "hs_lead_status, industry",
    },
  ],
};

export default hubspotApp;
