export const LT = {
  bg: "#09090b",
  bgSubtle: "#0f0f11",
  surface: "#18181b",
  surfaceHover: "#1f1f23",

  fg: "#f5f5f7",
  fgMuted: "#a1a1aa",
  fgDim: "#71717a",
  fgGhost: "#52525b",

  border: "#27272a",
  borderSubtle: "#ffffff0f",

  blue: "#3b82f6",
  blueDim: "#3b82f620",
  purple: "#8b5cf6",
  purpleDim: "#8b5cf620",
  green: "#22c55e",
  greenDim: "#22c55e20",
  amber: "#f59e0b",
  amberDim: "#f59e0b20",
  red: "#ef4444",

  slack: "#e01e5a",
  notion: "#ffffff",
  linear: "#5e6ad2",
  github: "#f0f6fc",
  gdrive: "#4285f4",
  confluence: "#1868db",
  jira: "#0052cc",

  radius: 8,
  radiusSm: 4,

  font: {
    sans: "'Inter', system-ui, sans-serif",
    mono: "'Geist Mono', 'SF Mono', monospace",
  },
} as const;

export const CONNECTOR_LOGOS = [
  "Slack",
  "Notion",
  "Linear",
  "GitHub",
  "Google Drive",
  "Confluence",
  "Jira",
  "Gmail",
  "Figma",
  "Asana",
  "HubSpot",
  "Salesforce",
  "Zendesk",
  "Intercom",
  "Monday",
  "ClickUp",
  "Trello",
  "Airtable",
  "Dropbox",
  "Box",
  "OneDrive",
  "SharePoint",
  "Teams",
  "Zoom",
  "PagerDuty",
  "Datadog",
  "Sentry",
  "GitLab",
  "Bitbucket",
  "CircleCI",
  "Vercel",
  "AWS",
  "Azure",
  "GCP",
  "Stripe",
  "Twilio",
  "Snowflake",
  "BigQuery",
  "Postgres",
  "MongoDB",
  "Redis",
  "Elastic",
  "Splunk",
  "Sumo Logic",
  "New Relic",
  "Grafana",
  "ServiceNow",
  "Freshdesk",
  "Gusto",
  "BambooHR",
  "Workday",
  "Oracle",
  "SAP",
  "NetSuite",
  "Mixpanel",
  "Amplitude",
  "Segment",
  "Heap",
  "Looker",
  "Tableau",
  "Miro",
  "Loom",
  "Calendly",
  "DocuSign",
  "Coda",
  "Basecamp",
  "Discord",
  "Webflow",
  "Ghost",
  "Wordpress",
  "Shopify",
  "Magento",
  "Marketo",
  "Pardot",
  "Mailchimp",
  "SendGrid",
  "Postmark",
  "Braze",
  "Okta",
  "Auth0",
  "OneLogin",
  "Duo",
  "CrowdStrike",
  "SentinelOne",
  "Wiz",
  "Snyk",
  "SonarQube",
  "Terraform",
  "Pulumi",
  "Kubernetes",
  "Docker",
  "Vault",
  "Consul",
  "Pendo",
  "FullStory",
  "Hotjar",
  "Gong",
  "Outreach",
  "Apollo",
  "ZoomInfo",
  "Clearbit",
  "Lusha",
  "Notion",
  "Coda",
  "Roam",
] as const;
