apiVersion: v1
kind: Service
metadata:
  name: livekit
  namespace: openbeam
spec:
  type: NodePort
  selector:
    app: livekit
  ports:
    - port: 7880
      targetPort: 7880
      nodePort: 30880
