/**
 * Agent Execution Queue
 *
 * Handles agentic AI task execution for deep research and multi-step reasoning.
 * Supports the AgentExecution and AgentStep models from ai.prisma.
 */
import { Queue } from "bullmq";
import { getSharedBullMqConnection } from "../client";
import { extractTraceContext, type TraceContext } from "../utils/trace-context";

// === Agent Job Types ===

export type AgentTaskType =
  | "research" // Deep research - multi-step information gathering
  | "analysis" // Data analysis - processing and insights
  | "action" // Action execution - triggering workflows
  | "synthesis"; // Synthesis - combining information from multiple sources

export type AgentStepType =
  | "search" // Search for information
  | "read" // Read/analyze document
  | "reason" // Think/reason about information
  | "tool" // Execute a tool/action
  | "synthesize" // Combine information
  | "verify" // Verify/validate result
  | "ask"; // Ask user for clarification

export interface AgentJobData {
  executionId: string;
  teamId: string;
  userId: string;
  conversationId?: string;

  // Task details
  task: string;
  taskType: AgentTaskType;

  // Execution plan (generated by planner)
  plan?: AgentStep[];

  // Current state
  currentStep: number;

  // Context from previous steps
  context?: AgentContext;

  // Configuration
  config?: AgentConfig;

  // Tracing
  traceContext?: TraceContext;
}

export interface AgentStep {
  stepId: string;
  type: AgentStepType;
  description: string;
  input?: Record<string, unknown>;
  toolId?: string;
  toolName?: string;
  dependencies?: string[]; // Step IDs this step depends on
}

export interface AgentContext {
  // Accumulated knowledge from previous steps
  searchResults?: Array<{
    documentId: string;
    title: string;
    snippet: string;
    relevance: number;
  }>;

  // Extracted facts
  facts?: string[];

  // Intermediate reasoning
  reasoning?: string[];

  // Tool outputs
  toolOutputs?: Record<string, unknown>;

  // User preferences (for personalization)
  userPreferences?: Record<string, unknown>;
}

export interface AgentConfig {
  model?: string;
  temperature?: number;
  maxTokens?: number;
  maxSteps?: number;
  timeoutMs?: number;

  // Feature flags
  enableWebSearch?: boolean;
  enableCodeExecution?: boolean;
  enableToolUse?: boolean;

  // Safety settings
  requireConfirmation?: boolean;
  maxToolCalls?: number;
}

export interface AgentJobResult {
  executionId: string;
  status: "completed" | "failed" | "cancelled" | "timeout";
  result?: string;
  artifacts?: Array<{
    type: string;
    title: string;
    content: string;
  }>;
  totalSteps: number;
  totalTokens: number;
  durationMs: number;
  error?: string;
}

// === Queue Configuration ===

export const AGENT_QUEUE_NAME = "agent";

export const agentQueue = new Queue<AgentJobData, AgentJobResult>(
  AGENT_QUEUE_NAME,
  {
    connection: getSharedBullMqConnection(),
    defaultJobOptions: {
      attempts: 2, // Agents are expensive, limit retries
      backoff: {
        type: "exponential",
        delay: 5000, // 5 second initial delay
      },
      removeOnComplete: {
        count: 100,
        age: 24 * 3600, // Keep for 24 hours
      },
      removeOnFail: {
        count: 500,
        age: 7 * 24 * 3600, // Keep failures for 7 days
      },
    },
  }
);

// === Queue Operations ===

/**
 * Add an agent execution job to the queue
 */
export async function addAgentJob(
  data: Omit<AgentJobData, "traceContext">,
  options?: {
    priority?: number;
    delay?: number;
  }
) {
  const jobData: AgentJobData = {
    ...data,
    traceContext: extractTraceContext(),
  };

  return await agentQueue.add("agent-execute", jobData, {
    priority: options?.priority ?? 5,
    delay: options?.delay,
    jobId: `agent-${data.executionId}`,
  });
}

/**
 * Add a step execution job (for parallel step execution)
 */
export async function addAgentStepJob(
  executionId: string,
  step: AgentStep,
  context: AgentContext,
  teamId: string,
  userId: string,
  options?: {
    priority?: number;
  }
) {
  const jobData: AgentJobData = {
    executionId,
    teamId,
    userId,
    task: step.description,
    taskType: "action",
    currentStep: 0,
    plan: [step],
    context,
    traceContext: extractTraceContext(),
  };

  return await agentQueue.add("agent-step", jobData, {
    priority: options?.priority ?? 7, // Higher priority for individual steps
    jobId: `agent-step-${executionId}-${step.stepId}`,
  });
}

/**
 * Get agent job by ID
 */
export async function getAgentJob(jobId: string) {
  return await agentQueue.getJob(jobId);
}

/**
 * Cancel an agent execution
 */
export async function cancelAgentJob(executionId: string): Promise<boolean> {
  const job = await agentQueue.getJob(`agent-${executionId}`);
  if (job) {
    const state = await job.getState();
    if (state === "waiting" || state === "delayed") {
      await job.remove();
      return true;
    }
    // Can't cancel active jobs directly, need to handle in processor
  }
  return false;
}

/**
 * Get agent queue metrics
 */
export async function getAgentQueueMetrics() {
  const [waiting, active, completed, failed, delayed] = await Promise.all([
    agentQueue.getWaitingCount(),
    agentQueue.getActiveCount(),
    agentQueue.getCompletedCount(),
    agentQueue.getFailedCount(),
    agentQueue.getDelayedCount(),
  ]);

  return {
    waiting,
    active,
    completed,
    failed,
    delayed,
    total: waiting + active + completed + failed + delayed,
  };
}

/**
 * Get active agent executions for a user
 */
export async function getActiveAgentExecutions(
  userId: string
): Promise<string[]> {
  const activeJobs = await agentQueue.getActive();
  return activeJobs
    .filter((job) => job.data.userId === userId)
    .map((job) => job.data.executionId);
}

/**
 * Close the agent queue
 */
export async function closeAgentQueue(): Promise<void> {
  await agentQueue.close();
}
