import { HugeiconsIcon, type HugeiconsIconProps } from "@hugeicons/react";
import {
  ArtificialIntelligence01Icon,
  BookOpen01Icon,
  CommandLineIcon,
  FlowSquareIcon,
  GitBranchIcon,
  Home01Icon,
  Rocket01Icon,
  Search01Icon,
  ServerStackIcon,
  Settings01Icon,
} from "@hugeicons-pro/core-stroke-rounded";
import { type InferPageType, loader } from "fumadocs-core/source";
import { createElement, type ReactElement } from "react";
import { docs } from "@/.source";
import {
  AirtableIcon,
  AmplitudeIcon,
  AsanaIcon,
  AwsIotIcon,
  AzureDevOpsIcon,
  AzureIotIcon,
  BACnetIcon,
  BambooHRIcon,
  BenchlingIcon,
  BitbucketIcon,
  BoxIcon,
  BynderIcon,
  CanvaIcon,
  ClickUpIcon,
  CodaIcon,
  ConfluenceIcon,
  CoupaIcon,
  DatadogIcon,
  DoceboIcon,
  DocuSignIcon,
  DropboxIcon,
  Dynamics365Icon,
  EgnyteIcon,
  EvernoteIcon,
  FellowIcon,
  FHIRIcon,
  FifteenFiveIcon,
  FigmaIcon,
  FreshserviceIcon,
  GitHubIcon,
  GitLabIcon,
  GmailIcon,
  GongIcon,
  GoogleCalendarIcon,
  GoogleChatIcon,
  GoogleDriveIcon,
  GoogleSitesIcon,
  GreenhouseIcon,
  GuruIcon,
  HarvestIcon,
  HaystackIcon,
  HighspotIcon,
  HubSpotIcon,
  InsidedIcon,
  InteractIcon,
  IntercomIcon,
  IroncladIcon,
  JenkinsIcon,
  JFrogIcon,
  JiraIcon,
  KlueIcon,
  LessonlyIcon,
  LinearIcon,
  LookerStudioIcon,
  LoopioIcon,
  LucidIcon,
  LumAppsIcon,
  MarketoIcon,
  MatterportIcon,
  MicrosoftCalendarIcon,
  MindtickleIcon,
  MindtouchIcon,
  MiroIcon,
  MondayIcon,
  MQTTIcon,
  NetSuiteIcon,
  NiceCxoneIcon,
  NodeREDIcon,
  NotionIcon,
  OmniverseIcon,
  OneNoteIcon,
  OPCUAIcon,
  OpsGenieIcon,
  OutlookIcon,
  PagerDutyIcon,
  PanoptoIcon,
  PipedriveIcon,
  S3Icon,
  SalesforceIcon,
  SamsaraIcon,
  SecurityShieldIcon,
  ServiceNowIcon,
  SharePointIcon,
  SlackIcon,
  SmartThingsIcon,
  TeamsIcon,
  ThingsBoardIcon,
  VerkadaIcon,
  ViamIcon,
  WorkdayIcon,
  ZendeskIcon,
  ZoomIcon,
} from "@/components/connector-icons";

type IconType = HugeiconsIconProps["icon"];

const hugeIconMap: Record<string, IconType> = {
  BookOpen: BookOpen01Icon,
  Bot: ArtificialIntelligence01Icon,
  Connector: FlowSquareIcon,
  Connectors: FlowSquareIcon,
  GitBranch: GitBranchIcon,
  Home: Home01Icon,
  LayoutGrid: FlowSquareIcon,
  Rocket: Rocket01Icon,
  Search: Search01Icon,
  Server: ServerStackIcon,
  Settings: Settings01Icon,
  Terminal: CommandLineIcon,
};

const customIconMap: Record<
  string,
  (props: { size?: number }) => ReactElement
> = {
  Airtable: AirtableIcon,
  Asana: AsanaIcon,
  Slack: SlackIcon,
  Gmail: GmailIcon,
  GoogleDrive: GoogleDriveIcon,
  Notion: NotionIcon,
  Linear: LinearIcon,
  Bitbucket: BitbucketIcon,
  GitHub: GitHubIcon,
  GitLab: GitLabIcon,
  Samsara: SamsaraIcon,
  MQTT: MQTTIcon,
  OPCUA: OPCUAIcon,
  BACnet: BACnetIcon,
  ThingsBoard: ThingsBoardIcon,
  NodeRED: NodeREDIcon,
  FHIR: FHIRIcon,
  Matterport: MatterportIcon,
  Omniverse: OmniverseIcon,
  Viam: ViamIcon,
  AwsIot: AwsIotIcon,
  AzureIot: AzureIotIcon,
  SmartThings: SmartThingsIcon,
  Verkada: VerkadaIcon,
  Outlook: OutlookIcon,
  SharePoint: SharePointIcon,
  Teams: TeamsIcon,
  Confluence: ConfluenceIcon,
  Coupa: CoupaIcon,
  Docebo: DoceboIcon,
  Box: BoxIcon,
  Dropbox: DropboxIcon,
  Jira: JiraIcon,
  Figma: FigmaIcon,
  HubSpot: HubSpotIcon,
  Salesforce: SalesforceIcon,
  GoogleCalendar: GoogleCalendarIcon,
  GoogleChat: GoogleChatIcon,
  MicrosoftCalendar: MicrosoftCalendarIcon,
  SecurityShield: SecurityShieldIcon,
  ServiceNow: ServiceNowIcon,
  Zendesk: ZendeskIcon,
  InSided: InsidedIcon,
  Interact: InteractIcon,
  Intercom: IntercomIcon,
  Zoom: ZoomIcon,
  Monday: MondayIcon,
  PagerDuty: PagerDutyIcon,
  Pipedrive: PipedriveIcon,
  Freshservice: FreshserviceIcon,
  ClickUp: ClickUpIcon,
  AzureDevOps: AzureDevOpsIcon,
  S3: S3Icon,
  Gong: GongIcon,
  BambooHR: BambooHRIcon,
  Workday: WorkdayIcon,
  Greenhouse: GreenhouseIcon,
  Guru: GuruIcon,
  Coda: CodaIcon,
  OneNote: OneNoteIcon,
  Miro: MiroIcon,
  Dynamics365: Dynamics365Icon,
  OpsGenie: OpsGenieIcon,
  Datadog: DatadogIcon,
  DocuSign: DocuSignIcon,
  Marketo: MarketoIcon,
  Canva: CanvaIcon,
  Bynder: BynderIcon,
  Egnyte: EgnyteIcon,
  Evernote: EvernoteIcon,
  Fellow: FellowIcon,
  Harvest: HarvestIcon,
  Haystack: HaystackIcon,
  Highspot: HighspotIcon,
  GoogleSites: GoogleSitesIcon,
  Amplitude: AmplitudeIcon,
  FifteenFive: FifteenFiveIcon,
  Benchling: BenchlingIcon,
  Ironclad: IroncladIcon,
  Jenkins: JenkinsIcon,
  JFrog: JFrogIcon,
  Klue: KlueIcon,
  Lessonly: LessonlyIcon,
  LookerStudio: LookerStudioIcon,
  Loopio: LoopioIcon,
  Lucid: LucidIcon,
  LumApps: LumAppsIcon,
  Mindtouch: MindtouchIcon,
  Mindtickle: MindtickleIcon,
  NetSuite: NetSuiteIcon,
  NiceCxone: NiceCxoneIcon,
  Panopto: PanoptoIcon,
};

export const source = loader({
  baseUrl: "/docs",
  source: docs.toFumadocsSource(),
  icon(icon) {
    if (!icon) {
      return;
    }
    if (icon in customIconMap) {
      return createElement(customIconMap[icon], { size: 16 });
    }
    if (icon in hugeIconMap) {
      return createElement(HugeiconsIcon, {
        icon: hugeIconMap[icon],
        size: 16,
        strokeWidth: 1.5,
        color: "currentColor",
      });
    }
    return;
  },
});

export function getPageImage(page: InferPageType<typeof source>) {
  const segments = [...page.slugs, "image.png"];

  return {
    segments,
    url: `/og/docs/${segments.join("/")}`,
  };
}

export async function getLLMText(page: InferPageType<typeof source>) {
  const processed = await page.data.getText("processed");

  return `# ${page.data.title}

${processed}`;
}
