export {
  type AuthorSearchParams,
  type AutocompleteParams,
  type AutocompleteSuggestion,
  type RecentDocumentsParams,
  type SearchParams,
  type SearchRanking,
  type SearchResult,
  SearchService,
  type SimilarDocumentsParams,
  searchService,
  type ThreadSearchParams,
  type UnifiedSearchParams,
  type UnifiedSearchResult,
  type VideoSearchParams,
  type VideoSearchRanking,
  type VideoSearchResult,
  type VideoType,
} from "@openplane/services";
