import {
  AppType,
  AuthType,
  ConnectorType,
  SyncMode,
  type UnifiedApp,
} from "../types";

export const coupaApp: UnifiedApp = {
  id: AppType.COUPA,
  name: "Coupa",
  category: "Procurement & Spend Management",
  active: true,
  logo: AppType.COUPA,
  short_description:
    "Search purchase orders, invoices, requisitions, suppliers, contracts, and expense reports.",
  description:
    "Connect Coupa to search across business spend management data including purchase orders, invoices, requisitions, suppliers, contracts, and expense reports. Uses OAuth 2.0 client credentials with offset-based pagination.",
  images: [],
  installed: false,
  type: "official",
  connectorType: ConnectorType.SOURCE,
  developerName: "Coupa Software",
  website: "https://www.coupa.com",

  searchDisplay: {
    defaultIconKey: "ShoppingCart",
    documentTypes: {
      purchase_order: {
        label: "purchase order",
        iconKey: "ShoppingCart",
        category: "document",
      },
      invoice: {
        label: "invoice",
        iconKey: "Receipt",
        category: "document",
      },
      requisition: {
        label: "requisition",
        iconKey: "ClipboardList",
        category: "document",
      },
      supplier: {
        label: "supplier",
        iconKey: "Building",
        category: "contact",
      },
      contract: {
        label: "contract",
        iconKey: "FileText",
        category: "document",
      },
      expense_report: {
        label: "expense report",
        iconKey: "DollarSign",
        category: "document",
      },
    },
  },

  features: [
    "Purchase order search with status, amount, and supplier filtering",
    "Invoice indexing with approval status and payment tracking",
    "Requisition discovery with line items and approval chains",
    "Supplier directory with contact and compliance data",
    "Contract search with terms and expiration dates",
    "Expense report indexing with receipt and approval status",
    "OAuth 2.0 client credentials authentication",
    "Incremental sync via updated_at filters",
  ],

  auth: {
    type: AuthType.API_KEY,
    config: {
      headerName: "Authorization",
      documentationUrl:
        "https://compass.coupa.com/en-us/products/core-platform/integration-technical-documentation/the-coupa-core-api",
    },
  },

  streams: [
    {
      name: "purchase_orders",
      label: "Purchase Orders",
      description: "Purchase orders with line items and approval status",
      entityType: "resource",
      dataPoints: [
        "PO Number",
        "Status",
        "Total",
        "Currency",
        "Supplier",
        "Requester",
        "Ship To",
      ],
      isPii: false,
      syncMode: SyncMode.PERIODIC,
      defaultInterval: 30,
      supportsBackfill: true,
    },
    {
      name: "invoices",
      label: "Invoices",
      description: "Invoices with line items and payment status",
      entityType: "resource",
      dataPoints: [
        "Invoice Number",
        "Status",
        "Total",
        "Currency",
        "Supplier",
        "Due Date",
        "Payment Date",
      ],
      isPii: false,
      syncMode: SyncMode.PERIODIC,
      defaultInterval: 30,
      supportsBackfill: true,
    },
    {
      name: "requisitions",
      label: "Requisitions",
      description: "Purchase requisitions with approval workflow",
      entityType: "resource",
      dataPoints: [
        "Requisition Number",
        "Status",
        "Total",
        "Requester",
        "Department",
        "Justification",
      ],
      isPii: false,
      syncMode: SyncMode.PERIODIC,
      defaultInterval: 30,
      supportsBackfill: true,
    },
    {
      name: "suppliers",
      label: "Suppliers",
      description: "Supplier directory with contact and compliance info",
      entityType: "resource",
      dataPoints: [
        "Name",
        "Status",
        "Payment Terms",
        "Primary Contact",
        "Address",
        "Tax ID",
      ],
      isPii: true,
      syncMode: SyncMode.PERIODIC,
      defaultInterval: 60,
      supportsBackfill: true,
    },
    {
      name: "contracts",
      label: "Contracts",
      description: "Contracts with terms, dates, and associated suppliers",
      entityType: "resource",
      dataPoints: [
        "Contract Number",
        "Name",
        "Status",
        "Start Date",
        "End Date",
        "Total Value",
        "Supplier",
      ],
      isPii: false,
      syncMode: SyncMode.PERIODIC,
      defaultInterval: 60,
      supportsBackfill: true,
    },
    {
      name: "expense_reports",
      label: "Expense Reports",
      description: "Expense reports with line items and receipts",
      entityType: "resource",
      dataPoints: [
        "Title",
        "Status",
        "Total",
        "Currency",
        "Submitter",
        "Department",
        "Submit Date",
      ],
      isPii: true,
      syncMode: SyncMode.PERIODIC,
      defaultInterval: 30,
      supportsBackfill: true,
    },
  ],

  settings: [
    {
      id: "instance_url",
      label: "Instance URL",
      description:
        "Your Coupa instance URL (e.g., https://yourcompany.coupahost.com).",
      type: "text",
      required: true,
      value: "",
      placeholder: "https://yourcompany.coupahost.com",
    },
    {
      id: "client_id",
      label: "Client ID",
      description:
        "OAuth 2.0 client ID from Setup > Integrations > OAuth2/OpenID Connect Clients.",
      type: "text",
      required: true,
      value: "",
      placeholder: "your-client-id",
    },
    {
      id: "client_secret",
      label: "Client Secret",
      description: "OAuth 2.0 client secret from the same integration setup.",
      type: "password",
      required: true,
      value: "",
    },
    {
      id: "sync_purchase_orders",
      label: "Sync Purchase Orders",
      description: "Index purchase orders.",
      type: "switch",
      required: false,
      value: true,
    },
    {
      id: "sync_invoices",
      label: "Sync Invoices",
      description: "Index invoices.",
      type: "switch",
      required: false,
      value: true,
    },
    {
      id: "sync_requisitions",
      label: "Sync Requisitions",
      description: "Index purchase requisitions.",
      type: "switch",
      required: false,
      value: true,
    },
    {
      id: "sync_suppliers",
      label: "Sync Suppliers",
      description: "Index supplier directory.",
      type: "switch",
      required: false,
      value: true,
    },
    {
      id: "sync_contracts",
      label: "Sync Contracts",
      description: "Index contracts.",
      type: "switch",
      required: false,
      value: true,
    },
    {
      id: "sync_expense_reports",
      label: "Sync Expense Reports",
      description: "Index expense reports.",
      type: "switch",
      required: false,
      value: true,
    },
  ],
};

export default coupaApp;
