-- AlterEnum
ALTER TYPE "AppType" ADD VALUE 'MQTT';
ALTER TYPE "AppType" ADD VALUE 'OPCUA';
ALTER TYPE "AppType" ADD VALUE 'BACNET';
ALTER TYPE "AppType" ADD VALUE 'THINGSBOARD';
ALTER TYPE "AppType" ADD VALUE 'NODERED';
