import { createOpenAI } from "@ai-sdk/openai";
import type { EmbeddingModel, LanguageModel } from "ai";
import { getConfig } from "../config";
import type {
  AIProvider,
  ChatModelDefinition,
  EmbeddingModelDefinition,
} from "./types";

const CHAT_MODELS: ChatModelDefinition[] = [
  {
    id: "gpt-oss:120b",
    name: "GPT-OSS 120B",
    provider: "ollama",
    contextWindow: 131_072,
    maxOutputTokens: 131_072,
    supportsTools: true,
    supportsVision: false,
    supportsStreaming: true,
  },
  {
    id: "gpt-oss:20b",
    name: "GPT-OSS 20B",
    provider: "ollama",
    contextWindow: 131_072,
    maxOutputTokens: 131_072,
    supportsTools: true,
    supportsVision: false,
    supportsStreaming: true,
  },
  {
    id: "qwen3:235b",
    name: "Qwen 3 235B MoE",
    provider: "ollama",
    contextWindow: 128_000,
    maxOutputTokens: 8192,
    supportsTools: true,
    supportsVision: false,
    supportsStreaming: true,
  },
  {
    id: "qwen3:32b",
    name: "Qwen 3 32B",
    provider: "ollama",
    contextWindow: 128_000,
    maxOutputTokens: 8192,
    supportsTools: true,
    supportsVision: false,
    supportsStreaming: true,
  },
  {
    id: "qwen3:8b",
    name: "Qwen 3 8B",
    provider: "ollama",
    contextWindow: 128_000,
    maxOutputTokens: 8192,
    supportsTools: true,
    supportsVision: false,
    supportsStreaming: true,
  },
  {
    id: "qwen3-vl:32b",
    name: "Qwen 3 Vision 32B",
    provider: "ollama",
    contextWindow: 128_000,
    maxOutputTokens: 8192,
    supportsTools: true,
    supportsVision: true,
    supportsStreaming: true,
  },
  {
    id: "qwen3-vl:8b",
    name: "Qwen 3 Vision 8B",
    provider: "ollama",
    contextWindow: 128_000,
    maxOutputTokens: 8192,
    supportsTools: true,
    supportsVision: true,
    supportsStreaming: true,
  },
  {
    id: "qwen3-coder:30b",
    name: "Qwen 3 Coder 30B",
    provider: "ollama",
    contextWindow: 128_000,
    maxOutputTokens: 8192,
    supportsTools: true,
    supportsVision: false,
    supportsStreaming: true,
  },
  {
    id: "ministral-3:14b",
    name: "Ministral 3 14B",
    provider: "ollama",
    contextWindow: 128_000,
    maxOutputTokens: 8192,
    supportsTools: true,
    supportsVision: true,
    supportsStreaming: true,
  },
  {
    id: "ministral-3:8b",
    name: "Ministral 3 8B",
    provider: "ollama",
    contextWindow: 128_000,
    maxOutputTokens: 8192,
    supportsTools: true,
    supportsVision: true,
    supportsStreaming: true,
  },
  {
    id: "ministral-3:3b",
    name: "Ministral 3 3B",
    provider: "ollama",
    contextWindow: 128_000,
    maxOutputTokens: 8192,
    supportsTools: true,
    supportsVision: true,
    supportsStreaming: true,
  },
  {
    id: "deepseek-r1:671b",
    name: "DeepSeek R1 671B",
    provider: "ollama",
    contextWindow: 64_000,
    maxOutputTokens: 8192,
    supportsTools: true,
    supportsVision: false,
    supportsStreaming: true,
  },
  {
    id: "deepseek-r1:70b",
    name: "DeepSeek R1 70B",
    provider: "ollama",
    contextWindow: 64_000,
    maxOutputTokens: 8192,
    supportsTools: true,
    supportsVision: false,
    supportsStreaming: true,
  },
  {
    id: "deepseek-r1:8b",
    name: "DeepSeek R1 8B",
    provider: "ollama",
    contextWindow: 64_000,
    maxOutputTokens: 8192,
    supportsTools: true,
    supportsVision: false,
    supportsStreaming: true,
  },
  {
    id: "deepseek-v3.1:671b",
    name: "DeepSeek V3.1 671B",
    provider: "ollama",
    contextWindow: 128_000,
    maxOutputTokens: 8192,
    supportsTools: true,
    supportsVision: false,
    supportsStreaming: true,
  },
  {
    id: "glm-4.6",
    name: "GLM 4.6",
    provider: "ollama",
    contextWindow: 128_000,
    maxOutputTokens: 8192,
    supportsTools: true,
    supportsVision: false,
    supportsStreaming: true,
  },
  {
    id: "llama3.3:70b",
    name: "Llama 3.3 70B",
    provider: "ollama",
    contextWindow: 128_000,
    maxOutputTokens: 8192,
    supportsTools: true,
    supportsVision: false,
    supportsStreaming: true,
  },
  {
    id: "llama3.2:3b",
    name: "Llama 3.2 3B",
    provider: "ollama",
    contextWindow: 128_000,
    maxOutputTokens: 8192,
    supportsTools: true,
    supportsVision: false,
    supportsStreaming: true,
  },
  {
    id: "llama3.2-vision:11b",
    name: "Llama 3.2 Vision 11B",
    provider: "ollama",
    contextWindow: 128_000,
    maxOutputTokens: 8192,
    supportsTools: false,
    supportsVision: true,
    supportsStreaming: true,
  },
  {
    id: "llama3.1:8b",
    name: "Llama 3.1 8B",
    provider: "ollama",
    contextWindow: 128_000,
    maxOutputTokens: 8192,
    supportsTools: true,
    supportsVision: false,
    supportsStreaming: true,
  },
  {
    id: "llama3.1:70b",
    name: "Llama 3.1 70B",
    provider: "ollama",
    contextWindow: 128_000,
    maxOutputTokens: 8192,
    supportsTools: true,
    supportsVision: false,
    supportsStreaming: true,
  },
  {
    id: "qwen2.5:72b",
    name: "Qwen 2.5 72B",
    provider: "ollama",
    contextWindow: 128_000,
    maxOutputTokens: 8192,
    supportsTools: true,
    supportsVision: false,
    supportsStreaming: true,
  },
  {
    id: "qwen2.5-coder:32b",
    name: "Qwen 2.5 Coder 32B",
    provider: "ollama",
    contextWindow: 128_000,
    maxOutputTokens: 8192,
    supportsTools: true,
    supportsVision: false,
    supportsStreaming: true,
  },
  {
    id: "gemma3:27b",
    name: "Gemma 3 27B",
    provider: "ollama",
    contextWindow: 128_000,
    maxOutputTokens: 8192,
    supportsTools: false,
    supportsVision: true,
    supportsStreaming: true,
  },
  {
    id: "gemma3:12b",
    name: "Gemma 3 12B",
    provider: "ollama",
    contextWindow: 128_000,
    maxOutputTokens: 8192,
    supportsTools: false,
    supportsVision: true,
    supportsStreaming: true,
  },
  {
    id: "gemma3:4b",
    name: "Gemma 3 4B",
    provider: "ollama",
    contextWindow: 128_000,
    maxOutputTokens: 8192,
    supportsTools: false,
    supportsVision: true,
    supportsStreaming: true,
  },
  {
    id: "phi4:14b",
    name: "Phi 4 14B",
    provider: "ollama",
    contextWindow: 16_000,
    maxOutputTokens: 4096,
    supportsTools: false,
    supportsVision: false,
    supportsStreaming: true,
  },
  {
    id: "phi4-mini:3.8b",
    name: "Phi 4 Mini 3.8B",
    provider: "ollama",
    contextWindow: 16_000,
    maxOutputTokens: 4096,
    supportsTools: true,
    supportsVision: false,
    supportsStreaming: true,
  },
  {
    id: "mistral:7b",
    name: "Mistral 7B",
    provider: "ollama",
    contextWindow: 32_768,
    maxOutputTokens: 4096,
    supportsTools: true,
    supportsVision: false,
    supportsStreaming: true,
  },
  {
    id: "mistral-nemo:12b",
    name: "Mistral Nemo 12B",
    provider: "ollama",
    contextWindow: 128_000,
    maxOutputTokens: 8192,
    supportsTools: true,
    supportsVision: false,
    supportsStreaming: true,
  },
  {
    id: "mistral-small:24b",
    name: "Mistral Small 24B",
    provider: "ollama",
    contextWindow: 128_000,
    maxOutputTokens: 8192,
    supportsTools: true,
    supportsVision: false,
    supportsStreaming: true,
  },
  {
    id: "mixtral:8x7b",
    name: "Mixtral 8x7B",
    provider: "ollama",
    contextWindow: 32_768,
    maxOutputTokens: 4096,
    supportsTools: true,
    supportsVision: false,
    supportsStreaming: true,
  },
  {
    id: "codestral:22b",
    name: "Codestral 22B",
    provider: "ollama",
    contextWindow: 32_768,
    maxOutputTokens: 8192,
    supportsTools: false,
    supportsVision: false,
    supportsStreaming: true,
  },
  {
    id: "devstral:24b",
    name: "Devstral 24B",
    provider: "ollama",
    contextWindow: 128_000,
    maxOutputTokens: 8192,
    supportsTools: true,
    supportsVision: false,
    supportsStreaming: true,
  },
];

const EMBEDDING_MODELS: EmbeddingModelDefinition[] = [
  {
    id: "nomic-embed-text",
    name: "Nomic Embed Text",
    provider: "ollama",
    dimensions: 768,
    maxTokens: 8192,
  },
  {
    id: "mxbai-embed-large",
    name: "MxBai Embed Large",
    provider: "ollama",
    dimensions: 1024,
    maxTokens: 512,
  },
  {
    id: "bge-m3",
    name: "BGE M3",
    provider: "ollama",
    dimensions: 1024,
    maxTokens: 8192,
  },
  {
    id: "snowflake-arctic-embed",
    name: "Snowflake Arctic Embed",
    provider: "ollama",
    dimensions: 1024,
    maxTokens: 512,
  },
  {
    id: "all-minilm",
    name: "All MiniLM",
    provider: "ollama",
    dimensions: 384,
    maxTokens: 512,
  },
  {
    id: "embeddinggemma",
    name: "Embedding Gemma",
    provider: "ollama",
    dimensions: 768,
    maxTokens: 2048,
  },
];

export function createOllamaProvider(): AIProvider {
  const config = getConfig();
  const providerConfig = config.providers.ollama;

  const ollama = createOpenAI({
    baseURL: providerConfig.baseURL,
    apiKey: "ollama",
  });

  return {
    id: "ollama",
    name: "Ollama (Local)",

    getChatModel(modelId: string): LanguageModel {
      return ollama(modelId);
    },

    getEmbeddingModel(modelId: string): EmbeddingModel {
      return ollama.embedding(modelId);
    },

    listChatModels(): ChatModelDefinition[] {
      return CHAT_MODELS;
    },

    listEmbeddingModels(): EmbeddingModelDefinition[] {
      return EMBEDDING_MODELS;
    },

    isConfigured(): boolean {
      return !!providerConfig.baseURL;
    },
  };
}
