import {
  AppType,
  AuthType,
  ConnectorType,
  SyncMode,
  type UnifiedApp,
} from "../types";

export const harvestApp: UnifiedApp = {
  id: AppType.HARVEST,
  name: "Harvest",
  category: "Time Tracking & Invoicing",
  active: true,
  logo: AppType.HARVEST,
  short_description:
    "Search across time entries, projects, clients, invoices, and expenses.",
  description:
    "Connect Harvest to search across time tracking and invoicing data including time entries, projects, tasks, clients, invoices, and expenses. Supports OAuth 2.0 with page-based pagination and updated_since incremental sync.",
  images: [],
  installed: false,
  type: "official",
  connectorType: ConnectorType.SOURCE,
  developerName: "Iridesco dba Harvest",
  website: "https://www.getharvest.com",

  searchDisplay: {
    defaultIconKey: "Clock",
    documentTypes: {
      time_entry: {
        label: "time entry",
        iconKey: "Clock",
        category: "event",
      },
      project: {
        label: "project",
        iconKey: "Folder",
        category: "project",
      },
      task: {
        label: "task",
        iconKey: "CheckSquareIcon",
        category: "task",
      },
      client: {
        label: "client",
        iconKey: "Building",
        category: "account",
      },
      invoice: {
        label: "invoice",
        iconKey: "FileText",
        category: "document",
      },
      expense: {
        label: "expense",
        iconKey: "CreditCard",
        category: "event",
      },
    },
  },

  features: [
    "Time entry search with project, task, and user details",
    "Project tracking with budgets, billing rates, and status",
    "Client and invoice data for financial visibility",
    "Expense tracking with receipt metadata",
    "Incremental sync via updated_since parameter",
    "OAuth 2.0 authentication with automatic token refresh",
  ],

  auth: {
    type: AuthType.OAUTH2,
    config: {
      authUrl: "https://id.getharvest.com/oauth2/authorize",
      tokenUrl: "https://id.getharvest.com/api/v2/oauth2/token",
      redirectPath: "/connectors/setup/harvest/oauth/callback",
      scopes: [],
    },
  },

  streams: [
    {
      name: "time_entries",
      label: "Time Entries",
      description: "Time entries with project, task, user, and duration",
      entityType: "activity",
      dataPoints: [
        "Hours",
        "Notes",
        "Project",
        "Task",
        "User",
        "Date",
        "Billable",
      ],
      isPii: false,
      syncMode: SyncMode.PERIODIC,
      defaultInterval: 15,
      supportsBackfill: true,
    },
    {
      name: "projects",
      label: "Projects",
      description: "Projects with budgets, billing, and client assignments",
      entityType: "resource",
      dataPoints: ["Name", "Code", "Client", "Budget", "BillBy", "Active"],
      isPii: false,
      syncMode: SyncMode.PERIODIC,
      defaultInterval: 60,
      supportsBackfill: true,
    },
    {
      name: "tasks",
      label: "Tasks",
      description: "Task definitions used across projects",
      entityType: "resource",
      dataPoints: ["Name", "Billable", "Active"],
      isPii: false,
      syncMode: SyncMode.PERIODIC,
      defaultInterval: 60,
      supportsBackfill: true,
    },
    {
      name: "clients",
      label: "Clients",
      description: "Client records with contact information",
      entityType: "resource",
      dataPoints: ["Name", "Currency", "Active"],
      isPii: false,
      syncMode: SyncMode.PERIODIC,
      defaultInterval: 60,
      supportsBackfill: true,
    },
    {
      name: "invoices",
      label: "Invoices",
      description: "Invoices with line items, amounts, and payment status",
      entityType: "resource",
      dataPoints: [
        "Number",
        "Client",
        "Amount",
        "DueDate",
        "Status",
        "Currency",
      ],
      isPii: false,
      syncMode: SyncMode.PERIODIC,
      defaultInterval: 30,
      supportsBackfill: true,
    },
    {
      name: "expenses",
      label: "Expenses",
      description: "Expense entries with project and category details",
      entityType: "activity",
      dataPoints: [
        "Amount",
        "Project",
        "Category",
        "Notes",
        "Date",
        "Billable",
      ],
      isPii: false,
      syncMode: SyncMode.PERIODIC,
      defaultInterval: 30,
      supportsBackfill: true,
    },
  ],

  settings: [
    {
      id: "oauth_input_method",
      label: "Credentials",
      description: "Enter Harvest OAuth app credentials.",
      type: "select",
      required: true,
      value: "manual",
      options: [{ label: "Enter manually", value: "manual" }],
    },
    {
      id: "client_id",
      label: "Client ID",
      description: "From Harvest OAuth2 application settings",
      type: "text",
      required: true,
      value: "",
      placeholder: "abc123...",
    },
    {
      id: "client_secret",
      label: "Client Secret",
      description: "From Harvest OAuth2 application settings",
      type: "password",
      required: true,
      value: "",
    },
    {
      id: "sync_expenses",
      label: "Sync Expenses",
      description: "Index expense entries as searchable documents.",
      type: "switch",
      required: false,
      value: true,
    },
    {
      id: "sync_invoices",
      label: "Sync Invoices",
      description: "Index invoices as searchable documents.",
      type: "switch",
      required: false,
      value: true,
    },
    {
      id: "lookback_days",
      label: "History (days)",
      description: "How far back to sync. Leave empty for unlimited.",
      type: "text",
      required: false,
      value: "",
      placeholder: "Unlimited",
    },
  ],
};

export default harvestApp;
