import { build } from "esbuild";
import { chmod } from "node:fs/promises";

await build({
  entryPoints: ["src/index.ts"],
  bundle: true,
  format: "esm",
  platform: "node",
  target: "node18",
  outfile: "dist/index.js",
  minify: true,
  banner: { js: "#!/usr/bin/env node" },
  external: [
    "@modelcontextprotocol/sdk",
    "@modelcontextprotocol/sdk/*",
    "@prisma/client",
    "@prisma/client/*",
    "@prisma/engines",
    "@prisma/*",
    "@temporalio/*",
    "@duckdb/*",
    "@swc/*",
    "@aws-sdk/*",
    "@openbeam/ai",
    "@openbeam/ai/*",
    "@openbeam/analytics",
    "@openbeam/analytics/*",
    "@openbeam/services",
    "@openbeam/services/*",
    "@openbeam/auth",
    "@openbeam/auth/*",
    "@openbeam/integrations",
    "@openbeam/integrations/*",
    "@openbeam/media",
    "@openbeam/media/*",
    "@openbeam/storage",
    "@openbeam/storage/*",
    "@openbeam/observability",
    "@openbeam/observability/*",
    "@openbeam/orchestrations",
    "@openbeam/orchestrations/*",
    "ioredis",
    "mqtt",
    "node-opcua-client",
    "node-sql-parser",
    "playwright-core",
    "electron",
    "chromium-bidi",
    "chromium-bidi/*",
  ],
  logLevel: "info",
});

await chmod("dist/index.js", 0o755);
